/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ping.interfaceSAP.mapMaster;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import ping.interfaceSAP.entity.article;
import ping.interfaceSAP.entity.site;
import ping.interfaceSAP.eventFocus;
import ping.interfaceSAP.showMessage;
import ping.interfaceSAP.utilitySAP;
import utilititiesfunction.UserLogin;

/**
 *
 * @author soneping
 */
public class sap_updatemaster_csv extends javax.swing.JDialog {

    article ar = new article();
    site si = new site();
    utilitySAP us = new utilitySAP();
    eventFocus ef = new eventFocus();

    public sap_updatemaster_csv(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        ef.setFocusSwing(txt_site);
        ef.setFocusSwing(txt_aritcle);

        jTabbedPane1.setSelectedIndex(0);
        jTabbedPane1.setFocusable(false);

        btn_article.setFocusable(false);
        btn_updateArticle.setFocusable(false);
        btn_site.setFocusable(false);
        btn_updateSite.setFocusable(false);
        us.openTextFiled(txt_aritcle, true, true);
        us.openTextFiled(txt_site, true, false);
        areaArticle.setFocusable(false);
        areaSite.setFocusable(false);
        areaArticle.setText("");
        areaSite.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_aritcle = new javax.swing.JTextField();
        btn_article = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaArticle = new javax.swing.JTextArea();
        btn_updateArticle = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_site = new javax.swing.JTextField();
        btn_site = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaSite = new javax.swing.JTextArea();
        btn_updateSite = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_site1 = new javax.swing.JTextField();
        btn_site1 = new javax.swing.JButton();
        btn_updateCharge = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaCharge = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Import CSV File (Mapping SAP master)");

        jTabbedPane1.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Norasi", 1, 15)); // NOI18N
        jLabel1.setText("Path to file");

        txt_aritcle.setFont(new java.awt.Font("Norasi", 1, 15)); // NOI18N
        txt_aritcle.setText("jTextField1");
        txt_aritcle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_aritcleKeyPressed(evt);
            }
        });

        btn_article.setFont(new java.awt.Font("Norasi", 1, 15)); // NOI18N
        btn_article.setText("...");
        btn_article.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_articleActionPerformed(evt);
            }
        });

        areaArticle.setColumns(20);
        areaArticle.setRows(5);
        jScrollPane1.setViewportView(areaArticle);

        btn_updateArticle.setFont(new java.awt.Font("Norasi", 1, 15)); // NOI18N
        btn_updateArticle.setText("Update");
        btn_updateArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateArticleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_aritcle, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_article, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                    .addComponent(btn_updateArticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_aritcle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_article, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_updateArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Article Master", jPanel1);

        jLabel2.setFont(new java.awt.Font("Norasi", 1, 15)); // NOI18N
        jLabel2.setText("Path to file");

        txt_site.setFont(new java.awt.Font("Norasi", 1, 15)); // NOI18N
        txt_site.setText("jTextField1");
        txt_site.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_siteKeyPressed(evt);
            }
        });

        btn_site.setFont(new java.awt.Font("Norasi", 1, 15)); // NOI18N
        btn_site.setText("...");
        btn_site.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siteActionPerformed(evt);
            }
        });

        areaSite.setColumns(20);
        areaSite.setRows(5);
        jScrollPane2.setViewportView(areaSite);

        btn_updateSite.setFont(new java.awt.Font("Norasi", 1, 15)); // NOI18N
        btn_updateSite.setText("Update");
        btn_updateSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateSiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_site, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_site, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                    .addComponent(btn_updateSite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_site, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_site, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_updateSite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Site Master", jPanel2);

        jLabel3.setFont(new java.awt.Font("Norasi", 1, 15)); // NOI18N
        jLabel3.setText("Path to file");

        txt_site1.setFont(new java.awt.Font("Norasi", 1, 15)); // NOI18N
        txt_site1.setText("jTextField1");
        txt_site1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_site1KeyPressed(evt);
            }
        });

        btn_site1.setFont(new java.awt.Font("Norasi", 1, 15)); // NOI18N
        btn_site1.setText("...");
        btn_site1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_site1ActionPerformed(evt);
            }
        });

        btn_updateCharge.setFont(new java.awt.Font("Norasi", 1, 15)); // NOI18N
        btn_updateCharge.setText("Update");
        btn_updateCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateChargeActionPerformed(evt);
            }
        });

        areaCharge.setColumns(20);
        areaCharge.setRows(5);
        jScrollPane3.setViewportView(areaCharge);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_site1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_site1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                    .addComponent(btn_updateCharge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_site1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_site1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_updateCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Chargemaster", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        setSize(new java.awt.Dimension(651, 378));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_articleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_articleActionPerformed
        browsePathToFile(txt_aritcle, btn_article);
    }//GEN-LAST:event_btn_articleActionPerformed

    private void btn_siteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siteActionPerformed
        browsePathToFile(txt_site, btn_site);
    }//GEN-LAST:event_btn_siteActionPerformed

    private void txt_aritcleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_aritcleKeyPressed
        if (evt.getKeyCode() == evt.VK_F1) {
            browsePathToFile(txt_aritcle, btn_article);
        } else if (evt.getKeyCode() == evt.VK_ESCAPE) {
            dispose();
        } else if (evt.getKeyCode() == evt.VK_F5) {
            btn_updateArticleActionPerformed(null);
        }
    }//GEN-LAST:event_txt_aritcleKeyPressed

    private void txt_siteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_siteKeyPressed
        if (evt.getKeyCode() == evt.VK_F1) {
            browsePathToFile(txt_site, btn_site);
        } else if (evt.getKeyCode() == evt.VK_ESCAPE) {
            dispose();
        } else if (evt.getKeyCode() == evt.VK_F5) {
            btn_updateSiteActionPerformed(null);
        }
    }//GEN-LAST:event_txt_siteKeyPressed

    private void btn_updateArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateArticleActionPerformed
        new processMainThread(txt_aritcle, areaArticle).start();
    }//GEN-LAST:event_btn_updateArticleActionPerformed

    private void btn_updateSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateSiteActionPerformed
        new processMainThread(txt_site, areaSite).start();
    }//GEN-LAST:event_btn_updateSiteActionPerformed

    private void txt_site1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_site1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_site1KeyPressed

    private void btn_site1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_site1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_site1ActionPerformed

    private void btn_updateChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateChargeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sap_updatemaster_csv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sap_updatemaster_csv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sap_updatemaster_csv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sap_updatemaster_csv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                sap_updatemaster_csv dialog = new sap_updatemaster_csv(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaArticle;
    private javax.swing.JTextArea areaCharge;
    private javax.swing.JTextArea areaSite;
    private javax.swing.JButton btn_article;
    private javax.swing.JButton btn_site;
    private javax.swing.JButton btn_site1;
    private javax.swing.JButton btn_updateArticle;
    private javax.swing.JButton btn_updateCharge;
    private javax.swing.JButton btn_updateSite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txt_aritcle;
    private javax.swing.JTextField txt_site;
    private javax.swing.JTextField txt_site1;
    // End of variables declaration//GEN-END:variables
    private void browsePathToFile(JTextField txt, JButton btn) {
        JFileChooser chooser = new JFileChooser();
        chooser.setLocation(btn.getX(), btn.getY());
        chooser.setCurrentDirectory(new File("."));
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        chooser.showOpenDialog(null);
        File selectedPfile = chooser.getSelectedFile();
        try {
            txt.setText(selectedPfile.getCanonicalPath());
            txt.setFocusable(true);
            txt.requestFocus();
        } catch (IOException ex) {
            new showMessage().showMessageError(ex.getMessage(), "browsePathToFile");
        } finally {
            txt.requestFocus();
        }
    }

    private void processImport(JTextField path2file, JTextArea area) {

        int haveSAP = 0;
        int totalSAP = 0;
        int havePro = 0;
        int totalPro = 0;

        area.setText("");
        int tab = jTabbedPane1.getSelectedIndex();
        String strPath2File = path2file.getText();
        String strFile = "";
        File fObject = null;
        if (strPath2File.length() <= 0) {
            path2file.requestFocus();
        } else {
            fObject = new File(strPath2File);
            strFile = fObject.getName();

            int index = strFile.indexOf(".csv");
            if (strFile.substring(index, strFile.length()).equals(".csv")) {
                if (!fObject.canRead()) {
                    new showMessage().showMessageError("ไม่สามารถอ่านไฟล์ได้", "processImport(" + path2file + ")");
                } else {
                    try {
                        boolean eof = false;
                        FileReader file = new FileReader(strPath2File);
                        BufferedReader buff = new BufferedReader(file);

                        while (!eof) {
                            String line = buff.readLine();
                            if (line == null) {
                                eof = true;
                            } else if (!line.equals("")) {
                                String[] spData = line.split("\\t");
                                String bor_code = spData[0];
                                String str_sap = spData[1];
                                String cashBank = (spData.length == 3 ? spData[2] : "");
                                //doing something
                                if (tab == 0) {
                                    if (str_sap.length() < 18) {
                                        str_sap = us.addZeroBefore(18, str_sap);
                                    }
                                    totalSAP++;
                                    totalPro++;
                                    boolean haveArticle = false;
                                    boolean havePLU = false;
                                    ar = ar.seekArticleMaster(str_sap);
                                    if (ar.isArticle()) {
                                        haveArticle = true;
                                        haveSAP++;
                                    }
                                    ar = ar.seek(bor_code);
                                    if (ar.isArticle()) {
                                        havePLU = true;
                                        havePro++;
                                    }
                                    ar.updateProductArticle(bor_code, str_sap);
                                    area.append("Pcode [" + bor_code + "] " + (havePLU ? "Have" : "Havn't") + "\t\t" + "Article [" + str_sap + "] " + (haveArticle ? "Have" : "Havn't") + "\n");
                                } else {
                                    if (str_sap.length() < 10) {
                                        str_sap = us.addZeroBefore(10, str_sap);
                                    }
                                    si.updateBranfileSite(bor_code, str_sap, cashBank);
                                    area.append("Bcode [" + bor_code + "]" + "\t" + "Site [" + str_sap + "]" + "\t" + "Bank [" + cashBank + "]" + "\n");
                                }
                                area.setCaretPosition(area.getDocument().getLength());
                            }
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                        new showMessage().showMessageError(e.getMessage(), "processImport");
                    } finally {
                        area.append("\n");
                        area.append("\n");
                        area.append("=======================================");
                        area.append("\n");
                        if (tab == 0) {
                            area.append("Have Article " + haveSAP + " / " + totalSAP + "\n");
                            area.append("Have PLU " + havePro + " / " + totalPro + "\n");
                        } else {

                        }
                        area.setCaretPosition(area.getDocument().getLength());
                        new showMessage().showMessageInformation("Mapping Finish.", "sap_updatemaster_csv.processImport");
//                        dispose();
                    }
                }
            } else {
                us.openTextFiled(path2file, false, true);
            }
        }
    }

    class processMainThread extends Thread {

        JTextField path2file;
        JTextArea area;

        public processMainThread(JTextField path2file, JTextArea area) {
            super();
            this.path2file = path2file;
            this.area = area;
        }

        public void run() {
            processImport(this.path2file, this.area);
        }
    }

    private void checkuserconfig() {
        UserLogin userrec = UserLogin.userlogin;
        if (userrec.getTran8().equals("1")) {
            btn_updateArticle.setEnabled(false);
            btn_updateSite.setEnabled(false);
        } else {
            btn_updateArticle.setEnabled(true);
            btn_updateSite.setEnabled(true);
        }
    }
}
