/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ingredent_bom;

import dbutility.dbUtility;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import report.Report;
import utilititiesfunction.ThaiUtilities;

/**
 *
 * @author natee
 */
public class listIngredent extends javax.swing.JDialog {

    /**
     * Creates new form listIngredent
     */
    formatDateNumber fdn = new formatDateNumber();
    dbUtility db = new dbUtility();
    Statement stmt;
    ThaiUtilities cvth = new ThaiUtilities();
    String fix = "F";
    public String code = "";
    public String name = "";
    public String group = "";
    public String unit = "";
    public String subunit = "";
    public Double scale = 0.000;
    public Double pacost = 0.000;

    public listIngredent(java.awt.Frame parent, boolean modal, String type) {
        super(parent, modal);
        initComponents();

        db.dbconnect();
        setTable();

        fix = type;
        clearText();
        showtable("pcode", "%%%", fix);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        mb_enter = new javax.swing.JLabel();
        d_h3 = new javax.swing.JLabel();
        d_h2 = new javax.swing.JLabel();
        txt_pdesc = new javax.swing.JTextField();
        txt_pcode = new javax.swing.JTextField();
        db_h1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mb_test = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        db_lblcount = new javax.swing.JLabel();
        btn_showall = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        d_h4 = new javax.swing.JLabel();
        txt_pgroup = new javax.swing.JTextField();
        combo1 = new javax.swing.JComboBox();
        btn_print = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(213, 202, 253));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBackground(new java.awt.Color(9, 0, 91));

        mb_enter.setFont(new java.awt.Font("Norasi", 1, 16)); // NOI18N
        mb_enter.setForeground(new java.awt.Color(255, 37, 37));
        mb_enter.setText("ใส่ข้อมูลตามช่องที่ต้องการแล้วกด Enter");
        mb_enter.setName("mb_enter");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(mb_enter)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(mb_enter)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        d_h3.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_h3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_h3.setText("ชื่อวัตถุดิบ");
        d_h3.setName("d_h3");

        d_h2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_h2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_h2.setText("รหัสวัตถุดิบ");
        d_h2.setName("d_h2");

        txt_pdesc.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txt_pdesc.setText("txt_pdesc");
        txt_pdesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pdescKeyPressed(evt);
            }
        });

        txt_pcode.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txt_pcode.setText("txt_pcode");
        txt_pcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pcodeKeyPressed(evt);
            }
        });

        db_h1.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_h1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        db_h1.setText("ค้นหาจากสินค้า");
        db_h1.setName("db_h1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(d_h2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(d_h3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_pdesc, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(txt_pcode)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(db_h1)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(db_h1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pcode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_h2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d_h3)
                    .addComponent(txt_pdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(194, 254, 140));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mb_test.setFont(new java.awt.Font("Norasi", 1, 16)); // NOI18N
        mb_test.setForeground(new java.awt.Color(255, 37, 37));
        mb_test.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mb_test.setText("การค้นหาข้อมูล สามารถใช้ส่วนหนึ่งของคำในการค้นหาได้เช่น \"เจ้าพระยา\"เพื่อหา\"บริษัท เจ้าพระยาคอมพิวเทค จำกัด\"");
        mb_test.setName("mb_test");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(mb_test, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mb_test))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1000, -1));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        db_lblcount.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_lblcount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        db_lblcount.setText("จำนวนรายการ 0 รายการ");
        db_lblcount.setName("db_lblcount");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(db_lblcount, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(db_lblcount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 290, -1));

        btn_showall.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btn_showall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Trash-icon.png"))); // NOI18N
        btn_showall.setText("F11-แสดงทั้งหมด");
        btn_showall.setName("btn_showall");
        btn_showall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showallActionPerformed(evt);
            }
        });
        jPanel1.add(btn_showall, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 160, 35));

        jPanel5.setBackground(new java.awt.Color(255, 252, 193));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        d_h4.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_h4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_h4.setText("กลุ่มสินค้า");
        d_h4.setName("d_h4");

        txt_pgroup.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txt_pgroup.setText("txt_pgroup");
        txt_pgroup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pgroupKeyPressed(evt);
            }
        });

        combo1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });
        combo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                combo1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(d_h4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo1, 0, 378, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d_h4)
                    .addComponent(txt_pgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 610, -1));

        btn_print.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Printer-icon.png"))); // NOI18N
        btn_print.setText("F12-พิมพ์");
        btn_print.setName("btn_showall");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });
        jPanel1.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 160, 35));

        tbltable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "รหัสวัตถุดิบ", "ชื่อวัตถุดิบ", "กลุ่ม", "หน่วยนับหลัก", "หน่วยย่อย", "อัตราส่วน / หน่วยนับหลัก", "ต้นทุนเฉลี่ย"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbltable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltableMouseClicked(evt);
            }
        });
        tbltable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbltableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbltable);
        tbltable.getColumnModel().getColumn(0).setPreferredWidth(130);
        tbltable.getColumnModel().getColumn(1).setPreferredWidth(360);
        tbltable.getColumnModel().getColumn(2).setPreferredWidth(70);
        tbltable.getColumnModel().getColumn(3).setPreferredWidth(100);
        tbltable.getColumnModel().getColumn(4).setPreferredWidth(80);
        tbltable.getColumnModel().getColumn(5).setPreferredWidth(150);
        tbltable.getColumnModel().getColumn(6).setPreferredWidth(100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1024)/2, (screenSize.height-793)/2, 1024, 793);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_showallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showallActionPerformed
        showtable("pcode", "%%%", fix);
    }//GEN-LAST:event_btn_showallActionPerformed

    private void tbltableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltableMouseClicked
        int index = tbltable.getSelectedRow();
        if (evt.getClickCount() == 2) {
            code = tbltable.getValueAt(index, 0).toString();
            name = tbltable.getValueAt(index, 1).toString();
            group = tbltable.getValueAt(index, 2).toString();
            unit = tbltable.getValueAt(index, 3).toString();
            subunit = tbltable.getValueAt(index, 4).toString();
            scale = Double.parseDouble(fdn.convertDoubleString(tbltable.getValueAt(index, 5).toString()));
            pacost = Double.parseDouble(fdn.convertDoubleString(tbltable.getValueAt(index, 6).toString()));
            dispose();
        }
    }//GEN-LAST:event_tbltableMouseClicked

    private void txt_pcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pcodeKeyPressed
        String data = txt_pcode.getText().trim();
        if (data.length() <= 0) {
            data = "%%%";
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            showtable("pcode", data, fix);
        } else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            dispose();
        } else if (evt.getKeyCode() == KeyEvent.VK_F11) {
            showtable("pcode", "%%%", fix);
        }
    }//GEN-LAST:event_txt_pcodeKeyPressed

    private void txt_pdescKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pdescKeyPressed
        String data = txt_pdesc.getText().trim();
        if (data.length() <= 0) {
            data = "%%%";
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            showtable("pdesc", data, fix);
        } else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            dispose();
        } else if (evt.getKeyCode() == KeyEvent.VK_F11) {
            showtable("pcode", "%%%", fix);
        }
    }//GEN-LAST:event_txt_pdescKeyPressed

    private void txt_pgroupKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pgroupKeyPressed
        String data = txt_pgroup.getText().trim();
        if (data.length() <= 0) {
            data = "%%%";
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            showtable("pgroup", data, fix);
        } else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            dispose();
        } else if (evt.getKeyCode() == KeyEvent.VK_F11) {
            showtable("pcode", "%%%", fix);
        }
    }//GEN-LAST:event_txt_pgroupKeyPressed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        try {
            String TempStr = combo1.getSelectedItem().toString();
            String ArrayStr[] = TempStr.split(" - ");
            txt_pgroup.setText(ArrayStr[0]);
            txt_pgroup.requestFocus();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_combo1ActionPerformed

    private void combo1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combo1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String TempStr = combo1.getSelectedItem().toString();
            String ArrayStr[] = TempStr.split(" - ");
            txt_pgroup.setText(ArrayStr[0]);
            txt_pgroup.requestFocus();
        }
    }//GEN-LAST:event_combo1KeyPressed

    private void tbltableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbltableKeyPressed
        int index = tbltable.getSelectedRow();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            code = tbltable.getValueAt(index, 0).toString();
            name = tbltable.getValueAt(index, 1).toString();
            group = tbltable.getValueAt(index, 2).toString();
            unit = tbltable.getValueAt(index, 3).toString();
            subunit = tbltable.getValueAt(index, 4).toString();
            scale = Double.parseDouble(fdn.convertDoubleString(tbltable.getValueAt(index, 5).toString()));
            pacost = Double.parseDouble(fdn.convertDoubleString(tbltable.getValueAt(index, 6).toString()));
            dispose();
        }
    }//GEN-LAST:event_tbltableKeyPressed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        btnPrint();
    }//GEN-LAST:event_btn_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listIngredent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listIngredent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listIngredent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listIngredent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                listIngredent dialog = new listIngredent(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_showall;
    private javax.swing.JComboBox combo1;
    private javax.swing.JLabel d_h2;
    private javax.swing.JLabel d_h3;
    private javax.swing.JLabel d_h4;
    private javax.swing.JLabel db_h1;
    private javax.swing.JLabel db_lblcount;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mb_enter;
    private javax.swing.JLabel mb_test;
    private javax.swing.JTable tbltable;
    private javax.swing.JTextField txt_pcode;
    private javax.swing.JTextField txt_pdesc;
    private javax.swing.JTextField txt_pgroup;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel model;

    private void setTable() {

        model = (DefaultTableModel) tbltable.getModel();
        tbltable.setShowGrid(true);
        tbltable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tbltable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbltable.setRowSelectionAllowed(true);
        tbltable.setBackground(java.awt.Color.WHITE);
        tbltable.setGridColor(java.awt.Color.gray);
        tbltable.setRowHeight(24);
        tbltable.setFont(new Font("Norasi", Font.PLAIN, 14));
        JTableHeader tHeader = tbltable.getTableHeader();
        tHeader.setFont(new Font("Norasi", Font.BOLD, 14));
        DefaultTableCellRenderer l = new DefaultTableCellRenderer();
        l.setHorizontalAlignment(SwingConstants.LEFT);
        DefaultTableCellRenderer r = new DefaultTableCellRenderer();
        r.setHorizontalAlignment(SwingConstants.RIGHT);
        DefaultTableCellRenderer c = new DefaultTableCellRenderer();
        c.setHorizontalAlignment(SwingConstants.CENTER);
        TableColumnModel tcm = tbltable.getColumnModel();
        tcm.getColumn(0).setCellRenderer(l);
        tcm.getColumn(1).setCellRenderer(l);
        tcm.getColumn(2).setCellRenderer(l);
        tcm.getColumn(3).setCellRenderer(l);
        tcm.getColumn(4).setCellRenderer(l);
        tcm.getColumn(5).setCellRenderer(r);
        tcm.getColumn(6).setCellRenderer(r);

    }

    private void clearTable() {
        int size = tbltable.getRowCount();
        for (int i = 0; i < size; i++) {
            model.removeRow(0);
        }
    }

    private void clearText() {
        txt_pcode.setText("");
        txt_pcode.setFocusable(true);
        txt_pcode.requestFocus();

        txt_pdesc.setText("");
        txt_pdesc.setFocusable(true);

        txt_pgroup.setText("");
        txt_pgroup.setFocusable(true);

        db_lblcount.setText("จำนวนรายการ 0 รายการ");

        btn_showall.setFocusable(false);

        loadcombotype();
    }

    private void loadcombotype() {
        combo1.removeAllItems();
        try {
            String sql = "select * from groupfile order by groupcode";

            stmt = dbUtility.con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                    combo1.addItem(cvth.ASCII2Unicode(rs.getString("groupCode")) + " - " + cvth.ASCII2Unicode(rs.getString("GroupName")));
                } else {
                    combo1.addItem(rs.getString("GroupCode") + " - " + rs.getString("GroupName"));
                }
                txt_pgroup.setText("");
            }
        } catch (SQLException ex) {
        }
    }

    private void showtable(String where, String code, String fix) {
        try {
            new ingredentFactory();
            clearTable();
            stmt = (Statement) dbUtility.con.createStatement();
            int count = 0;

            if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                String sql = "select PCode,PDesc,PGroup,PUnit1,psubunit,pscale,pacost,groupname "
                        + "from product "
                        + "left join groupfile on PGroup=groupcode "
                        + "where " + where + "  like '%" + cvth.Unicode2ASCII(code) + "%' "
                        + "and fix='" + fix + "' "
                        + "order by PGroup,PCode";
                ResultSet rs = stmt.executeQuery(sql);
                while (rs.next()) {
                    count++;
                    model.addRow(new Object[]{
                                cvth.ASCII2Unicode(rs.getString("PCode")),
                                cvth.ASCII2Unicode(rs.getString("PDesc")),
                                cvth.ASCII2Unicode(rs.getString("PGroup")),
                                cvth.ASCII2Unicode(rs.getString("PUnit1")),
                                cvth.ASCII2Unicode(rs.getString("psubunit")),
                                fdn.double3Fmt(rs.getDouble("pscale")),
                                fdn.double4FmtShow(rs.getDouble("pacost"))
                            });
                    new ingredentFactory(
                            cvth.ASCII2Unicode(rs.getString("PCode")),
                            cvth.ASCII2Unicode(rs.getString("PDesc")),
                            cvth.ASCII2Unicode(rs.getString("PGroup")),
                            cvth.ASCII2Unicode(rs.getString("groupname")),
                            cvth.ASCII2Unicode(rs.getString("PUnit1")),
                            cvth.ASCII2Unicode(rs.getString("psubunit")),
                            rs.getDouble("pscale"),
                            rs.getDouble("pacost"));
                }
                rs.close();
                stmt.close();
            } else {
                String sql = "select PCode,PDesc,PGroup,PUnit1,psubunit,pscale,pacost,groupname "
                        + "from product "
                        + "left join groupfile on PGroup=groupcode "
                        + "where " + where + "  like '%" + cvth.Unicode2ASCII(code) + "%' "
                        + "and fix='" + fix + "' "
                        + "order by PGroup,PCode";
                ResultSet rs = stmt.executeQuery(sql);
                while (rs.next()) {
                    count++;
                    model.addRow(new Object[]{
                                rs.getString("PCode"),
                                rs.getString("PDesc"),
                                rs.getString("PGroup"),
                                rs.getString("PUnit1"),
                                rs.getString("psubunit"),
                                fdn.double3Fmt(rs.getDouble("pscale")),
                                fdn.double4FmtShow(rs.getDouble("pacost"))
                            });
                    new ingredentFactory(
                            rs.getString("PCode"),
                            rs.getString("PDesc"),
                            rs.getString("PGroup"),
                            rs.getString("groupname"),
                            rs.getString("PUnit1"),
                            rs.getString("psubunit"),
                            rs.getDouble("pscale"),
                            rs.getDouble("pacost"));
                    rs.close();
                    stmt.close();
                }
            }
            db_lblcount.setText("จำนวนรายการ " + count + " รายการ");
            if (count > 0) {
                tbltable.setFocusable(true);
                tbltable.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            e.printStackTrace();
        }
    }

    private void btnPrint() {
        Report r = new Report();
        Map map = new HashMap();
        JRBeanCollectionDataSource ds = new JRBeanCollectionDataSource(
                ingredentFactory.createBeanCollection());

        String filename = "posbom_ingredent";
        String pcode = txt_pcode.getText().trim();
        String pdesc = txt_pdesc.getText().trim();
        String pgroup = txt_pgroup.getText().trim();
        
        if (pcode.length() <= 0) {
            pcode = "ไม่ระบุ";
        }
        if (pdesc.length() <= 0) {
            pdesc = "ไม่ระบุ";
        }
        if (pgroup.length() <= 0) {
            pgroup = "ไม่ระบุ";
        }
        map.put("pcode", pcode);
        map.put("pdesc", pdesc);
        map.put("pgroup", pgroup);

        r.viewReportbean(filename, map, "ingredent", ds);
    }
}
