/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package convertplu;

import dbutility.dbUtility;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import utilititiesfunction.* ;

/**
 *
 * @author user
 */
public class mainconvert extends javax.swing.JDialog {

    dbUtility db = new dbUtility();
    Statement stmt0;
    int totalrec = 0 ;

    /**
     * Creates new form mainconvert
     */
    public mainconvert(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ClearFrom();
    }

    public void ClearFrom() {
        PMsg.setText("");
        int cnt = 0;
        try {
            Statement stmt = (Statement) dbUtility.con.createStatement();
            String SqlQuery = "select *from product where pgroup='0088' and length(pcode)<10  ";
            ResultSet rec = stmt.executeQuery(SqlQuery);
            rec.first();
            if (rec.getRow() == 0) {
            } else {
                do {
                    cnt++;
                } while (rec.next());
            }
            rec.close();
            stmt.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        totalrec = cnt ;
        RowCnt.setText("จำนวนรายการที่จะทำการ Convert " + cnt + " รายการ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        PMsg = new javax.swing.JLabel();
        RowCnt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Convert PLU DPT 0088");

        jButton1.setFont(new java.awt.Font("Norasi", 1, 18)); // NOI18N
        jButton1.setText("ประมวลผล");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        PMsg.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        PMsg.setText("Status Message");

        RowCnt.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        RowCnt.setText("จำนวนรายการที่ทำการ Convert");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PMsg))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(RowCnt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(RowCnt)
                .addGap(37, 37, 37)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(PMsg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Thread SendData = new Thread(new ProcessSend());
        SendData.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainconvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainconvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainconvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainconvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                mainconvert dialog = new mainconvert(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private class ProcessSend extends javax.swing.JDialog implements Runnable {

        public void run() {
            int cnt = 0;
            try {
                Statement stmt = (Statement) dbUtility.con.createStatement();
                String SqlQuery = "select *from product where pgroup='0088' and length(pcode)<10  ";
                ResultSet rec = stmt.executeQuery(SqlQuery);
                rec.first();
                if (rec.getRow() == 0) {
                } else {
                    do {
                        cnt++;
                        String OldCode = rec.getString("pcode") ;
                        String NewCode = PUtility.Addzero(OldCode, 10) ;
                        
                        //AdjStock
                        PMsg.setText("Process : "+cnt+"/"+totalrec+"     "+"Adjstock");
                        stmt0 = (Statement) dbUtility.con.createStatement();
                        String Query = "update adjstock set r_pcode='"+NewCode+"' where r_pcode='"+OldCode+"' " ;
                        stmt0.executeUpdate(Query);
                        
                        //pset
                        PMsg.setText("Process : "+cnt+"/"+totalrec+"     "+"pset");
                        stmt0 = (Statement) dbUtility.con.createStatement();
                        Query = "update pset set psubcode='"+NewCode+"' where psubcode='"+OldCode+"' " ;
                        stmt0.executeUpdate(Query);
                        
                        //pingredent
                        PMsg.setText("Process : "+cnt+"/"+totalrec+"     "+"pingredent");
                        stmt0 = (Statement) dbUtility.con.createStatement();
                        Query = "update pingredent set pingcode='"+NewCode+"' where pingcode='"+OldCode+"' " ;
                        stmt0.executeUpdate(Query);
                        
                        //train
                        PMsg.setText("Process : "+cnt+"/"+totalrec+"     "+"tranin");
                        stmt0 = (Statement) dbUtility.con.createStatement();
                        Query = "update tranin set r_pcode='"+NewCode+"' where r_pcode='"+OldCode+"' " ;
                        stmt0.executeUpdate(Query);
                        
                        //traout
                        PMsg.setText("Process : "+cnt+"/"+totalrec+"     "+"tranout");
                        stmt0 = (Statement) dbUtility.con.createStatement();
                        Query = "update tranout set r_pcode='"+NewCode+"' where r_pcode='"+OldCode+"' " ;
                        stmt0.executeUpdate(Query);
                        
                        //traout
                        PMsg.setText("Process : "+cnt+"/"+totalrec+"     "+"tranout");
                        stmt0 = (Statement) dbUtility.con.createStatement();
                        Query = "update tranout set r_pcode='"+NewCode+"' where r_pcode='"+OldCode+"' " ;
                        stmt0.executeUpdate(Query);
                        
                        //blink
                        PMsg.setText("Process : "+cnt+"/"+totalrec+"     "+"blink");
                        stmt0 = (Statement) dbUtility.con.createStatement();
                        Query = "update blink set pcode='"+NewCode+"' where pcode='"+OldCode+"' " ;
                        stmt0.executeUpdate(Query);
                        
                        //dstockcake
                        PMsg.setText("Process : "+cnt+"/"+totalrec+"     "+"dstockcake");
                        stmt0 = (Statement) dbUtility.con.createStatement();
                        Query = "update dstockcake set pcode='"+NewCode+"' where pcode='"+OldCode+"' " ;
                        stmt0.executeUpdate(Query);
                        
                        //dstock
                        PMsg.setText("Process : "+cnt+"/"+totalrec+"     "+"dstock");
                        stmt0 = (Statement) dbUtility.con.createStatement();
                        Query = "update dstock set s_pcode='"+NewCode+"' where s_pcode='"+OldCode+"' " ;
                        stmt0.executeUpdate(Query);
                        
                        //dtranout
                        PMsg.setText("Process : "+cnt+"/"+totalrec+"     "+"dtranout");
                        stmt0 = (Statement) dbUtility.con.createStatement();
                        Query = "update dtranout set r_pcode='"+NewCode+"' where r_pcode='"+OldCode+"' " ;
                        stmt0.executeUpdate(Query);
                        
                        //product
                        PMsg.setText("Process : "+cnt+"/"+totalrec+"     "+"product");
                        stmt0 = (Statement) dbUtility.con.createStatement();
                        Query = "update product set pcode='"+NewCode+"',fix='L'  where pcode='"+OldCode+"' " ;
                        stmt0.executeUpdate(Query);
                        
                    } while (rec.next());
                }
                rec.close();
                stmt.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            
            JOptionPane.showMessageDialog(null, "สิ้นสุดการทำงาน....");

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PMsg;
    private javax.swing.JLabel RowCnt;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
