package EStamp;

import dbutility.dbUtility;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import utilititiesfunction.ThaiUtilities;

public class dBrows_Plu extends javax.swing.JDialog {

    private DefaultTableModel model;
    dbUtility db = new dbUtility();
    Statement stmt;
    ThaiUtilities cvth = new ThaiUtilities();
    int index = 0;
    int chk = 0;
    public String procode;
    public String proname = "";
    public String pcode = "";
    public String pname = "";
    String frmname = "dBrows_Plu";
    public String scode = "";

    public dBrows_Plu(java.awt.Frame parent, boolean modal, String scode, String procode) {
        super(parent, modal);
        initComponents();

        this.scode = scode;
        this.procode = procode;

        lbllist.setText(tbltable.getRowCount() + "");
        tbltable.setShowGrid(true);
        tbltable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tbltable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbltable.setRowSelectionAllowed(true);
        tbltable.setBackground(java.awt.Color.WHITE);
        tbltable.setGridColor(java.awt.Color.gray);

        //getLanguage lang = new getLanguage();
        //lang.setText(frmname, this, lang.getChklang());
        tbltable.setRowHeight(24);
        tbltable.setFont(new Font("Norasi", Font.PLAIN, 14));
        tbltable.setAutoCreateRowSorter(true);
        loadcombotype();
        initTable();
        showtable("pcode", "%%%");
        txtid.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        d_h4 = new javax.swing.JLabel();
        txtgroup = new javax.swing.JTextField();
        combo1 = new javax.swing.JComboBox();
        db_btnProcress = new javax.swing.JButton();
        db_btnshowall = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        mb_enter = new javax.swing.JLabel();
        d_h3 = new javax.swing.JLabel();
        d_h2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        db_h1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mb_test1 = new javax.swing.JLabel();
        mb_test = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltable = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        db_lblcount1 = new javax.swing.JLabel();
        lbllist = new javax.swing.JLabel();
        db_lblcount2 = new javax.swing.JLabel();
        btn_chkall = new javax.swing.JButton();
        btn_unchkall = new javax.swing.JButton();
        btn_ok = new javax.swing.JButton();
        btn_ok1 = new javax.swing.JButton();
        com_record = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("แสดงรายการสินค้า");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 252, 193));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d_h4.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_h4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_h4.setText("กลุ่มสินค้า");
        d_h4.setName("d_h4"); // NOI18N
        jPanel5.add(d_h4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 17, 101, -1));

        txtgroup.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtgroup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtgroupFocusGained(evt);
            }
        });
        txtgroup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtgroupKeyPressed(evt);
            }
        });
        jPanel5.add(txtgroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 14, 84, 30));

        combo1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });
        combo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                combo1KeyPressed(evt);
            }
        });
        jPanel5.add(combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 14, 350, 30));

        db_btnProcress.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_btnProcress.setText("F5-ตกลง");
        db_btnProcress.setName("db_btnProcress"); // NOI18N
        db_btnProcress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_btnProcressActionPerformed(evt);
            }
        });
        jPanel5.add(db_btnProcress, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 50, 145, -1));

        db_btnshowall.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_btnshowall.setText("F11-แสดงทั้งหมด");
        db_btnshowall.setName("db_btnshowall"); // NOI18N
        db_btnshowall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_btnshowallActionPerformed(evt);
            }
        });
        jPanel5.add(db_btnshowall, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 50, 160, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 5, 605, 90));

        jPanel3.setBackground(new java.awt.Color(213, 202, 253));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(9, 0, 91));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mb_enter.setFont(new java.awt.Font("Norasi", 1, 16)); // NOI18N
        mb_enter.setForeground(new java.awt.Color(255, 37, 37));
        mb_enter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mb_enter.setText("ใส่ข้อมูลตามช่องที่ต้องการแล้วกด Enter");
        mb_enter.setName("mb_enter"); // NOI18N
        jPanel4.add(mb_enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 370, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 110, 388, 40));

        d_h3.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_h3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_h3.setText("ชื่อสินค้า");
        d_h3.setName("d_h3"); // NOI18N
        jPanel3.add(d_h3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 72, 113, -1));

        d_h2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_h2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_h2.setText("รหัสสินค้า");
        d_h2.setName("d_h2"); // NOI18N
        jPanel3.add(d_h2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 37, 113, -1));

        txtname.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnameFocusGained(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
        });
        jPanel3.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 70, 235, 30));

        txtid.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtidFocusGained(evt);
            }
        });
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidKeyPressed(evt);
            }
        });
        jPanel3.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 35, 235, 30));

        db_h1.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_h1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        db_h1.setText("ค้นหาจากสินค้า");
        db_h1.setName("db_h1"); // NOI18N
        jPanel3.add(db_h1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 390, 150));

        jPanel2.setBackground(new java.awt.Color(194, 254, 140));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mb_test1.setFont(new java.awt.Font("Norasi", 1, 16)); // NOI18N
        mb_test1.setForeground(new java.awt.Color(255, 37, 37));
        mb_test1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mb_test1.setText("การค้นหาข้อมูล สามารถใช้ส่วนหนึ่งของคำในการค้นหาได้");
        mb_test1.setName("mb_test"); // NOI18N
        jPanel2.add(mb_test1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 390, 30));

        mb_test.setFont(new java.awt.Font("Norasi", 1, 16)); // NOI18N
        mb_test.setForeground(new java.awt.Color(255, 37, 37));
        mb_test.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mb_test.setText("เช่น \"เจ้าพระยา\" เพื่อหา\"บริษัท เจ้าพระยาคอมพิวเทค จำกัด\"");
        mb_test.setName("mb_test"); // NOI18N
        jPanel2.add(mb_test, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 27, 430, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 95, 605, 60));

        tbltable.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        tbltable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "เลือก", "กลุ่มสินค้า", "รหัสสินค้า", "ชื่อสินค้า", "ราคาขาย/หน่วย", "หน่วยนับ", "Active"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbltable.setName("tbltable"); // NOI18N
        tbltable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltableMouseClicked(evt);
            }
        });
        tbltable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbltableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbltable);
        if (tbltable.getColumnModel().getColumnCount() > 0) {
            tbltable.getColumnModel().getColumn(0).setPreferredWidth(80);
            tbltable.getColumnModel().getColumn(1).setPreferredWidth(230);
            tbltable.getColumnModel().getColumn(2).setPreferredWidth(120);
            tbltable.getColumnModel().getColumn(3).setPreferredWidth(290);
            tbltable.getColumnModel().getColumn(4).setPreferredWidth(110);
            tbltable.getColumnModel().getColumn(5).setPreferredWidth(100);
            tbltable.getColumnModel().getColumn(6).setPreferredWidth(60);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1020, 500));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        db_lblcount1.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_lblcount1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        db_lblcount1.setText("จำนวนรายการ");
        db_lblcount1.setName("db_lblcount1"); // NOI18N
        jPanel8.add(db_lblcount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 112, 40));

        lbllist.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        lbllist.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbllist.setText("0");
        jPanel8.add(lbllist, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 30, 40));

        db_lblcount2.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_lblcount2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        db_lblcount2.setText("รายการ");
        db_lblcount2.setName("db_lblcount2"); // NOI18N
        jPanel8.add(db_lblcount2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, -1, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 662, 348, 40));

        btn_chkall.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btn_chkall.setText("Check All");
        btn_chkall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chkallActionPerformed(evt);
            }
        });
        getContentPane().add(btn_chkall, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 662, 110, 40));

        btn_unchkall.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btn_unchkall.setText("UnCheck All");
        btn_unchkall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_unchkallActionPerformed(evt);
            }
        });
        getContentPane().add(btn_unchkall, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 662, 110, 40));

        btn_ok.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btn_ok.setText("ตกลง (OK)");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 662, 130, 40));

        btn_ok1.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btn_ok1.setText("ยกเลิก (Cancel)");
        btn_ok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ok1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ok1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 662, 130, 40));

        com_record.setFont(new java.awt.Font("Norasi", 0, 15)); // NOI18N
        com_record.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1000", "2000", "3000", "All" }));
        com_record.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                com_recordItemStateChanged(evt);
            }
        });
        getContentPane().add(com_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 662, 130, 40));

        setSize(new java.awt.Dimension(1022, 734));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtgroupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtgroupFocusGained
        cleartxt();
    }//GEN-LAST:event_txtgroupFocusGained

    private void txtgroupKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgroupKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            db_btnProcress.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            dispose();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F11) {
            showtable("pcode", "%%%");
            txtid.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F5) {
            btnProcress();
        }
    }//GEN-LAST:event_txtgroupKeyPressed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        combo1action();
    }//GEN-LAST:event_combo1ActionPerformed

    private void combo1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combo1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            combo1action();
        }
    }//GEN-LAST:event_combo1KeyPressed

    private void db_btnProcressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_btnProcressActionPerformed
        btnProcress();
    }//GEN-LAST:event_db_btnProcressActionPerformed

    private void db_btnshowallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_btnshowallActionPerformed
        com_record.setSelectedItem("All");
        showtable("pcode", "%%%");
        combo1.setSelectedIndex(0);
        cleartxt();
    }//GEN-LAST:event_db_btnshowallActionPerformed

    private void txtnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusGained
        cleartxt();
    }//GEN-LAST:event_txtnameFocusGained

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txtname.getText().trim().equals("")) {
                showtable("pdesc", txtname.getText());
            } else {
                txtid.requestFocus();
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            dispose();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F11) {
            showtable("pcode", "%%%");
            txtid.requestFocus();
        }
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidFocusGained
        cleartxt();
    }//GEN-LAST:event_txtidFocusGained

    private void txtidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txtid.getText().trim().equals("")) {
                showtable("pcode", txtid.getText());
            } else {
                //                txtmanager.requestFocus();
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            dispose();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F11) {
            showtable("pcode", "%%%");
            txtid.requestFocus();
        }
    }//GEN-LAST:event_txtidKeyPressed

    private void tbltableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltableMouseClicked
        index = tbltable.getSelectedRow();
        if (evt.getClickCount() == 2) {
            index = tbltable.getSelectedRow();
            if (index != -1) {
                try {
                    pcode = tbltable.getValueAt(index, 2).toString();
                    pname = tbltable.getValueAt(index, 3).toString();
                    this.dispose();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_tbltableMouseClicked

    private void tbltableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbltableKeyPressed

    }//GEN-LAST:event_tbltableKeyPressed

    private void btn_chkallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chkallActionPerformed
        int cnt = model.getRowCount();
        if (cnt > 0) {
            for (int i = 0; i < cnt; i++) {
                model.removeRow(0);
            }
        }
        try {
            String sql = "select * from product left join groupfile on pgroup=groupcode "
                    + "order by pcode";
            stmt = dbUtility.con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {

                model.addRow(new Object[]{
                    true,
                    rs.getString("pgroup") + " " + rs.getString("groupname"),
                    rs.getString("pcode"),
                    rs.getString("pdesc"),
                    rs.getDouble("pprice11"),
                    rs.getString("punit1"),
                    rs.getString("pactive")
                });

            }
            rs.close();
            stmt.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btn_chkallActionPerformed

    private void btn_unchkallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_unchkallActionPerformed
        int cnt = model.getRowCount();
        if (cnt > 0) {
            for (int i = 0; i < cnt; i++) {
                model.removeRow(0);
            }
        }
        try {
            String sql = "select * from product left join groupfile on pgroup=groupcode "
                    + "order by pcode";
            stmt = dbUtility.con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {

                model.addRow(new Object[]{
                    false,
                    cvth.ASCII2Unicode(rs.getString("pgroup") + " " + rs.getString("groupname")),
                    cvth.ASCII2Unicode(rs.getString("pcode")),
                    cvth.ASCII2Unicode(rs.getString("pdesc")),
                    rs.getDouble("pprice11"),
                    cvth.ASCII2Unicode(rs.getString("punit1")),
                    cvth.ASCII2Unicode(rs.getString("pactive"))
                });

            }
            rs.close();
            stmt.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btn_unchkallActionPerformed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        try {
            for (int i = 0; i < tbltable.getRowCount(); i++) {
                String chkbox = tbltable.getValueAt(i, 0).toString();
                if (chkbox.equalsIgnoreCase("true")) {
                    if (!chk(scode, procode, tbltable.getValueAt(i, 2).toString())) {
                        stmt = (Statement) dbUtility.con.createStatement();
                        String sql = "Insert into stamplinkplu (s_code,st_code, pcode) "
                                + " values(?,?,?)";
                        PreparedStatement prm2 = (PreparedStatement) dbUtility.con.prepareStatement(sql);
                        prm2.setString(1, scode);
                        prm2.setString(2, procode);
                        prm2.setString(3, tbltable.getValueAt(i, 2).toString());
                        prm2.executeUpdate();
                        stmt.close();
                    }
                } else {
                    stmt = (Statement) dbUtility.con.createStatement();
                    String sql2 = "Delete from stamplinkplu where pcode = ? and st_code = '" + procode + "' and s_code='" + scode + "' ";
                    PreparedStatement prm2 = (PreparedStatement) dbUtility.con.prepareStatement(sql2);
                    prm2.setString(1, tbltable.getValueAt(i, 2).toString());
                    prm2.executeUpdate();
                    stmt.close();
                }
            }
            dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_ok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ok1ActionPerformed
        dispose();
    }//GEN-LAST:event_btn_ok1ActionPerformed

    private void com_recordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_com_recordItemStateChanged
        showtable("pcode", "%%%");
    }//GEN-LAST:event_com_recordItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dBrows_Plu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dBrows_Plu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dBrows_Plu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dBrows_Plu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dBrows_Plu dialog = new dBrows_Plu(new javax.swing.JFrame(), true, "", "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chkall;
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton btn_ok1;
    private javax.swing.JButton btn_unchkall;
    private javax.swing.JComboBox com_record;
    private javax.swing.JComboBox combo1;
    private javax.swing.JLabel d_h2;
    private javax.swing.JLabel d_h3;
    private javax.swing.JLabel d_h4;
    private javax.swing.JButton db_btnProcress;
    private javax.swing.JButton db_btnshowall;
    private javax.swing.JLabel db_h1;
    private javax.swing.JLabel db_lblcount1;
    private javax.swing.JLabel db_lblcount2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbllist;
    private javax.swing.JLabel mb_enter;
    private javax.swing.JLabel mb_test;
    private javax.swing.JLabel mb_test1;
    private javax.swing.JTable tbltable;
    private javax.swing.JTextField txtgroup;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
private void initTable() {

        model = (DefaultTableModel) tbltable.getModel();
        tbltable.setRowHeight(24);
        tbltable.setFont(new Font("Norasi", Font.PLAIN, 14));
        JTableHeader tHeader = tbltable.getTableHeader();
        tHeader.setFont(new Font("Norasi", Font.BOLD, 14));
        TableColumnModel tcm = tbltable.getColumnModel();
        DefaultTableCellRenderer d;
        ((DefaultTableCellRenderer) tbltable.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);

        d = new DefaultTableCellRenderer();
        d.setHorizontalAlignment(SwingConstants.CENTER);
        tcm.getColumn(5).setCellRenderer(d);
        tcm.getColumn(6).setCellRenderer(d);

        try {
            String sql = "select * from product left join groupfile on pgroup=groupcode order by pcode";
            stmt = dbUtility.con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {

                model.addRow(new Object[]{
                    chk(scode, procode, rs.getString("pcode")),
                    cvth.ASCII2Unicode(rs.getString("pgroup") + " " + rs.getString("groupname")),
                    cvth.ASCII2Unicode(rs.getString("pcode")),
                    cvth.ASCII2Unicode(rs.getString("pdesc")),
                    rs.getDouble("pprice11"),
                    cvth.ASCII2Unicode(rs.getString("punit1")),
                    cvth.ASCII2Unicode(rs.getString("pactive"))
                });

            }
            rs.close();
            stmt.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }

    private void clearModel() {
        int size = tbltable.getRowCount();
        for (int i = 0; i < size; i++) {
            model.removeRow(0);
        }
    }

    private void showtable(String where, String code) {
        String record = com_record.getSelectedItem().toString();
        try {
            clearModel();
            stmt = (Statement) dbUtility.con.createStatement();
            int count = 0;

            String sql = "select * from product left join groupfile on pgroup=groupcode where " + where + "  like '%" + code + "%' and pactive='Y'  "
                    + "order by PCode ";

            if (!record.equals("All")) {
                sql += "limit " + record;
            }

            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                count++;

                model.addRow(new Object[]{
                    chk(scode, procode, rs.getString("pcode")),
                    cvth.ASCII2Unicode(rs.getString("pgroup") + " " + rs.getString("groupname")),
                    cvth.ASCII2Unicode(rs.getString("pcode")),
                    cvth.ASCII2Unicode(rs.getString("pdesc")),
                    rs.getDouble("pprice11"),
                    cvth.ASCII2Unicode(rs.getString("punit1")),
                    cvth.ASCII2Unicode(rs.getString("pactive"))
                });
            }
            rs.close();
            stmt.close();
            lbllist.setText(count + "");
            tbltable.requestFocus();
            cleartxt();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void loadcombotype() {
        combo1.removeAllItems();
        try {
            String sql = "select * from groupfile order by groupcode";
            stmt = dbUtility.con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                combo1.addItem(rs.getString("GroupCode") + " - " + rs.getString("GroupName"));
                txtgroup.setText("");
            }
        } catch (SQLException ex) {
        }
    }

    private void combo1action() {
        try {
            cleartxt();
            String TempStr = combo1.getSelectedItem().toString();
            String ArrayStr[] = TempStr.split(" - ");
            txtgroup.setText(ArrayStr[0]);
            db_btnProcress.requestFocus();
        } catch (Exception e) {
        }
    }

    private void cleartxt() {
        txtgroup.setText("");
        txtname.setText("");
        txtid.setText("");
    }

    private void btnProcress() {
        if (!txtgroup.getText().trim().equals("")) {
            showtable("pgroup", txtgroup.getText());
        } else {
            db_btnshowall.requestFocus();
        }
        combo1.setSelectedIndex(0);
        cleartxt();
    }

    private boolean chk(String scode, String procode, String pcode) {
        ResultSet rs;
        boolean chk = false;
        String sql;
        try {
            sql = "SELECT * FROM stamplinkplu WHERE pcode='" + pcode + "' and st_code = '" + procode + "' and s_code='" + scode + "' ";
            stmt = dbUtility.con.createStatement();
            rs = stmt.executeQuery(sql);
            if (rs.next()) {
                return chk = true;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return chk;

    }
}
