/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package reportfile;

import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import jxl.write.WriteException;
import net.sf.jasperreports.view.save.JRSingleSheetXlsSaveContributor;
import org.jdesktop.swingx.JXTree;
import reportModel.reportSumTerminalByDateModel;
import reportModel.reportSumTerminalModel;
import utilititiesfunction.*;

/**
 *
 * @author s386
 */
public class rptSumTerminalByDate extends javax.swing.JDialog {

    /**
     * Creates new form rptSumTerminalByDate
     */
    public static String date1 = "",date2 ="",dept1="",dept2="",plu1="",plu2="",branch1="",branch2="",btype1="",btype2=""
            ,barea1="",barea2="",bsize1="",bsize2="",bplan1="",bplan2="",bstore1="",bstore2="",strday=""
            ,company1="",company2="",brand1="",brand2="",bustype1="",bustype2="",code="",name="";
    private Font fontbold = new Font("Norasi", Font.BOLD, 14);
    private Font fontplain = new Font("Norasi", Font.PLAIN, 14);
    String frmName = "rptSumTerminalByDate";
    ThaiUtilities cvth = new ThaiUtilities();
    private String condition = "";
    public rptSumTerminalByDate(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inittbl();
        getLanguage lang = new getLanguage();
        lang.setText(frmName, this, lang.getChklang());
        setTxt();
    }

    public rptSumTerminalByDate() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        db_btnPrint = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lbldate = new javax.swing.JLabel();
        db_lblh1 = new javax.swing.JLabel();
        db_lblh2 = new javax.swing.JLabel();
        lblbranch = new javax.swing.JLabel();
        db_btnExpand = new javax.swing.JButton();
        db_btnExel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new org.jdesktop.swingx.JXTreeTable();
        btnExit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        db_btnPrint.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Printer-icon.png"))); // NOI18N
        db_btnPrint.setText("พิมม์");
        db_btnPrint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        db_btnPrint.setIconTextGap(0);
        db_btnPrint.setName("db_btnPrint"); // NOI18N
        db_btnPrint.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        db_btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_btnPrintActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbldate.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        lbldate.setText("-");
        lbldate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        db_lblh1.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_lblh1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        db_lblh1.setText("วันที่ (Date)");
        db_lblh1.setName("db_lblh1"); // NOI18N

        db_lblh2.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_lblh2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        db_lblh2.setText("สาขา");
        db_lblh2.setName("db_lblh2"); // NOI18N

        lblbranch.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        lblbranch.setText("-");
        lblbranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        db_btnExpand.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_btnExpand.setText("Expand On/Off");
        db_btnExpand.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        db_btnExpand.setIconTextGap(0);
        db_btnExpand.setName("db_btnExpand"); // NOI18N
        db_btnExpand.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        db_btnExpand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_btnExpandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(db_lblh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(db_lblh2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbranch, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(db_btnExpand)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(db_btnExpand)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(db_lblh1)
                            .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(db_lblh2)
                            .addComponent(lblbranch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        db_btnExel.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_btnExel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Excel-icon.png"))); // NOI18N
        db_btnExel.setText("Exel File");
        db_btnExel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        db_btnExel.setIconTextGap(0);
        db_btnExel.setName("db_btnExel"); // NOI18N
        db_btnExel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        db_btnExel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_btnExelActionPerformed(evt);
            }
        });

        tbl.setName("tbl");
        jScrollPane1.setViewportView(tbl);

        btnExit1.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btnExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LogOut-icon.png"))); // NOI18N
        btnExit1.setText("Exit");
        btnExit1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit1.setIconTextGap(0);
        btnExit1.setName("db_btnExit"); // NOI18N
        btnExit1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(db_btnExel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(db_btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(db_btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(db_btnExel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1032)/2, (screenSize.height-796)/2, 1032, 796);
    }// </editor-fold>//GEN-END:initComponents

    private void db_btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_btnPrintActionPerformed


        // TODO add your handling code here:
  }//GEN-LAST:event_db_btnPrintActionPerformed

    private void db_btnExpandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_btnExpandActionPerformed
        if (tbl.isExpanded(0)) {
            tbl.collapseAll();
        } else {
            tbl.expandAll();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_db_btnExpandActionPerformed

    private void db_btnExelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_btnExelActionPerformed
        Export2Excel test = new Export2Excel();
        JFileChooser chooser = new JFileChooser();
        setTxt();
        try {
            

            chooser.setSelectedFile(test.getDefaulepath());
            chooser.setFileFilter(new JRSingleSheetXlsSaveContributor(Locale.ENGLISH, null));
            int confirm = chooser.showSaveDialog(this);
            if (confirm == JFileChooser.APPROVE_OPTION) {
                File curFile = chooser.getSelectedFile();


                
                
                if(curFile.exists())
                {
                    int confirm2 = JOptionPane.showConfirmDialog(this, "ข้อมูลนี้มีอยู่แล้ว คุณต้องการบันทึกรายการนี้หรือไม่...?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (confirm2 == JOptionPane.NO_OPTION) {
                        test.setDefaultpath(curFile);
                        db_btnExelActionPerformed(null);
                        
                        return;

                    }
                    
                }
                
                   
                try {
                    test.setOutputFile(curFile.toString());
                    test.writeTreetableContditionNoSum(tbl, tbl.getColumnModel(), condition);
                    test.setDefaultpath(curFile);
                } catch (WriteException ex) {
                    JOptionPane.showMessageDialog(this, ex);
                }
                
                
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_db_btnExelActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rptSumTerminalByDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rptSumTerminalByDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rptSumTerminalByDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rptSumTerminalByDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                rptSumTerminalByDate dialog = new rptSumTerminalByDate(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton db_btnExel;
    private javax.swing.JButton db_btnExpand;
    private javax.swing.JButton db_btnPrint;
    private javax.swing.JLabel db_lblh1;
    private javax.swing.JLabel db_lblh2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblbranch;
    private javax.swing.JLabel lbldate;
    private org.jdesktop.swingx.JXTreeTable tbl;
    // End of variables declaration//GEN-END:variables
private void inittbl()
{
    try {
            
            
            TableColumnModel tcm = new DefaultTableColumnModel();
            
            TableColumn tc1 = new TableColumn(0,200);
            tc1.setHeaderValue("รหัส");
            TableColumn tc2 = new TableColumn(1,200);
            tc2.setHeaderValue("รายละเอียด");
            TableColumn tc3 = new TableColumn(2,100);
            tc3.setHeaderValue("TDay");
            TableColumn tc4 = new TableColumn(3,100);
            tc4.setHeaderValue("Date");
            TableColumn tc5 = new TableColumn(4,100);
            tc5.setHeaderValue("Dept_Sum");
            TableColumn tc6 = new TableColumn(5,100);
            tc6.setHeaderValue("Service");
            TableColumn tc7 = new TableColumn(6,100);
            tc7.setHeaderValue("Discount");
            TableColumn tc8 = new TableColumn(7,100);
            tc8.setHeaderValue("NetSale");
            TableColumn tc9 = new TableColumn(8,100);
            tc9.setHeaderValue("เงินสด");
            TableColumn tc10 = new TableColumn(9,100);
            tc10.setHeaderValue("บัตรเครดิต");
            TableColumn tc11 = new TableColumn(10,100);
            tc11.setHeaderValue("บัตรกำนัล");
            TableColumn tc12 = new TableColumn(11,100);
            tc12.setHeaderValue("ลูกหนี้การค้า");
            TableColumn tc13 = new TableColumn(12,100);
            tc13.setHeaderValue("ยอดขายคิดภาษา");
            TableColumn tc14 = new TableColumn(13,100);
            tc14.setHeaderValue("ยอดขายไม่คิดภาษี");
            TableColumn tc15 = new TableColumn(14,100);
            tc15.setHeaderValue("ภาษีมูลค่าเพิ่ม");
            TableColumn tc16 = new TableColumn(15,100);
            tc16.setHeaderValue("จำนวนบิล");
            TableColumn tc17 = new TableColumn(16,100);
            tc17.setHeaderValue("จำนวนลูกค้า");
            TableColumn tc18 = new TableColumn(17,100);
            tc18.setHeaderValue("ยอดการ Void");
            TableColumn tc19 = new TableColumn(18,100);
            tc19.setHeaderValue("ยกเลิกการขาย");
            TableColumn tc52 = new TableColumn(19,100);
            tc52.setHeaderValue("ค่ามัดจำ");
            TableColumn tc20 = new TableColumn(20,100);
            tc20.setHeaderValue("เฉลี่ย / บิล");
            TableColumn tc21 = new TableColumn(21,100);
            tc21.setHeaderValue("เฉลี่ย / ลูกค้า");
            TableColumn tc22 = new TableColumn(22,100);
            tc22.setHeaderValue("(E)ยอดขาย");
            TableColumn tc23 = new TableColumn(23,100);
            tc23.setHeaderValue("(E)ยอดขายสุทธิ");
            TableColumn tc24 = new TableColumn(24,100);
            tc24.setHeaderValue("(E)จำนวนบิล");
            TableColumn tc25 = new TableColumn(25,100);
            tc25.setHeaderValue("(E)จำนวนลูกค้า");
            TableColumn tc26 = new TableColumn(26,100);
            tc26.setHeaderValue("(E)เฉลี่ย / บิล");
            TableColumn tc27 = new TableColumn(27,100);
            tc27.setHeaderValue("(E)เฉลี่ย / ลูกค้า");
            TableColumn tc28 = new TableColumn(28,100);
            tc28.setHeaderValue("(T)ยอดขาย");
            TableColumn tc29 = new TableColumn(29,100);
            tc29.setHeaderValue("(T)ยอดขายสุทธิ");
            TableColumn tc30 = new TableColumn(30,100);
            tc30.setHeaderValue("(T)จำนวนบิล");
            TableColumn tc31 = new TableColumn(31,100);
            tc31.setHeaderValue("(T)จำนวนลูกค้า");
            TableColumn tc32 = new TableColumn(32,100);
            tc32.setHeaderValue("(T)เฉลี่ย / บิล");
            TableColumn tc33 = new TableColumn(33,100);
            tc33.setHeaderValue("(T)เฉลี่ย / ลูกค้า");
            TableColumn tc34 = new TableColumn(34,100);
            tc34.setHeaderValue("(D)ยอดขาย");
            TableColumn tc35 = new TableColumn(35,100);
            tc35.setHeaderValue("(D)ยอดขายสุทธิ");
            TableColumn tc36 = new TableColumn(36,100);
            tc36.setHeaderValue("(D)จำนวนบิล");
            TableColumn tc37 = new TableColumn(37,100);
            tc37.setHeaderValue("(D)จำนวนลูกค้า");
            TableColumn tc38 = new TableColumn(38,100);
            tc38.setHeaderValue("(D)เฉลี่ย / บิล");
            TableColumn tc39 = new TableColumn(39,100);
            tc39.setHeaderValue("(D)เฉลี่ย / ลูกค้า");
            TableColumn tc40 = new TableColumn(40,100);
            tc40.setHeaderValue("(P)ยอดขาย");
            TableColumn tc41 = new TableColumn(41,100);
            tc41.setHeaderValue("(P)ยอดขายสุทธิ");
            TableColumn tc42 = new TableColumn(42,100);
            tc42.setHeaderValue("(P)จำนวนบิล");
            TableColumn tc43 = new TableColumn(43,100);
            tc43.setHeaderValue("(P)จำนวนลูกค้า");
            TableColumn tc44 = new TableColumn(44,100);
            tc44.setHeaderValue("(P)เฉลี่ย / บิล");
            TableColumn tc45 = new TableColumn(45,100);
            tc45.setHeaderValue("(P)เฉลี่ย / ลูกค้า");
            TableColumn tc46 = new TableColumn(46,100);
            tc46.setHeaderValue("(W)ยอดขาย");
            TableColumn tc47 = new TableColumn(47,100);
            tc47.setHeaderValue("(w)ยอดขายสุทธิ");
            TableColumn tc48 = new TableColumn(48,100);
            tc48.setHeaderValue("(W)จำนวนบิล");
            TableColumn tc49 = new TableColumn(49,100);
            tc49.setHeaderValue("(W)จำนวนลูกค้า");
            TableColumn tc50 = new TableColumn(50,100);
            tc50.setHeaderValue("(W)เฉลี่ย / บิล");
            TableColumn tc51 = new TableColumn(51,100);
            tc51.setHeaderValue("(W)เฉลี่ย / ลูกค้า");
            
            
            
//            TableColumn tc31 = new TableColumn(30,100);
//            tc31.setHeaderValue("S_Price");
            
            tcm.addColumn(tc1);
            tcm.addColumn(tc2);
            tcm.addColumn(tc3);
            tcm.addColumn(tc4);
            tcm.addColumn(tc5);
            tcm.addColumn(tc6);
            tcm.addColumn(tc7);
            tcm.addColumn(tc8);
            tcm.addColumn(tc9);
            tcm.addColumn(tc10);
            tcm.addColumn(tc11);
            tcm.addColumn(tc12);
            tcm.addColumn(tc13);
            tcm.addColumn(tc14);
            tcm.addColumn(tc15);
            tcm.addColumn(tc16);
            tcm.addColumn(tc17);
            tcm.addColumn(tc18);
            tcm.addColumn(tc19);
            tcm.addColumn(tc52);
            tcm.addColumn(tc20);
            tcm.addColumn(tc21);
            tcm.addColumn(tc22);
            tcm.addColumn(tc23);
            tcm.addColumn(tc24);
            tcm.addColumn(tc25);
            tcm.addColumn(tc26);
            tcm.addColumn(tc27);
            tcm.addColumn(tc28);
            tcm.addColumn(tc29);
            tcm.addColumn(tc30);
            tcm.addColumn(tc31);
            tcm.addColumn(tc32);
            tcm.addColumn(tc33);
            tcm.addColumn(tc34);
            tcm.addColumn(tc35);
            tcm.addColumn(tc36);
            tcm.addColumn(tc37);
            tcm.addColumn(tc38);
            tcm.addColumn(tc39);
            tcm.addColumn(tc40);
            tcm.addColumn(tc41);
            tcm.addColumn(tc42);
            tcm.addColumn(tc43);
            tcm.addColumn(tc44);
            tcm.addColumn(tc45);
            tcm.addColumn(tc46);
            tcm.addColumn(tc47);
            tcm.addColumn(tc48);
            tcm.addColumn(tc49);
            tcm.addColumn(tc50);
            tcm.addColumn(tc51);
            
//            tcm.addColumn(tc31);
            
      
        
        tcm.getColumn(0).setCellRenderer(FormatCell.l());
        tcm.getColumn(1).setCellRenderer(FormatCell.l());
        tcm.getColumn(2).setCellRenderer(FormatCell.l());
        tcm.getColumn(3).setCellRenderer(FormatCell.l());
        tcm.getColumn(4).setCellRenderer(FormatCell.color1());
        tcm.getColumn(5).setCellRenderer(FormatCell.color1());
        tcm.getColumn(6).setCellRenderer(FormatCell.color1());
        tcm.getColumn(7).setCellRenderer(FormatCell.color1());
        tcm.getColumn(8).setCellRenderer(FormatCell.color2());
        tcm.getColumn(9).setCellRenderer(FormatCell.color2());
        tcm.getColumn(10).setCellRenderer(FormatCell.color2());
        tcm.getColumn(11).setCellRenderer(FormatCell.color2());
        tcm.getColumn(12).setCellRenderer(FormatCell.color1());
        tcm.getColumn(13).setCellRenderer(FormatCell.color1());
        tcm.getColumn(14).setCellRenderer(FormatCell.color1());
        tcm.getColumn(15).setCellRenderer(FormatCell.color2());
        tcm.getColumn(16).setCellRenderer(FormatCell.color2());
        tcm.getColumn(17).setCellRenderer(FormatCell.color2());
        tcm.getColumn(18).setCellRenderer(FormatCell.color2());
        tcm.getColumn(19).setCellRenderer(FormatCell.color2());
        tcm.getColumn(20).setCellRenderer(FormatCell.color2());
        tcm.getColumn(21).setCellRenderer(FormatCell.color2());
        tcm.getColumn(22).setCellRenderer(FormatCell.color1());
        tcm.getColumn(23).setCellRenderer(FormatCell.color1());
        tcm.getColumn(24).setCellRenderer(FormatCell.color1());
        tcm.getColumn(25).setCellRenderer(FormatCell.color1());
        tcm.getColumn(26).setCellRenderer(FormatCell.color1());
        tcm.getColumn(27).setCellRenderer(FormatCell.color1());
        tcm.getColumn(28).setCellRenderer(FormatCell.color2());
        tcm.getColumn(29).setCellRenderer(FormatCell.color2());
        tcm.getColumn(30).setCellRenderer(FormatCell.color2());
        tcm.getColumn(31).setCellRenderer(FormatCell.color2());
        tcm.getColumn(32).setCellRenderer(FormatCell.color2());
        tcm.getColumn(33).setCellRenderer(FormatCell.color2());
        tcm.getColumn(34).setCellRenderer(FormatCell.color1());
        tcm.getColumn(35).setCellRenderer(FormatCell.color1());
        tcm.getColumn(36).setCellRenderer(FormatCell.color1());
        tcm.getColumn(37).setCellRenderer(FormatCell.color1());
        tcm.getColumn(38).setCellRenderer(FormatCell.color1());
        tcm.getColumn(39).setCellRenderer(FormatCell.color1());
        tcm.getColumn(40).setCellRenderer(FormatCell.color2());
        tcm.getColumn(41).setCellRenderer(FormatCell.color2());
        tcm.getColumn(42).setCellRenderer(FormatCell.color2());
        tcm.getColumn(43).setCellRenderer(FormatCell.color2());
        tcm.getColumn(44).setCellRenderer(FormatCell.color2());
        tcm.getColumn(45).setCellRenderer(FormatCell.color2());
        tcm.getColumn(46).setCellRenderer(FormatCell.color1());
        tcm.getColumn(47).setCellRenderer(FormatCell.color1());
        tcm.getColumn(48).setCellRenderer(FormatCell.color1());
        tcm.getColumn(49).setCellRenderer(FormatCell.color1());
        tcm.getColumn(50).setCellRenderer(FormatCell.color1());
        tcm.getColumn(51).setCellRenderer(FormatCell.color1());
        
        
        
        tbl.setEditable(false);//ห้ามแก้ไขตาราง
        tbl.setShowGrid(true);
        tbl.setFont(fontplain);
        tbl.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbl.setRowSelectionAllowed(true);
        tbl.setBackground(java.awt.Color.WHITE);
        tbl.setGridColor(java.awt.Color.gray);
        tbl.setRowHeight(24);
        
            tbl.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            String d1 = "";
            String d2 = "";
            if(!date1.equals(""))
            {
            Date d = Format.dateFmtShow.parse(date1);
            d1= Format.dateFmtSql.format(d);
            }
            if(!date2.equals(""))
            {
            Date dd = Format.dateFmtShow.parse(date2);
            d2= Format.dateFmtSql.format(dd);
            }
            String sql="";
            if(dbutility.dbUtility.Char_Set.equalsIgnoreCase("utf-8"))
            {
                sql = "SELECT drj.total as total,sum(nrefund) as nre,s_bran,dayname(t_date) as tday,t_date"
                        + ",b.name as branchname,bt.btname as Btypename,ar.name as BAreaname"
                        + ",si.name as BSizename,pl.name as BPlanname,st.name as BStorename,com.name as Companyname"
                        + ",bf.brandname as Brandname,bust.busname as Bustypename"
                        + ",b.code as BranchCode,b.btype as BtypeCode,b.barea as BAreacode"
                        + ",b.bsize as BSizecode,b.bplane as BPlancode,b.bstore as BStorecode,b.companycode as Companycode"
                        + ",b.brandcode as Brandcode,b.buscode as Bustypecode"
                        + ",sum(deptsum) as deptsum,sum(service) as service,sum(dsales) as dsales,sum(cash) as cash"
                        + ",sum(misc) as misc,sum(cupon) as cupon,sum(ar) as ar,sum(salevat) as salevat"
                        + ",sum(SaleNon) as SaleNon,sum(SVat) as SVat,sum(cust) as cust,sum(pcust) as pcust"
                        + ",sum(void) as void,sum(refund) as refund"
                        + ",sum(Eatin) as Eatin,sum(EatinNet) as EatinNet,sum(NEatin) as NEatin,sum(CEatin) as CEatin"
                        + ",sum(TakeAway) as TakeAway,sum(TakeAwayNet) as TakeAwayNet,sum(NTakeAway) as NTakeAway,sum(CTakeAway) as CTakeAway"
                        + ",sum(Delivery) as Delivery,sum(DeliveryNet) as DeliveryNet,sum(NDelivery) as NDelivery,sum(CDelivery) as CDelivery"
                        + ",sum(Pinto) as Pinto,sum(PintoNet) as PintoNet,sum(NPinto) as NPinto,sum(CPinto) as CPinto"
                        + ",sum(Whole) as Whole,sum(WholeNet) as WholeNet,sum(NWhole) as NWhole,sum(CWhole) as CWhole"
                        + ",(sum(deptsum)+sum(service)-sum(dsales)) as disc,sap_site_code "
                        + "FROM dterminal d "
                        + "inner join branfile b on d.s_bran = b.code "
                        + "inner join drjfile as drj "
                        + "on drj.brcode=d.s_bran and drj.tdate = d.t_date "
                        + "left join btype bt on b.btype = bt.btcode "
                        + "left join area ar on b.barea = ar.code "
                        + "left join size si on b.bsize = si.code "
                        + "left join plane pl on b.bplane = pl.code "
                        + "left join store st on b.bstore = st.code "
                        + "left join businesstype bust on b.buscode = bust.buscode "
                        + "left join brandfile bf on b.brandcode = bf.brandcode "
                        + "left join company com on b.companycode = com.code "
                        +"where " 
                        +"d.t_date>= '"+d1+"' and d.t_date<='"+d2+"' "
                        +"and d.s_bran >= '"+branch1+"' and d.s_bran <= '"+branch2+"' "
                        +"and b.btype >= '"+btype1+"' and b.btype <= '"+btype2+"' "
                        +"and b.barea >= '"+barea1+"' and b.barea <= '"+barea2+"' "
                        +"and b.bsize >= '"+bsize1+"' and b.bsize <= '"+bsize2+"' "
                        +"and b.bplane >= '"+bplan1+"' and b.bplane <= '"+bplan2+"' "
                        +"and b.bstore >= '"+bstore1+"' and b.bstore <= '"+bstore2+"' "
                        +"and b.companycode >= '"+company1+"' and b.companycode <= '"+company2+"' "
                        +"and b.brandcode >= '"+brand1+"' and b.brandcode <= '"+brand2+"' "
                        +"and b.buscode >= '"+bustype1+"' and b.buscode <= '"+bustype2+"' "
                        +"and locate(dayofweek(d.t_date),'"+strday+"')>0 "
                       +"and drj.rjno = '53' "
                        +"group by "+code+",t_date order by "+code+",t_date";
            }
            else
            {
               sql = "SELECT drj.total as total,sum(nrefund) as nre,s_bran,dayname(t_date) as tday,t_date"
                        + ",b.name as branchname,bt.btname as Btypename,ar.name as BAreaname"
                        + ",si.name as BSizename,pl.name as BPlanname,st.name as BStorename,com.name as Companyname"
                        + ",bf.brandname as Brandname,bust.busname as Bustypename"
                        + ",b.code as BranchCode,b.btype as BtypeCode,b.barea as BAreacode"
                        + ",b.bsize as BSizecode,b.bplane as BPlancode,b.bstore as BStorecode,b.companycode as Companycode"
                        + ",b.brandcode as Brandcode,b.buscode as Bustypecode"
                        + ",sum(deptsum) as deptsum,sum(service) as service,sum(dsales) as dsales,sum(cash) as cash"
                        + ",sum(misc) as misc,sum(cupon) as cupon,sum(ar) as ar,sum(salevat) as salevat"
                        + ",sum(SaleNon) as SaleNon,sum(SVat) as SVat,sum(cust) as cust,sum(pcust) as pcust"
                        + ",sum(void) as void,sum(refund) as refund"
                        + ",sum(Eatin) as Eatin,sum(EatinNet) as EatinNet,sum(NEatin) as NEatin,sum(CEatin) as CEatin"
                        + ",sum(TakeAway) as TakeAway,sum(TakeAwayNet) as TakeAwayNet,sum(NTakeAway) as NTakeAway,sum(CTakeAway) as CTakeAway"
                        + ",sum(Delivery) as Delivery,sum(DeliveryNet) as DeliveryNet,sum(NDelivery) as NDelivery,sum(CDelivery) as CDelivery"
                        + ",sum(Pinto) as Pinto,sum(PintoNet) as PintoNet,sum(NPinto) as NPinto,sum(CPinto) as CPinto"
                        + ",sum(Whole) as Whole,sum(WholeNet) as WholeNet,sum(NWhole) as NWhole,sum(CWhole) as CWhole"
                        + ",(sum(deptsum)+sum(service)-sum(dsales)) as disc ,sap_site_code "
                        + "FROM dterminal d "
                        + "inner join branfile b on d.s_bran = b.code "
                        + "inner join drjfile as drj "
                        + "on drj.brcode=d.s_bran and drj.tdate = d.t_date "
                        + "left join btype bt on b.btype = bt.btcode "
                        + "left join area ar on b.barea = ar.code "
                        + "left join size si on b.bsize = si.code "
                        + "left join plane pl on b.bplane = pl.code "
                        + "left join store st on b.bstore = st.code "
                        + "left join businesstype bust on b.buscode = bust.buscode "
                        + "left join brandfile bf on b.brandcode = bf.brandcode "
                        + "left join company com on b.companycode = com.code "
                        +"where " 
                        +"d.t_date>= '"+d1+"' and d.t_date<='"+d2+"' "
                        +"and d.s_bran >= '"+cvth.Unicode2ASCII(branch1)+"' and d.s_bran <= '"+cvth.Unicode2ASCII(branch2)+"' "
                        +"and b.btype >= '"+cvth.Unicode2ASCII(btype1)+"' and b.btype <= '"+cvth.Unicode2ASCII(btype2)+"' "
                        +"and b.barea >= '"+cvth.Unicode2ASCII(barea1)+"' and b.barea <= '"+cvth.Unicode2ASCII(barea2)+"' "
                        +"and b.bsize >= '"+cvth.Unicode2ASCII(bsize1)+"' and b.bsize <= '"+cvth.Unicode2ASCII(bsize2)+"' "
                        +"and b.bplane >= '"+cvth.Unicode2ASCII(bplan1)+"' and b.bplane <= '"+cvth.Unicode2ASCII(bplan2)+"' "
                        +"and b.bstore >= '"+cvth.Unicode2ASCII(bstore1)+"' and b.bstore <= '"+cvth.Unicode2ASCII(bstore2)+"' "
                        +"and b.companycode >= '"+cvth.Unicode2ASCII(company1)+"' and b.companycode <= '"+cvth.Unicode2ASCII(company2)+"' "
                        +"and b.brandcode >= '"+cvth.Unicode2ASCII(brand1)+"' and b.brandcode <= '"+cvth.Unicode2ASCII(brand2)+"' "
                        +"and b.buscode >= '"+cvth.Unicode2ASCII(bustype1)+"' and b.buscode <= '"+cvth.Unicode2ASCII(bustype2)+"' "
                        +"and locate(dayofweek(d.t_date),'"+strday+"')>0 "
                       +"and drj.rjno = '53' "
                        +"group by "+code+",t_date order by "+code+",t_date";
            
            }
            reportSumTerminalByDateModel treemodel = new reportSumTerminalByDateModel(sql,code,name);
            tbl.setTreeTableModel(treemodel);
            tbl.setColumnModel(tcm);
            tbl.setRootVisible(true);
            ((JXTree)tbl.getCellRenderer(0,tbl.getHierarchicalColumn())).setFont(fontplain);
            setTxt();
            JTableHeader h = tbl.getTableHeader();
            h.setFont(fontbold);
       //     h.setReorderingAllowed(false);
            tbl.setLeafIcon(null);
            tbl.getColumnModel().removeColumn(tc3);
            //tbl.getColumnModel().removeColumn(tc4);
        } catch (ParseException ex) {
            Logger.getLogger(rptSaleOfPlu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(rptSaleOfPlu.class.getName()).log(Level.SEVERE, null, ex);
        }
}
private void setTxt()
{
    String date = "";
    String branch = "";
    String dept = "";
    String plu = "";
    if(!date1.equals(""))
    {
    date = date1+" - ";
    }
    else
    {
    date = " - ";
    }
    
    if(!date2.equals("31/12/9999"))
    {
        date += date2;
    }
    
    if(!branch1.equals(""))
    {
        branch = branch1+" - ";
    }
    else
    {
        branch = " - ";
    }
    
    if(!branch2.equals("ZZZ"))
    {
        branch += branch2;
    }
    
    if(!dept1.equals(""))
    {
        dept = dept1+" - ";
    }
    else
    {
        dept = " - ";
    }
    
    if(!dept2.equals("ZZZZ"))
    {
        dept += dept2;
    }
    
    if(!plu1.equals(""))
    {
        plu = plu1+" - ";
    }
    else
    {
        plu = " - ";
    }
    
    if(!plu2.equals("ZZZZZZZZZZZZZ"))
    {
        plu += plu2;
    }
    
    lbldate.setText(date);
    lblbranch.setText(branch);
    condition = this.getTitle()+" Date : "+date;
}
}
