/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package reportfile;

import borfunction.GetApplicationName;
import borfunction.GetUser;
import borfunction.btnFind;
import borfunction.settext;
import dbutility.dbUtility;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.*;
import jxl.write.WriteException;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.save.JRSingleSheetXlsSaveContributor;
import org.jdesktop.swingx.JXTree;
import report.Report;
import reportModel.reportShowMenuSetupModel;
import utilititiesfunction.*;

/**
 *
 * @author s386
 */
public class rptShowMenuSetup extends javax.swing.JDialog {

    /**
     * Creates new form rptShowMenuSetup
     */
    btnFind btn = new btnFind();
    dbUtility db = new dbUtility();
    java.sql.Statement stmt ;
    String frmName = "rptshowmenusetup";
    boolean chkData = true;
    ThaiUtilities cvth = new ThaiUtilities();
    DefaultTableModel dtb ;
    getLanguage lang = new getLanguage();
    private Font fontbold = new Font("Norasi", Font.BOLD, 14);
    private Font fontplain = new Font("Norasi", Font.PLAIN, 14);
    public rptShowMenuSetup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inittbl();
        lang.setText(frmName, this, lang.getChklang());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        d_ing3 = new javax.swing.JLabel();
        t_ing1 = new javax.swing.JTextField();
        btn3 = new javax.swing.JButton();
        d_ing4 = new javax.swing.JLabel();
        t_ing2 = new javax.swing.JTextField();
        btn2 = new javax.swing.JButton();
        db_btnProcress = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        t_inggroup2 = new javax.swing.JTextField();
        btn5 = new javax.swing.JButton();
        d_ing2 = new javax.swing.JLabel();
        t_inggroup1 = new javax.swing.JTextField();
        d_ing1 = new javax.swing.JLabel();
        db_btnPrint = new javax.swing.JButton();
        db_btnExel = new javax.swing.JButton();
        btnExit1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new org.jdesktop.swingx.JXTreeTable();
        db_btnExpand = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        d_ing3.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_ing3.setText("รหัสวัตถุดิบ");
        d_ing3.setName("d_ing3"); // NOI18N

        t_ing1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_ing1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_ing1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_ing1FocusLost(evt);
            }
        });
        t_ing1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_ing1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_ing1KeyTyped(evt);
            }
        });

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Windows-Magnifier-icon.png"))); // NOI18N
        btn3.setFocusable(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        d_ing4.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_ing4.setText("ถึง");
        d_ing4.setName("d_ing4"); // NOI18N

        t_ing2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_ing2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_ing2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_ing2FocusLost(evt);
            }
        });
        t_ing2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_ing2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_ing2KeyTyped(evt);
            }
        });

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Windows-Magnifier-icon.png"))); // NOI18N
        btn2.setFocusable(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        db_btnProcress.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_btnProcress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Hourglass-icon.png"))); // NOI18N
        db_btnProcress.setText("F5-ประมวลผล");
        db_btnProcress.setName("db_btnProcress"); // NOI18N
        db_btnProcress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_btnProcressActionPerformed(evt);
            }
        });

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Windows-Magnifier-icon.png"))); // NOI18N
        btn4.setFocusable(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        t_inggroup2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_inggroup2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_inggroup2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_inggroup2FocusLost(evt);
            }
        });
        t_inggroup2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_inggroup2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_inggroup2KeyTyped(evt);
            }
        });

        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Windows-Magnifier-icon.png"))); // NOI18N
        btn5.setFocusable(false);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        d_ing2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_ing2.setText("ถึง");
        d_ing2.setName("d_ing2"); // NOI18N

        t_inggroup1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_inggroup1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_inggroup1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_inggroup1FocusLost(evt);
            }
        });
        t_inggroup1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_inggroup1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_inggroup1KeyTyped(evt);
            }
        });

        d_ing1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_ing1.setText("กลุ่มวัตถุดิบ");
        d_ing1.setName("d_ing1"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(d_ing3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(d_ing1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(t_ing1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(t_inggroup1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(d_ing4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_ing2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(t_ing2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(t_inggroup2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(db_btnProcress, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(db_btnProcress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(t_inggroup1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(d_ing1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(t_inggroup2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(d_ing2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(d_ing4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t_ing2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t_ing1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(d_ing3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        db_btnPrint.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Printer-icon.png"))); // NOI18N
        db_btnPrint.setText("พิมม์");
        db_btnPrint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        db_btnPrint.setIconTextGap(0);
        db_btnPrint.setName("db_btnPrint"); // NOI18N
        db_btnPrint.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        db_btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_btnPrintActionPerformed(evt);
            }
        });

        db_btnExel.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_btnExel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Excel-icon.png"))); // NOI18N
        db_btnExel.setText("Exel File");
        db_btnExel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        db_btnExel.setIconTextGap(0);
        db_btnExel.setName("db_btnExel"); // NOI18N
        db_btnExel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        db_btnExel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_btnExelActionPerformed(evt);
            }
        });

        btnExit1.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btnExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LogOut-icon.png"))); // NOI18N
        btnExit1.setText("Exit");
        btnExit1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit1.setIconTextGap(0);
        btnExit1.setName("db_btnExit"); // NOI18N
        btnExit1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });

        tbl.setName("tbl"); // NOI18N
        jScrollPane1.setViewportView(tbl);

        db_btnExpand.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_btnExpand.setText("Expand On/Off");
        db_btnExpand.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        db_btnExpand.setIconTextGap(0);
        db_btnExpand.setName("db_btnExpand"); // NOI18N
        db_btnExpand.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        db_btnExpand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_btnExpandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(db_btnExel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(db_btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(db_btnExpand)
                        .addGap(0, 891, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(db_btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(db_btnExel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(db_btnExpand)
                .addGap(69, 69, 69))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1024)/2, (screenSize.height-768)/2, 1024, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void t_ing1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_ing1FocusGained
        t_ing1.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_ing1FocusGained

    private void t_ing1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_ing1FocusLost
        t_ing1.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_ing1FocusLost

    private void t_ing1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_ing1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_ing2.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_F1) {
            btn.btnFindIng(t_ing1);
            
        } else if (evt.getKeyCode() == KeyEvent.VK_F5) {
            Procress();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_t_ing1KeyPressed

    private void t_ing1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_ing1KeyTyped
        settext.setTextLength(evt, t_ing1, 4);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_ing1KeyTyped

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        btn.btnFindIng(t_ing1);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void t_ing2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_ing2FocusGained
        t_ing2.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_ing2FocusGained

    private void t_ing2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_ing2FocusLost
        t_ing2.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_ing2FocusLost

    private void t_ing2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_ing2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_inggroup1.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_F1) {
            btn.btnFindIng(t_ing2);
        } else if (evt.getKeyCode() == KeyEvent.VK_F5) {
            Procress();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_ing2KeyPressed

    private void t_ing2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_ing2KeyTyped
        settext.setTextLength(evt, t_ing2, 4);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_ing2KeyTyped

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        btn.btnFindIng(t_ing2);
        //btnSearchBgroupSettext(2);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void db_btnProcressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_btnProcressActionPerformed
        Procress();
    }//GEN-LAST:event_db_btnProcressActionPerformed

    private void db_btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_btnPrintActionPerformed
        Map parm = new HashMap();
        JRBeanCollectionDataSource ds = null;
        setCondition();
        ds = new JRBeanCollectionDataSource(report.databeanReportPlu.getIng(inggroup1, inggroup2, ing1, ing2));
        parm.put("companyName", lang.getTextCompanyReport());
        parm.put("Reportheader", lang.getTextReport(frmName, "texthead"));
        parm.put("branch1", t_ing1.getText());
        parm.put("branch2", t_ing2.getText());
        parm.put("forname", lang.getTextReport(frmName, "for"));
        parm.put("code", lang.getTextReport(frmName, "code"));
        parm.put("name", lang.getTextReport(frmName, "name"));
        parm.put("other2", lang.getTextReport(frmName, "other2"));
        parm.put("other3", lang.getTextReport(frmName, "other3"));
        parm.put("other4", lang.getTextReport(frmName, "other4"));
        parm.put("other5", lang.getTextReport(frmName, "other5"));
        parm.put("other6", lang.getTextReport(frmName, "other6"));
        parm.put("total", lang.getTextReport(frmName, "total"));
        parm.put("totalall", lang.getTextReport(frmName, "totalall"));
        parm.put("branchtxt", lang.getTextReport(frmName, "branchtxt"));
        parm.put("application",new GetApplicationName().getApplicationName());
        parm.put("user", new GetUser().getUser());
        parm.put("currentDate", Format.dateFmtReport.format(new java.util.Date()));
        String rptName = "rptMenuSetup";
        Report rpt = new Report();
        rpt.viewReportbean(rptName, parm,frmName, ds);
        
        

        // TODO add your handling code here:
  }//GEN-LAST:event_db_btnPrintActionPerformed

    private void db_btnExelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_btnExelActionPerformed

       Export2Excel test = new Export2Excel();
        JFileChooser chooser = new JFileChooser();
        String condition = "Group "+t_inggroup1.getText()+" - "+t_inggroup1.getText();
        try {
            

            chooser.setSelectedFile(test.getDefaulepath());
            chooser.setFileFilter(new JRSingleSheetXlsSaveContributor(Locale.ENGLISH, null));
            int confirm = chooser.showSaveDialog(this);
            if (confirm == JFileChooser.APPROVE_OPTION) {
                File curFile = chooser.getSelectedFile();


                
                
                if(curFile.exists())
                {
                    int confirm2 = JOptionPane.showConfirmDialog(this, "ข้อมูลนี้มีอยู่แล้ว คุณต้องการบันทึกรายการนี้หรือไม่...?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (confirm2 == JOptionPane.NO_OPTION) {
                        test.setDefaultpath(curFile);
                        db_btnExelActionPerformed(null);
                        
                        return;

                    }
                    
                }
                
                   
                try {
                    test.setOutputFile(curFile.toString());
                    test.writeTreetableContditionNoSum(tbl, tbl.getColumnModel(), condition);
                    test.setDefaultpath(curFile);
                } catch (WriteException ex) {
                    JOptionPane.showMessageDialog(this, ex);
                }
                
                
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_db_btnExelActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        btn.btnFindIngGroup(t_inggroup2);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void t_inggroup2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_inggroup2FocusGained
        t_inggroup2.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_inggroup2FocusGained

    private void t_inggroup2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_inggroup2FocusLost
        t_inggroup2.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_inggroup2FocusLost

    private void t_inggroup2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_inggroup2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_ing1.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_F1) {
            btn.btnFindIngGroup(t_inggroup2);
        } else if (evt.getKeyCode() == KeyEvent.VK_F5) {
            Procress();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_inggroup2KeyPressed

    private void t_inggroup2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_inggroup2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_t_inggroup2KeyTyped

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        btn.btnFindIngGroup(t_inggroup1);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    private void t_inggroup1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_inggroup1FocusGained
        t_inggroup1.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_inggroup1FocusGained

    private void t_inggroup1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_inggroup1FocusLost
        t_inggroup1.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_inggroup1FocusLost

    private void t_inggroup1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_inggroup1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_inggroup2.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_F1) {
            btn.btnFindIngGroup(t_inggroup1);
        } else if (evt.getKeyCode() == KeyEvent.VK_F5) {
            Procress();
        }        
        // TODO add your handling code here:
    }//GEN-LAST:event_t_inggroup1KeyPressed

    private void t_inggroup1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_inggroup1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_t_inggroup1KeyTyped

    private void db_btnExpandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_btnExpandActionPerformed
        if (tbl.isExpanded(0)) {
            tbl.collapseAll();
        } else {
            tbl.expandAll();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_db_btnExpandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rptShowMenuSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rptShowMenuSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rptShowMenuSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rptShowMenuSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                rptShowMenuSetup dialog = new rptShowMenuSetup(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btnExit1;
    private javax.swing.JLabel d_ing1;
    private javax.swing.JLabel d_ing2;
    private javax.swing.JLabel d_ing3;
    private javax.swing.JLabel d_ing4;
    private javax.swing.JButton db_btnExel;
    private javax.swing.JButton db_btnExpand;
    private javax.swing.JButton db_btnPrint;
    private javax.swing.JButton db_btnProcress;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t_ing1;
    private javax.swing.JTextField t_ing2;
    private javax.swing.JTextField t_inggroup1;
    private javax.swing.JTextField t_inggroup2;
    private org.jdesktop.swingx.JXTreeTable tbl;
    // End of variables declaration//GEN-END:variables

    private void Procress() {
        setTbl();
    }
    private void inittbl()
{
    try {
            
            TableColumnModel tcm = new DefaultTableColumnModel();
            
            TableColumn tc1 = new TableColumn(0,250);
            tc1.setHeaderValue("รายการ");
            TableColumn tc2 = new TableColumn(1,70);
            tc2.setHeaderValue("วัตถุดิบ");
            TableColumn tc3 = new TableColumn(2,70);
            tc3.setHeaderValue("รหัสเมนู");
            TableColumn tc4 = new TableColumn(3,200);
            tc4.setHeaderValue("ชื่อสินค้า/รายการ");
            TableColumn tc5 = new TableColumn(4,80);
            tc5.setHeaderValue("ปริมาณ/จำนวน");
            TableColumn tc6 = new TableColumn(5,80);
            tc6.setHeaderValue("หน่วยนับ");
            TableColumn tc7 = new TableColumn(6,80);
            tc7.setHeaderValue("มูลค่าทุน");
            TableColumn tc8 = new TableColumn(7,80);
            tc8.setHeaderValue("ราคาขาย");
            TableColumn tc9 = new TableColumn(8,80);
            tc9.setHeaderValue("ทุน/ราคาขาย");
            
            
            tcm.addColumn(tc1);
            tcm.addColumn(tc2);
            tcm.addColumn(tc3);
            tcm.addColumn(tc4);
            tcm.addColumn(tc5);
            tcm.addColumn(tc6);
            tcm.addColumn(tc7);
            tcm.addColumn(tc8);
            tcm.addColumn(tc9);
            
            
            
//            tcm.addColumn(tc31);
        
        tcm.getColumn(0).setCellRenderer(FormatCell.l());
        tcm.getColumn(1).setCellRenderer(FormatCell.l());
        tcm.getColumn(2).setCellRenderer(FormatCell.l());
        tcm.getColumn(3).setCellRenderer(FormatCell.l());
        tcm.getColumn(4).setCellRenderer(FormatCell.r());
        tcm.getColumn(5).setCellRenderer(FormatCell.r());
        tcm.getColumn(6).setCellRenderer(FormatCell.r());
        tcm.getColumn(7).setCellRenderer(FormatCell.r());
        tcm.getColumn(8).setCellRenderer(FormatCell.r());
        
        
        
        tbl.setEditable(false);//ห้ามแก้ไขตาราง
        tbl.setShowGrid(true);
        tbl.setFont(fontplain);
        tbl.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbl.setRowSelectionAllowed(true);
        tbl.setBackground(java.awt.Color.WHITE);
        tbl.setGridColor(java.awt.Color.gray);
        tbl.setRowHeight(20);
        
            tbl.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            
            tbl.setColumnModel(tcm);
            tbl.setRootVisible(true);
            
            JTableHeader h = tbl.getTableHeader();
            h.setFont(fontbold);
         //   h.setReorderingAllowed(false);
            tbl.setLeafIcon(null);
        } catch (Exception ex) {
            
        } 
}
    private void setTbl()
{
    try {
            
            TableColumnModel tcm = new DefaultTableColumnModel();
            
            TableColumn tc1 = new TableColumn(0,250);
            tc1.setHeaderValue("รายการ");
            TableColumn tc2 = new TableColumn(1,70);
            tc2.setHeaderValue("วัตถุดิบ");
            TableColumn tc3 = new TableColumn(2,70);
            tc3.setHeaderValue("รหัสเมนู");
            TableColumn tc4 = new TableColumn(3,200);
            tc4.setHeaderValue("ชื่อสินค้า/รายการ");
            TableColumn tc5 = new TableColumn(4,80);
            tc5.setHeaderValue("ปริมาณ/จำนวน");
            TableColumn tc6 = new TableColumn(5,80);
            tc6.setHeaderValue("หน่วยนับ");
            TableColumn tc7 = new TableColumn(6,80);
            tc7.setHeaderValue("มูลค่าทุน");
            TableColumn tc8 = new TableColumn(7,80);
            tc8.setHeaderValue("ราคาขาย");
            TableColumn tc9 = new TableColumn(8,80);
            tc9.setHeaderValue("ทุน/ราคาขาย");
            
            
            tcm.addColumn(tc1);
            tcm.addColumn(tc2);
            tcm.addColumn(tc3);
            tcm.addColumn(tc4);
            tcm.addColumn(tc5);
            tcm.addColumn(tc6);
            tcm.addColumn(tc7);
            tcm.addColumn(tc8);
            tcm.addColumn(tc9);
            
            
            
//            tcm.addColumn(tc31);
        
        tcm.getColumn(0).setCellRenderer(FormatCell.l());
        tcm.getColumn(1).setCellRenderer(FormatCell.l());
        tcm.getColumn(2).setCellRenderer(FormatCell.l());
        tcm.getColumn(3).setCellRenderer(FormatCell.l());
        tcm.getColumn(4).setCellRenderer(FormatCell.r());
        tcm.getColumn(5).setCellRenderer(FormatCell.l());
        tcm.getColumn(6).setCellRenderer(FormatCell.r());
        tcm.getColumn(7).setCellRenderer(FormatCell.r());
        tcm.getColumn(8).setCellRenderer(FormatCell.r());
        
        
        tbl.setEditable(false);//ห้ามแก้ไขตาราง
        tbl.setShowGrid(true);
        tbl.setFont(fontplain);
        tbl.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbl.setRowSelectionAllowed(true);
        tbl.setBackground(java.awt.Color.WHITE);
        tbl.setGridColor(java.awt.Color.gray);
        tbl.setRowHeight(20);
        
            tbl.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            
            setCondition();
            String sql="";
            if(!dbutility.dbUtility.Char_Set.equalsIgnoreCase("utf-8"))
            {
                sql ="select i.incode as code,i.inname as name,m.*,i.*,p.* from menusetup m inner join ingredent i on m.incode = i.incode inner join product p on m.menucode=p.pcode "
                        + "where i.ingroup>='"+cvth.ASCII2Unicode(inggroup1)+"' and i.ingroup<='"+cvth.ASCII2Unicode(inggroup2)+"' "
                        + "and i.incode>= '"+cvth.ASCII2Unicode(ing1)+"' and i.incode<='"+cvth.ASCII2Unicode(ing2)+"' order by i.incode,menucode";
            }
            else
            {
               sql ="select i.incode as code,i.inname as name,m.*,i.*,p.* from menusetup m inner join ingredent i on m.incode = i.incode inner join product p on m.menucode=p.pcode "
                        + "where i.ingroup>='"+inggroup1+"' and i.ingroup<='"+inggroup2+"' order by i.incode,menucode"
                        + "and i.incode>= '"+ing1+"' and i.incode<='"+ing2+"'";
            
            }
            reportShowMenuSetupModel treemodel = new reportShowMenuSetupModel(sql);
            tbl.setTreeTableModel(treemodel);
            tbl.setColumnModel(tcm);
            tbl.setRootVisible(true);
            ((JXTree)tbl.getCellRenderer(0,tbl.getHierarchicalColumn())).setFont(fontplain);
            
            JTableHeader h = tbl.getTableHeader();
            h.setFont(fontbold);
            h.setReorderingAllowed(false);
            tbl.setLeafIcon(null);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        } 
}
    String ing1="",ing2="",inggroup2="",inggroup1="";
    private void setCondition()
    {
        if(!t_ing1.getText().equals(""))
        {
            ing1 = t_ing1.getText();
        }
        else
        {
            ing1="";
        }
        
        if(!t_ing2.getText().equals(""))
        {
            ing2 = t_ing2.getText();
        }
        else
        {
            ing2 = "ZZZZZZ";
        }
        
        if(!t_inggroup1.getText().equals(""))
        {
            inggroup1 = t_inggroup1.getText();
        }
        else
        {
            inggroup1="";
        }
        
        if(!t_inggroup2.getText().equals(""))
        {
            inggroup2 = t_inggroup2.getText();
        }
        else
        {
            inggroup2 = "ZZZZ";
        }
        
    }
}
