/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package reportfile;

import borfunction.GetApplicationName;
import borfunction.GetUser;
import borfunction.btnFind;
import borfunction.settext;
import dbutility.dbUtility;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import jxl.write.WriteException;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.save.JRSingleSheetXlsSaveContributor;
import report.Report;
import utilititiesfunction.*;

/**
 *
 * @author s386
 */
public class rptShowPLU extends javax.swing.JDialog {

    /**
     * Creates new form rptShowPLU
     */
    btnFind btn = new btnFind();
    dbUtility db = new dbUtility();
    Statement stmt ;
    String frmName = "rptshowplu";
    boolean chkData = true;
    ThaiUtilities cvth = new ThaiUtilities();
    DefaultTableModel dtb ;
    getLanguage lang = new getLanguage();
    DecimalFormat DoubleFmt2 = new DecimalFormat("##,###,##0.0000");
    public rptShowPLU(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initTable();
        db.dbconnect();
        //lang.setText(frmName, this, lang.getChklang());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        db_btnExel = new javax.swing.JButton();
        db_btnPrint = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        d_dapt1 = new javax.swing.JLabel();
        t_dept1 = new javax.swing.JTextField();
        btn3 = new javax.swing.JButton();
        d_dapt2 = new javax.swing.JLabel();
        t_dept2 = new javax.swing.JTextField();
        btn2 = new javax.swing.JButton();
        db_btnProcress = new javax.swing.JButton();
        cboActive = new javax.swing.JComboBox();
        d_act = new javax.swing.JLabel();
        btnExit1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        db_btnExel.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_btnExel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Excel-icon.png"))); // NOI18N
        db_btnExel.setText("Exel File");
        db_btnExel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        db_btnExel.setIconTextGap(0);
        db_btnExel.setName("db_btnExel"); // NOI18N
        db_btnExel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        db_btnExel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_btnExelActionPerformed(evt);
            }
        });

        db_btnPrint.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Printer-icon.png"))); // NOI18N
        db_btnPrint.setText("พิมม์");
        db_btnPrint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        db_btnPrint.setIconTextGap(0);
        db_btnPrint.setName("db_btnPrint"); // NOI18N
        db_btnPrint.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        db_btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_btnPrintActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        d_dapt1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_dapt1.setText("DEPTสินค้า");
        d_dapt1.setName("d_dapt1"); // NOI18N

        t_dept1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_dept1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_dept1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_dept1FocusLost(evt);
            }
        });
        t_dept1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_dept1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_dept1KeyTyped(evt);
            }
        });

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Windows-Magnifier-icon.png"))); // NOI18N
        btn3.setFocusable(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        d_dapt2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_dapt2.setText("ถึง DEPT ");
        d_dapt2.setName("d_dapt2"); // NOI18N

        t_dept2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_dept2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_dept2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_dept2FocusLost(evt);
            }
        });
        t_dept2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_dept2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_dept2KeyTyped(evt);
            }
        });

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Windows-Magnifier-icon.png"))); // NOI18N
        btn2.setFocusable(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        db_btnProcress.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_btnProcress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Hourglass-icon.png"))); // NOI18N
        db_btnProcress.setText("F5-ประมวลผล");
        db_btnProcress.setName("db_btnProcress"); // NOI18N
        db_btnProcress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_btnProcressActionPerformed(evt);
            }
        });

        cboActive.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        cboActive.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Y", "N" }));
        cboActive.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboActiveKeyPressed(evt);
            }
        });

        d_act.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_act.setText("Active");
        d_act.setName("d_act"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(d_dapt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_dept1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d_dapt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_dept2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(d_act)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboActive, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(db_btnProcress)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(db_btnProcress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(d_dapt2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_dept2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_dept1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d_dapt1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboActive, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d_act, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnExit1.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btnExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LogOut-icon.png"))); // NOI18N
        btnExit1.setText("Exit");
        btnExit1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit1.setIconTextGap(0);
        btnExit1.setName("db_btnExit"); // NOI18N
        btnExit1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });

        tbl.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Group", "Active", "รหัส PLU", "BarCode", "ชื่อสินค้า", "ต้นทุนสินค้า", "ต้นทุน/ราคาขาย", "Price1", "Price2", "Price3", "Price4", "Price5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.setName("tbl"); // NOI18N
        jScrollPane1.setViewportView(tbl);
        tbl.getColumnModel().getColumn(0).setPreferredWidth(60);
        tbl.getColumnModel().getColumn(1).setPreferredWidth(50);
        tbl.getColumnModel().getColumn(2).setPreferredWidth(80);
        tbl.getColumnModel().getColumn(3).setPreferredWidth(120);
        tbl.getColumnModel().getColumn(4).setPreferredWidth(200);
        tbl.getColumnModel().getColumn(5).setPreferredWidth(80);
        tbl.getColumnModel().getColumn(6).setPreferredWidth(80);
        tbl.getColumnModel().getColumn(7).setPreferredWidth(60);
        tbl.getColumnModel().getColumn(8).setPreferredWidth(60);
        tbl.getColumnModel().getColumn(9).setPreferredWidth(60);
        tbl.getColumnModel().getColumn(10).setPreferredWidth(60);
        tbl.getColumnModel().getColumn(11).setPreferredWidth(60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(db_btnExel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(db_btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(db_btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(db_btnExel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1024)/2, (screenSize.height-768)/2, 1024, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void db_btnExelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_btnExelActionPerformed

        Export2Excel test = new Export2Excel();
        JFileChooser chooser = new JFileChooser();

        try {
            chooser.setSelectedFile(test.getDefaulepath());
            chooser.setFileFilter(new JRSingleSheetXlsSaveContributor(Locale.ENGLISH, null));
            
            int confirm = chooser.showSaveDialog(this);
            if (confirm == JFileChooser.APPROVE_OPTION) {
                File curFile = chooser.getSelectedFile();


                
                
                if(curFile.exists())
                {
                    int confirm2 = JOptionPane.showConfirmDialog(this, "ข้อมูลนี้มีอยู่แล้ว คุณต้องการบันทึกรายการนี้หรือไม่...?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (confirm2 == JOptionPane.NO_OPTION) {
                        test.setDefaultpath(curFile);
                        db_btnExelActionPerformed(null);
                        
                        return;

                    }
                    
                }
                
                test.setOutputFile(curFile.toString());
                try {
                    test.writeTreetableNoSum2(tbl, tbl.getColumnModel());
                    test.setDefaultpath(curFile);
                } catch (WriteException ex) {
                    JOptionPane.showMessageDialog(this, ex);
                    
                }
                   
                
            }

        } catch (IOException e) {
        }
    }//GEN-LAST:event_db_btnExelActionPerformed

    private void db_btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_btnPrintActionPerformed
        Map parm = new HashMap();
        JRBeanCollectionDataSource ds = null;
        
        setCondition();
        String cbo = "";
        if(cboActive.getSelectedItem().equals(" "))
        {
            cbo = "-";
        }
        else
        {
            cbo = (String) cboActive.getSelectedItem();
        }
        
        ds = new JRBeanCollectionDataSource(report.databeanReportPlu.getPLU(dept1, dept2, active1, active2));
        parm.put("companyName", lang.getTextCompanyReport());
        parm.put("Reportheader", lang.getTextReport(frmName, "texthead"));
        parm.put("branch1", t_dept1.getText());
        parm.put("branch2", t_dept2.getText());
        parm.put("forname", lang.getTextReport(frmName, "for"));
        parm.put("code", lang.getTextReport(frmName, "code"));
        parm.put("name", lang.getTextReport(frmName, "name"));
        parm.put("Active", cbo);
        parm.put("other2", lang.getTextReport(frmName, "other2"));
        parm.put("other7", lang.getTextReport(frmName, "other7"));
        parm.put("total", lang.getTextReport(frmName, "total"));
        parm.put("totalall", lang.getTextReport(frmName, "totalall"));
        parm.put("branchtxt", lang.getTextReport(frmName, "branchtxt"));
        parm.put("application",new GetApplicationName().getApplicationName());
        parm.put("user", new GetUser().getUser());
        parm.put("currentDate", Format.dateFmtReport.format(new java.util.Date()));
        String rptName = "rptPlu";
        Report rpt = new Report();
        rpt.viewReportbean(rptName, parm,frmName, ds);
        

        // TODO add your handling code here:
  }//GEN-LAST:event_db_btnPrintActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void t_dept1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_dept1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_dept2.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_F1) {
            btn.btnFindDept(t_dept1);
        }
        else if (evt.getKeyCode() == KeyEvent.VK_F5) {
                Procress();
            }

        // TODO add your handling code here:
    }//GEN-LAST:event_t_dept1KeyPressed

    private void t_dept1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_dept1KeyTyped
        settext.setTextLength(evt, t_dept1, 4);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_dept1KeyTyped

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        btn.btnFindDept(t_dept1);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void t_dept2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_dept2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cboActive.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_F1) {
            btn.btnFindDept(t_dept2);
        }
        else if (evt.getKeyCode() == KeyEvent.VK_F5) {
                Procress();
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_dept2KeyPressed

    private void t_dept2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_dept2KeyTyped
        settext.setTextLength(evt, t_dept2, 4);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_dept2KeyTyped

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        btn.btnFindDept(t_dept2);
        //btnSearchBgroupSettext(2);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void db_btnProcressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_btnProcressActionPerformed
        Procress();

    }//GEN-LAST:event_db_btnProcressActionPerformed

    private void t_dept1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_dept1FocusGained
        t_dept1.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_dept1FocusGained

    private void t_dept2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_dept2FocusGained
        t_dept2.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_dept2FocusGained

    private void cboActiveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboActiveKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F5) {
                Procress();
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_cboActiveKeyPressed

    private void t_dept1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_dept1FocusLost
        t_dept1.select(0,0);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_t_dept1FocusLost

    private void t_dept2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_dept2FocusLost
        t_dept2.select(0,0);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_dept2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rptShowPLU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rptShowPLU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rptShowPLU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rptShowPLU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                rptShowPLU dialog = new rptShowPLU(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btnExit1;
    private javax.swing.JComboBox cboActive;
    private javax.swing.JLabel d_act;
    private javax.swing.JLabel d_dapt1;
    private javax.swing.JLabel d_dapt2;
    private javax.swing.JButton db_btnExel;
    private javax.swing.JButton db_btnPrint;
    private javax.swing.JButton db_btnProcress;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t_dept1;
    private javax.swing.JTextField t_dept2;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables

    private void Procress() {
        showdata();
    }

    private void initTable() {
        
        //tblCoupon
        DefaultTableModel tblc = (DefaultTableModel) tbl.getModel();
        tbl.setShowGrid(true);
        tbl.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tbl.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbl.setRowSelectionAllowed(true);
        tbl.setBackground(java.awt.Color.WHITE);
        tbl.setGridColor(java.awt.Color.gray);
        JTableHeader headerc = tbl.getTableHeader();
        headerc.setFont(new java.awt.Font("Norasi", java.awt.Font.BOLD, 14));
        tbl.setRowHeight(25);
      

        TableColumnModel tcmc = tbl.getColumnModel();
        tcmc.getColumn(0).setCellRenderer(FormatCell.l());
        tcmc.getColumn(1).setCellRenderer(FormatCell.l());
        tcmc.getColumn(2).setCellRenderer(FormatCell.l());
        tcmc.getColumn(3).setCellRenderer(FormatCell.l());
        tcmc.getColumn(4).setCellRenderer(FormatCell.l());
        tcmc.getColumn(5).setCellRenderer(FormatCell.r());
        tcmc.getColumn(6).setCellRenderer(FormatCell.r());
        tcmc.getColumn(7).setCellRenderer(FormatCell.r());
        tcmc.getColumn(8).setCellRenderer(FormatCell.r());
        tcmc.getColumn(9).setCellRenderer(FormatCell.r());
        tcmc.getColumn(10).setCellRenderer(FormatCell.r());
        tcmc.getColumn(11).setCellRenderer(FormatCell.r());
        
        //tblBtype.setFont(new java.awt.Font("Norasi", java.awt.Font.BOLD, 14));
        tbl.setRowHeight(25);
        tbl.setAutoCreateRowSorter(true);
    }
    private void showdata()
    {
    stmt = null;
    ResultSet rs = null;
    dtb = (DefaultTableModel) tbl.getModel();
    setCondition();
    clearTbl();
    
    try {
        stmt = (Statement) dbUtility.con.createStatement();
        if(!db.Char_Set.equalsIgnoreCase("utf-8"))
        {
            
        String sql = "select * from product where pgroup >= '"+cvth.Unicode2ASCII(dept1)+"' and pgroup <= '"+cvth.Unicode2ASCII(dept2)+"'"
                + "and pactive >= '"+active1+"' and pactive <='"+active2+"' order by pactive desc";
        rs = stmt.executeQuery(sql);
        while(rs.next())
        {
            double cost = 0;
            double gp = 0;
            if(rs.getString("pabtype").equals("R"))
            {
                cost = rs.getDouble("plcost");
            }
            else
            {
                cost = rs.getDouble("pscost");
            }
            
            if(rs.getDouble("pprice11")>0)
            {
                gp = (cost/rs.getDouble("pprice11"))*100;
            }
            else
            {
                gp = 0;
            }
            
            
            
            dtb.addRow(new Object[]{cvth.ASCII2Unicode(rs.getString("pgroup")),
                                            cvth.ASCII2Unicode(rs.getString("pactive")),
                                            cvth.ASCII2Unicode(rs.getString("pcode")),
                                            cvth.ASCII2Unicode(rs.getString("pbarcode")),
                                            cvth.ASCII2Unicode(rs.getString("pdesc")),
                                            DoubleFmt2.format(cost),
                                            Format.percentFmt.format(gp),
                                            Format.doubleFmt.format(rs.getDouble("pprice11")),
                                            Format.doubleFmt.format(rs.getDouble("pprice12")),
                                            Format.doubleFmt.format(rs.getDouble("pprice13")),
                                            Format.doubleFmt.format(rs.getDouble("pprice14")),
                                            Format.doubleFmt.format(rs.getDouble("pprice15"))
                                            
                                            });
            
        }
        }
        else
        {
            String sql = "select * from product where pgroup >= '"+dept1+"' and pgroup <= '"+dept2+"'"
                + "and pactive >= '"+active1+"' and pactive <='"+active2+"' order by pactive desc";
        rs = stmt.executeQuery(sql);
        while(rs.next())
        {
            double cost = 0;
            double gp = 0;
            if(rs.getString("pabtype").equals("R"))
            {
                cost = rs.getDouble("plcost");
            }
            else
            {
                cost = rs.getDouble("pscost");
            }
            
            if(rs.getDouble("pprice11")>0)
            {
                gp = (cost/rs.getDouble("pprice11"))*100;
            }
            else
            {
                gp = 0;
            }
            
            
            
            dtb.addRow(new Object[]{rs.getString("pgroup"),
                                            rs.getString("pactive"),
                                            rs.getString("pcode"),
                                            rs.getString("pbarcode"),
                                            rs.getString("pdesc"),
                                            DoubleFmt2.format(cost),
                                            Format.percentFmt.format(gp),
                                            Format.doubleFmt.format(rs.getDouble("pprice11")),
                                            Format.doubleFmt.format(rs.getDouble("pprice12")),
                                            Format.doubleFmt.format(rs.getDouble("pprice13")),
                                            Format.doubleFmt.format(rs.getDouble("pprice14")),
                                            Format.doubleFmt.format(rs.getDouble("pprice15"))
                                            
                                            });
            
        }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    }
    
    private void clearTbl()
    {
        
    DefaultTableModel tb = (DefaultTableModel) tbl.getModel();
     int cnt = tb.getRowCount();
        if (cnt > 0) {
            for (int i = 0; i < cnt; i++) {
                tb.removeRow(0);
            }
        }
    }
    String dept1="",dept2="",active1="",active2="";
    private void setCondition()
    {
        if(!t_dept1.getText().equals(""))
        {
            dept1 = t_dept1.getText();
        }
        else
        {
            dept1="";
        }
        
        if(!t_dept2.getText().equals(""))
        {
            dept2 = t_dept2.getText();
        }
        else
        {
            dept2 = "ZZZZ";
        }
        
        if(cboActive.getSelectedItem().equals(" "))
        {
           active1 = "";
           active2 = "ZZ";
        }
        else if(cboActive.getSelectedItem().equals("Y"))
        {
            active1 = "Y";
           active2 = "Y";
        }
        else if(cboActive.getSelectedItem().equals("N"))
        {
            active1 = "N";
           active2 = "N";
        }
    }
}
