/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package reportfile;

import dbutility.dbUtility;
import frmlist.ListProduct;
import frmlist.listTempPlu;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import masterfile.NimbusFrame;
import utilititiesfunction.TableTestFormatRenderer;
import utilititiesfunction.ThaiUtilities;
import utilititiesfunction.getLanguage;

/**
 *
 * @author s386
 */

public class TempPLU extends javax.swing.JDialog {

    /**
     * Creates new form TempPLU
     */
    Statement stmt ;
    dbUtility db = new dbUtility();
    ThaiUtilities cvth = new ThaiUtilities();
    getLanguage lang = new getLanguage();
    String frmName = "setmenulist";
    DecimalFormat DoubleFmt = new DecimalFormat("##,###,##0.00");
    public TempPLU(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initable();
        db.dbconnect();
        clearDisplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        t_pcode = new javax.swing.JTextField();
        btnsearch1 = new javax.swing.JButton();
        t_pname = new javax.swing.JTextField();
        d_lblh1 = new javax.swing.JLabel();
        db_btnOK = new javax.swing.JButton();
        db_btnCancel = new javax.swing.JButton();
        d_lblh3 = new javax.swing.JLabel();
        t_no = new javax.swing.JFormattedTextField();
        t_punit = new javax.swing.JTextField();
        db_btndelete = new javax.swing.JButton();
        db_btndeleteall = new javax.swing.JButton();
        d_lblh2 = new javax.swing.JLabel();
        t_mcode = new javax.swing.JTextField();
        btnsearch2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("บันทึกรายการลำดับ PLU Code");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbl1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ลำดับที่", "รหัสสินค้า", "ชื่อสินค้า", "หน่วย", "ราคาขาย"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl1.setName("tbl1"); // NOI18N
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl1MouseReleased(evt);
            }
        });
        tbl1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        t_pcode.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_pcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_pcodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_pcodeFocusLost(evt);
            }
        });
        t_pcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_pcodeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_pcodeKeyTyped(evt);
            }
        });

        btnsearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Windows-Magnifier-icon.png"))); // NOI18N
        btnsearch1.setFocusable(false);
        btnsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearch1ActionPerformed(evt);
            }
        });

        t_pname.setBackground(new java.awt.Color(249, 252, 186));
        t_pname.setEditable(false);
        t_pname.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_pname.setFocusable(false);

        d_lblh1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_lblh1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_lblh1.setText("รหัสสินค้า");
        d_lblh1.setName("d_lblh1"); // NOI18N

        db_btnOK.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_btnOK.setText("OK");
        db_btnOK.setName("db_btnOK"); // NOI18N
        db_btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_btnOKActionPerformed(evt);
            }
        });

        db_btnCancel.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_btnCancel.setText("Cancel");
        db_btnCancel.setName("db_btnCancel"); // NOI18N
        db_btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_btnCancelActionPerformed(evt);
            }
        });

        d_lblh3.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_lblh3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_lblh3.setText("ลำดับ");
        d_lblh3.setName("d_lblh1"); // NOI18N

        t_no.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        t_no.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        t_no.setText("1");
        t_no.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        t_no.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_noFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_noFocusLost(evt);
            }
        });
        t_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_noKeyPressed(evt);
            }
        });

        t_punit.setBackground(new java.awt.Color(249, 252, 186));
        t_punit.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_punit.setFocusable(false);
        t_punit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_punitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_punitFocusLost(evt);
            }
        });
        t_punit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_punitKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_punitKeyTyped(evt);
            }
        });

        db_btndelete.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_btndelete.setText("Delete");
        db_btndelete.setName("db_btnOK"); // NOI18N
        db_btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_btndeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(d_lblh3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(t_no, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(d_lblh1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_pcode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_pname, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_punit, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(db_btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(db_btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(db_btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(d_lblh3)
                    .addComponent(t_no, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_lblh1)
                    .addComponent(t_pcode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_pname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_punit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(db_btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(db_btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(db_btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        db_btndeleteall.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_btndeleteall.setText("Delete Group");
        db_btndeleteall.setName("db_btnOK"); // NOI18N
        db_btndeleteall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_btndeleteallActionPerformed(evt);
            }
        });

        d_lblh2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_lblh2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_lblh2.setText("ชื่อกลุ่ม PLU");
        d_lblh2.setName("d_lblh1"); // NOI18N

        t_mcode.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_mcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_mcodeFocusLost(evt);
            }
        });
        t_mcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_mcodeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_mcodeKeyTyped(evt);
            }
        });

        btnsearch2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Windows-Magnifier-icon.png"))); // NOI18N
        btnsearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearch2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(d_lblh2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_mcode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221)
                        .addComponent(db_btndeleteall, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(db_btndeleteall, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(d_lblh2)
                        .addComponent(t_mcode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-673)/2, (screenSize.height-716)/2, 673, 716);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseClicked
        //indextbl = tbltable.getSelectedRow();
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl1MouseClicked

    private void tbl1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseReleased
        if (evt.getClickCount() == 2) {
            int rowSelect = tbl1.getSelectedRow();
            String nocode = tbl1.getValueAt(rowSelect, 0).toString();
            setDataTotxt(t_mcode.getText(), nocode);


        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl1MouseReleased

    private void tbl1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl1KeyReleased

        // TODO add your handling code here:
   }//GEN-LAST:event_tbl1KeyReleased

    private void db_btndeleteallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_btndeleteallActionPerformed
        deleteGroup();
        //deleteintbl3All();
        // TODO add your handling code here:
    }//GEN-LAST:event_db_btndeleteallActionPerformed

    private void t_pcodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_pcodeFocusGained
        t_pcode.setText(t_pcode.getText());
        t_pcode.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_pcodeFocusGained

    private void t_pcodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_pcodeFocusLost
        if (!t_pcode.getText().equals("")) {
            setpname(t_pcode.getText());
        }
        t_pcode.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_pcodeFocusLost

    private void t_pcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_pcodeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!t_pcode.getText().equals("")) {
                db_btnOK.requestFocus();
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_F1) {

            btnplu();
        }

    }//GEN-LAST:event_t_pcodeKeyPressed

    private void t_pcodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_pcodeKeyTyped
        if (t_pcode.getText().length() >= 13) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_pcodeKeyTyped

    private void btnsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearch1ActionPerformed
        btnplu();
        //        btnfindPLU();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearch1ActionPerformed

    private void db_btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_btnOKActionPerformed
        save();
        // TODO add your handling code here:
    }//GEN-LAST:event_db_btnOKActionPerformed

    private void db_btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_btnCancelActionPerformed
//        clearplutxt();
        clearDisplay();
        // TODO add your handling code here:
    }//GEN-LAST:event_db_btnCancelActionPerformed

    private void t_mcodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_mcodeFocusLost
        if (!t_mcode.getText().equals("")) {
            if (t_mcode.getText().length() < 20) {
                loadtbl1(t_mcode.getText());
              
            } else {
                JOptionPane.showMessageDialog(this, "ข้อมูลไม่ถูกต้อง ห้ามกรอกข้อมูลเกิน 20 ตัวอักษร");
                t_mcode.setText("");
                t_mcode.requestFocus();
                setFocus(false);
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_mcodeFocusLost

    private void t_mcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_mcodeKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!t_mcode.getText().equals("")) {

                setFocus(true);
                t_no.requestFocus();

            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            btnTempPlu();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_mcodeKeyPressed

    private void t_mcodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_mcodeKeyTyped
        if (t_pcode.getText().length() >= 13) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_mcodeKeyTyped

    private void t_noFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_noFocusGained

        t_no.setText(t_no.getText());
        t_no.selectAll();
    }//GEN-LAST:event_t_noFocusGained

    private void t_noFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_noFocusLost
        t_pcode.setText("");
        t_pname.setText("");
        setDataTotxt(t_mcode.getText(), t_no.getText());
        t_no.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_noFocusLost

    private void t_noKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_noKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            t_pcode.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_t_noKeyPressed

    private void t_punitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_punitFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_t_punitFocusGained

    private void t_punitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_punitFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_t_punitFocusLost

    private void t_punitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_punitKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_punitKeyPressed

    private void t_punitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_punitKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_t_punitKeyTyped

    private void btnsearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearch2ActionPerformed
        btnTempPlu();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearch2ActionPerformed

    private void db_btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_btndeleteActionPerformed
        delete();
        // TODO add your handling code here:
    }//GEN-LAST:event_db_btndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TempPLU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TempPLU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TempPLU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TempPLU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                TempPLU dialog = new TempPLU(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsearch1;
    private javax.swing.JButton btnsearch2;
    private javax.swing.JLabel d_lblh1;
    private javax.swing.JLabel d_lblh2;
    private javax.swing.JLabel d_lblh3;
    private javax.swing.JButton db_btnCancel;
    private javax.swing.JButton db_btnOK;
    private javax.swing.JButton db_btndelete;
    private javax.swing.JButton db_btndeleteall;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t_mcode;
    private javax.swing.JFormattedTextField t_no;
    private javax.swing.JTextField t_pcode;
    private javax.swing.JTextField t_pname;
    private javax.swing.JTextField t_punit;
    private javax.swing.JTable tbl1;
    // End of variables declaration//GEN-END:variables
    private void btnplu()
    {
        ListProduct f = new ListProduct(new NimbusFrame(), true);
    f.setVisible(true);
    if(!f.code.equals(""))
    {
        t_pcode.setText(f.code);
        setpname(t_pcode.getText());
    }
    t_pcode.requestFocus();
    }
    
    private void setpname(String code)
    {
        stmt = null;
    ResultSet rs = null;
    
   
    try {
        stmt = (Statement) dbUtility.con.createStatement();
        String sql = "";
            if(!db.Char_Set.equalsIgnoreCase("utf-8"))
            {
                
                sql = "select pdesc,punit1 from product "
                + "where pcode ='"+cvth.Unicode2ASCII(code)+"'";
                rs = stmt.executeQuery(sql);
                if(rs.next())
                {
                   t_pname.setText(cvth.ASCII2Unicode(rs.getString("pdesc")));
                   t_punit.setText(cvth.ASCII2Unicode(rs.getString("punit1")));
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "ข้อมูลไม่ถูกต้อง กรุณากรอกข้อมูลให้ถูกต้อง");
                    t_pcode.setText("");
                    t_pname.setText("");
                   t_punit.setText("");
                    t_pcode.requestFocus();
                }
            
            }
            else
            {
                 sql = "select pdesc,punit1 from product "
                + "where pcode ='"+code+"'";
                rs = stmt.executeQuery(sql);
                if(rs.next())
                {
                   t_pname.setText(rs.getString("pdesc"));
                   t_punit.setText(cvth.ASCII2Unicode(rs.getString("punit1")));
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "ข้อมูลไม่ถูกต้อง กรุณากรอกข้อมูลให้ถูกต้อง");
                    t_pcode.setText("");
                    t_pname.setText("");
                   t_punit.setText("");
                    t_pcode.requestFocus();
                }
                
            }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    }
    
    private void setDataTotxt(String code,String no)
    {
         stmt = null;
    ResultSet rs = null;
    
   
    try {
        stmt = (Statement) dbUtility.con.createStatement();
        String sql = "";
            if(!db.Char_Set.equalsIgnoreCase("utf-8"))
            {
               
                sql = "select * from "
                + "tempplu t left join product p on t.pcode = p.pcode "
                + "where plugroup ='"+cvth.Unicode2ASCII(code)+"' and pque = '"+no+"'"
                + "order by pque";
                rs = stmt.executeQuery(sql);
                if(rs.next())
                {
                    t_no.setText(cvth.ASCII2Unicode(rs.getString("pque")));
                   t_pcode.setText(cvth.ASCII2Unicode(rs.getString("p.pcode")));
                   t_pname.setText(cvth.ASCII2Unicode(rs.getString("pdesc")));
                   t_punit.setText(cvth.ASCII2Unicode(rs.getString("punit1")));
                   
                }
            
            }
            else
            {
                 
                sql = "select * from "
                + "tempplu t left join product p on t.pcode = p.pcode "
                + "where plugroup ='"+code+"' and pque = '"+no+"'"
                + "order by pque";
                rs = stmt.executeQuery(sql);
                if(rs.next())
                {
                    t_no.setText(rs.getString("pque"));
                   t_pcode.setText(rs.getString("p.pcode"));
                   t_pname.setText(rs.getString("pdesc"));
                   t_punit.setText(rs.getString("punit1"));
                   
                }
            }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    }
    
    private void setFocus(boolean chk)
    {
    
    t_no.setFocusable(chk);
    t_pcode.setFocusable(chk);
    tbl1.setEnabled(chk);
    btnsearch1.setEnabled(chk);
    db_btnOK.setEnabled(chk);
    db_btndeleteall.setEnabled(chk);
    db_btnCancel.setEnabled(chk);
    db_btndelete.setEnabled(chk);
    if(chk==false)
    {
    t_mcode.setFocusable(true);
    t_mcode.setBackground(Color.WHITE);
    
    
    }
    else
    {
    t_mcode.setBackground(new java.awt.Color(255, 246, 143));
    t_mcode.setFocusable(false);
    }
    }
    
    private void clearDisplay()
    {
        t_no.setText("");
        t_pcode.setText("");
        t_pname.setText("");
        t_mcode.setText("");
        t_punit.setText("");
        t_no.setText("1");
        setFocus(false);
        removedataintble(tbl1);
        t_mcode.requestFocus();
    }
    
    private void cleartxt()
    {
        
        t_pcode.setText("");
        t_pname.setText("");
        setFocus(true);
        t_no.requestFocus();
        t_punit.setText("");
        getTextNo();
    }
    
    private void removedataintble(JTable tbl)
{
    DefaultTableModel tb = (DefaultTableModel) tbl.getModel();
     int cnt = tb.getRowCount();
        if (cnt > 0) {
            for (int i = 0; i < cnt; i++) {
                tb.removeRow(0);
            }
        }
}
    
    private void loadtbl1(String code)
{
    stmt = null;
    ResultSet rs = null;
    
   
    removedataintble(tbl1);
    DefaultTableModel tb = (DefaultTableModel) tbl1.getModel() ;
    try {
        stmt = (Statement) dbUtility.con.createStatement();
        String sql = "";
        if(!db.Char_Set.equalsIgnoreCase("utf-8"))
            {
        sql = "select * from "
                + "tempplu t left join product p on t.pcode = p.pcode where plugroup ='"+cvth.Unicode2ASCII(code)+"' "
                + "order by pque";
            }
        else
        {
         sql = "select * from "
                + "tempplu t left join product p on t.pcode = p.pcode where plugroup ='"+code+"' "
                + "order by pque";
        }
        rs = stmt.executeQuery(sql);
        while(rs.next())
        {
            if(!db.Char_Set.equalsIgnoreCase("utf-8"))
            {
                
            tb.addRow(new Object[]{rs.getInt("pque"),
                                   cvth.ASCII2Unicode(rs.getString("t.pcode")),
                                   cvth.ASCII2Unicode(rs.getString("pdesc")),
                                   cvth.ASCII2Unicode(rs.getString("punit1")),
                                   cvth.ASCII2Unicode(rs.getString("pprice11"))
                                  });
            }
            else
            {
             tb.addRow(new Object[]{rs.getInt("pque"),
                                   rs.getString("t.pcode"),
                                   rs.getString("pdesc"),
                                  rs.getString("punit1"),
                                  rs.getString("pprice11")
                                  });
            }
            
        }
        
        getTextNo();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
}
    
     private void initable() {
        DefaultTableModel tb = (DefaultTableModel) tbl1.getModel();
        tbl1.setShowGrid(true);
        //tblPLU.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tbl1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbl1.setRowSelectionAllowed(true);
        tbl1.setBackground(java.awt.Color.WHITE);
        tbl1.setGridColor(java.awt.Color.gray);
        JTableHeader header = tbl1.getTableHeader();
        header.setFont(new java.awt.Font("Norasi", java.awt.Font.BOLD, 14));
        //tblBtype.setFont(new java.awt.Font("Norasi", java.awt.Font.BOLD, 14));
        tbl1.setRowHeight(24);
        TableTestFormatRenderer t;
        t = new TableTestFormatRenderer(DoubleFmt);
        t.setHorizontalAlignment(SwingConstants.RIGHT);


        DefaultTableCellRenderer r;
        r = new DefaultTableCellRenderer();
        r.setHorizontalAlignment(SwingConstants.RIGHT);
        DefaultTableCellRenderer c;
        c = new DefaultTableCellRenderer();
        c.setHorizontalAlignment(SwingConstants.CENTER);
        DefaultTableCellRenderer l;
        l = new DefaultTableCellRenderer();
        l.setHorizontalAlignment(SwingConstants.LEFT);

        TableColumnModel tcm = tbl1.getColumnModel();
        tcm.getColumn(0).setCellRenderer(l);
        tcm.getColumn(1).setCellRenderer(l);
        tcm.getColumn(2).setCellRenderer(l);
        tcm.getColumn(3).setCellRenderer(l);
        tcm.getColumn(4).setCellRenderer(r);

    }
     private void getTextNo()
    {
            int no = 1;
            if(tbl1.getRowCount()>0)
            {
                no = Integer.parseInt(tbl1.getValueAt(tbl1.getRowCount()-1, 0).toString());
                no ++;
                
            }
            else
            {
                no = 1;
            }
            t_no.setText(no+"");
    }
     
     
     private void save()
    {
         try {
             
            if (!db.Char_Set.equalsIgnoreCase("utf-8")) {
                
            if(CheckValidSave())
            {
            if(chkMenu(t_mcode.getText(), t_no.getText()))
            {
               
                    //update
                    String sql2 = "Update tempplu Set pcode = ? where plugroup = ? and pque = ?";
                            
                   PreparedStatement prm = (PreparedStatement) db.con.prepareStatement(sql2);
                  
                   prm.setString(1, cvth.Unicode2ASCII(t_pcode.getText()));
                   prm.setString(2, cvth.Unicode2ASCII(t_mcode.getText()));
                   prm.setString(3, cvth.Unicode2ASCII(t_no.getText()));
                   prm.executeUpdate();
                   prm.close();
            }
            else
            {
                //insert
                
                String sql2 = "Insert Into tempplu (pcode ,plugroup ,pque )"
                        + "values(?,?,?)";
                        PreparedStatement prm = (PreparedStatement) db.con.prepareStatement(sql2);
                   prm.setString(1, cvth.Unicode2ASCII(t_pcode.getText()));
                   prm.setString(2, cvth.Unicode2ASCII(t_mcode.getText()));
                   prm.setString(3, cvth.Unicode2ASCII(t_no.getText()));
                   prm.executeUpdate();
                   prm.close();
            }
            loadtbl1(t_mcode.getText());
            cleartxt();
            
            }
            }
            else
            {
            
            }
            
            
            
        
         } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex);
                }
    }
     
     public boolean CheckValidSave() {
        boolean chk = true;


        if (t_mcode.getText().length() > 20) {
            JOptionPane.showMessageDialog(this, "กำหนดข้อมูลไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 20 ตัวอักษร)");
            chk = false;
            t_mcode.requestFocus();
        } else if (t_pcode.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "กรุณากำหนด PLU");
            chk = false;
            t_pcode.requestFocus();
        } else if (t_no.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "กรุณากำหนดลำดับ");
            chk = false;
            t_no.requestFocus();
        }
        else if(!chkplu(t_pcode.getText()))
        {
            JOptionPane.showMessageDialog(this, "ข้อมูลไม่ถูกต้อง กรุณากรอกข้อมูลให้ถูกต้อง");
                    t_pcode.setText("");
                    t_pname.setText("");
                   t_punit.setText("");
                    t_pcode.requestFocus();
                    chk = false;
        }
        else if(chkAll(t_mcode.getText(),t_pcode.getText()))
        {
            JOptionPane.showMessageDialog(this, "ไม่สามารถกรอกข้อมูลได้เนื่องจากมีรายการ(PLU Code) อยู่ในกลุ่มนี้แล้ว");
                    t_pcode.setText("");
                    t_pname.setText("");
                   t_punit.setText("");
                    t_pcode.requestFocus();
                    chk = false;
        }
        
        
        int no = Integer.parseInt(t_no.getText());
        if(no < 0 || no >999)
        {
            JOptionPane.showMessageDialog(this, "กำหนดข้อมูลไม่ถูกต้อง... (ลำดับห้ามน้อยกว่า 0 และมากกว่า 999)");
            chk = false;
            t_no.requestFocus();
        }
        return chk;
    }
     
     private boolean chkplu(String code)
    {
        stmt = null;
    ResultSet rs = null;
    boolean chk = false;
   
    try {
        stmt = (Statement) dbUtility.con.createStatement();
        String sql = "";
            if(!db.Char_Set.equalsIgnoreCase("utf-8"))
            {
                
                sql = "select pdesc,pprice11 from product "
                + "where pcode ='"+cvth.Unicode2ASCII(code)+"'";
                rs = stmt.executeQuery(sql);
                if(rs.next())
                {
                   chk = true;
                }
               
            
            }
            else
            {
                 sql = "select pdesc,pprice11 from product "
                + "where pcode ='"+code+"'";
                rs = stmt.executeQuery(sql);
                if(rs.next())
                {
                   chk = true;
                }
                
            }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    return chk;
    }
     
     private boolean chkMenu(String code, String no) {
        boolean chk = false;
        stmt = null;
        ResultSet rs = null;


        try {
            if (!db.Char_Set.equalsIgnoreCase("utf-8")) {
                stmt = (Statement) dbUtility.con.createStatement();
                String sql = "select * from tempplu "
                        + "where plugroup = '" + cvth.Unicode2ASCII(code) + "' and pque = '" + cvth.Unicode2ASCII(no) + "'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    chk = true;
                }
            } else {
                stmt = (Statement) dbUtility.con.createStatement();
                String sql = "select * from tempplu "
                        + "where plugroup = '" + code + "' and pque = '" + no + "'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    chk = true;
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return chk;
    }
     private boolean chkgroup(String code) {
        boolean chk = false;
        stmt = null;
        ResultSet rs = null;


        try {
            if (!db.Char_Set.equalsIgnoreCase("utf-8")) {
                stmt = (Statement) dbUtility.con.createStatement();
                String sql = "select * from tempplu "
                        + "where plugroup = '" + cvth.Unicode2ASCII(code) + "'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    chk = true;
                }
            } else {
                stmt = (Statement) dbUtility.con.createStatement();
                String sql = "select * from tempplu "
                        + "where plugroup = '" + code + "'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    chk = true;
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return chk;
    }
     
     private boolean chkAll(String code, String pcode) {
        boolean chk = false;
        stmt = null;
        ResultSet rs = null;


        try {
            if (!db.Char_Set.equalsIgnoreCase("utf-8")) {
                stmt = (Statement) dbUtility.con.createStatement();
                String sql = "select * from tempplu "
                        + "where plugroup = '" + cvth.Unicode2ASCII(code) + "' and pcode = '" + cvth.Unicode2ASCII(pcode) + "'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    chk = true;
                }
            } else {
                stmt = (Statement) dbUtility.con.createStatement();
                String sql = "select * from tempplu "
                        + "where plugroup = '" +"' and pcode = '" + pcode + "'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    chk = true;
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return chk;
    }
     
     public void deleteGroup()
    {
        ResultSet rs = null;
        try {
            
                String mcode = t_mcode.getText();
                if (chkgroup(mcode)) {
                    int confirm = JOptionPane.showConfirmDialog(this, "คุณต้องการลบข้อมูลรายการนี้หรือไม่...?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (confirm == JOptionPane.YES_OPTION) {
                        if (!db.Char_Set.equalsIgnoreCase("utf-8")) {
                            stmt = (Statement) db.con.createStatement();
                            String sql = "Delete from tempplu where plugroup=?";
                            java.sql.PreparedStatement prm = (java.sql.PreparedStatement) db.con.prepareStatement(sql);
                            prm.setString(1, cvth.Unicode2ASCII(mcode));
                            prm.executeUpdate();
                        } else {
                            stmt = (Statement) db.con.createStatement();
                             String sql = "Delete from tempplu where plugroup=?";
                            java.sql.PreparedStatement prm = (java.sql.PreparedStatement) db.con.prepareStatement(sql);
                            prm.setString(1, mcode);
                            prm.executeUpdate();
                        }
                        loadtbl1(mcode);
                        clearDisplay();
                    }

                }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
     
     public void delete()
    {
        ResultSet rs = null;
        try {
            
                String mcode = t_mcode.getText();
                String no = t_no.getText();
                if (chkMenu(mcode,no)) {
                    int confirm = JOptionPane.showConfirmDialog(this, "คุณต้องการลบข้อมูลรายการนี้หรือไม่...?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (confirm == JOptionPane.YES_OPTION) {
                        if (!db.Char_Set.equalsIgnoreCase("utf-8")) {
                            stmt = (Statement) db.con.createStatement();
                            String sql = "Delete from tempplu where plugroup=? and pque = ?";
                            java.sql.PreparedStatement prm = (java.sql.PreparedStatement) db.con.prepareStatement(sql);
                            prm.setString(1, cvth.Unicode2ASCII(mcode));
                            prm.setString(2, cvth.Unicode2ASCII(no));
                            prm.executeUpdate();
                        } else {
                            stmt = (Statement) db.con.createStatement();
                             String sql = "Delete from tempplu where plugroup=? and pque = ?";
                            java.sql.PreparedStatement prm = (java.sql.PreparedStatement) db.con.prepareStatement(sql);
                            prm.setString(1, mcode);
                            prm.setString(2, no);
                            prm.executeUpdate();
                        }
                        loadtbl1(mcode);
                        cleartxt();
                    }

                }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void btnTempPlu() {
        listTempPlu f = new listTempPlu(new NimbusFrame(), true);
        f.setVisible(true);
        if(!f.bcode.equals(""))
        {
            t_mcode.setText(f.bcode);
            loadtbl1(t_mcode.getText());
        }
        setFocus(true);
        t_no.requestFocus();
    }
}
