/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VenderList.java
 *
 * Created on Jun 9, 2012, 9:28:34 PM
 */
package frmlist;


import Entity.BranchCodeName;
import dbutility.dbUtility;
import java.awt.Font;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import utilititiesfunction.ThaiUtilities;

/**
 *
 * @author natee
 */
public class BrowserBankFile extends javax.swing.JDialog {

    dbUtility db = new dbUtility();
    private DefaultTableModel model;
    public BranchCodeName dataRecord;
    public String code;
    public String name;
    private Statement stmt;
    DefaultTableModel tbl_model;
    ThaiUtilities cvth = new ThaiUtilities();

    /** Creates new form VenderList */
    public BrowserBankFile(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        db.dbconnect();
        try {
            stmt = (Statement) dbUtility.con.createStatement();
        } catch (Exception e) {
        }

        initTable();
        tbl_model = (DefaultTableModel) tblList.getModel();
        tblList.setShowGrid(true);
        tblList.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblList.setRowSelectionAllowed(true);
        tblList.setBackground(java.awt.Color.WHITE);
        tblList.setGridColor(java.awt.Color.gray);
        JTableHeader header = tblList.getTableHeader();
        header.setFont(new java.awt.Font("Norasi", java.awt.Font.PLAIN, 14));
        tblList.setFont(new java.awt.Font("Norasi", java.awt.Font.PLAIN, 14));
        tblList.setRowHeight(25);

        DefaultTableCellRenderer c = new DefaultTableCellRenderer();
        c.setHorizontalAlignment(SwingConstants.CENTER);
        DefaultTableCellRenderer l = new DefaultTableCellRenderer();
        l.setHorizontalAlignment(SwingConstants.LEFT);
        DefaultTableCellRenderer r = new DefaultTableCellRenderer();
        r.setHorizontalAlignment(SwingConstants.RIGHT);



        TableColumnModel tcm = tblList.getColumnModel();
        tcm.getColumn(0).setCellRenderer(l);
        tcm.getColumn(1).setCellRenderer(l);
    }
    public BrowserBankFile(java.awt.Frame parent, boolean modal, Point point) {
        this(parent,modal);
        this.setLocation(point);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "รหัสธนาคาร", "ชื่อเจ้าของ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListMouseClicked(evt);
            }
        });
        tblList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblListKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblList);
        tblList.getColumnModel().getColumn(0).setPreferredWidth(120);
        tblList.getColumnModel().getColumn(1).setPreferredWidth(300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );

        setBounds(250, 190, 408, 374);
    }// </editor-fold>//GEN-END:initComponents

    private void tblListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListMouseClicked

        if (evt.getClickCount() == 2) {
            int index = tblList.getSelectedRow();

            try {
                dataRecord = getRecordAt((String) tblList.getValueAt(index, 0));
                code = dataRecord.getCode();
                name = dataRecord.getName();
                dispose();

            } catch (Exception ex) {
            }
        }
    }//GEN-LAST:event_tblListMouseClicked

    private void tblListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblListKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int index = tblList.getSelectedRow();

            try {
                dataRecord = getRecordAt((String) tblList.getValueAt(index, 0));
                code = dataRecord.getCode();
                name = dataRecord.getName();
                dispose();

            } catch (Exception e) {
            }
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblListKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrowserBankFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrowserBankFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrowserBankFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrowserBankFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                BrowserBankFile dialog = new BrowserBankFile(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblList;
    // End of variables declaration//GEN-END:variables
    private void initTable() {

        model = (DefaultTableModel) tblList.getModel();
        tblList.setRowHeight(24);
        tblList.setFont(new Font("Norasi", Font.PLAIN, 14));
        JTableHeader tHeader = tblList.getTableHeader();
        tHeader.setFont(new Font("Norasi", Font.BOLD, 14));

        DefaultTableCellRenderer d = new DefaultTableCellRenderer();
        d.setHorizontalAlignment(SwingConstants.CENTER);

        TableColumnModel tcm = tblList.getColumnModel();
        tcm.getColumn(0).setCellRenderer(d);
        tcm.getColumn(1).setCellRenderer(d);
        try {
            String sql = "select BCode,BName "
                    + "from bankfile";
            stmt = dbUtility.con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                    model.addRow(new Object[]{
                                cvth.ASCII2Unicode(rs.getString("BCode")),
                                cvth.ASCII2Unicode(rs.getString("BName")),});
                } else {
                    model.addRow(new Object[]{
                                rs.getString("BCode"),
                                rs.getString("BName"),});
                }
            }
            rs.close();
            stmt.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    public BranchCodeName getDataRecord() {
        return dataRecord;
    }

    public BranchCodeName getRecordAt(String GroupCode) {
        ResultSet rs;
        String sql;
        BranchCodeName fb = new BranchCodeName();

        try {
            sql = "SELECT * FROM bankfile where BCode='" + GroupCode + "'";
            stmt = dbUtility.con.createStatement();
            rs = stmt.executeQuery(sql);
            if (rs != null) {

                while (rs.next()) {
                    if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                        fb.setCode(cvth.ASCII2Unicode(rs.getString("BCode")));
                        fb.setName(cvth.ASCII2Unicode(rs.getString("BName")));
                    } else {
                        fb.setCode(rs.getString("BCode"));
                        fb.setName(rs.getString("BName"));
                    }

                }
                return fb;

            } else {
                return null;
            }
        } catch (SQLException ex) {
            return null;
        }
    }
}
