/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package frmlist;

import dbutility.dbUtility;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import utilititiesfunction.ThaiUtilities;
import utilititiesfunction.getLanguage;

/**
 *
 * @author s386
 */
public class ListVender extends javax.swing.JDialog {

    /**
     * Creates new form ListVender
     */
    private DefaultTableModel model;
    dbUtility db = new dbUtility();
    Statement stmt;
    ThaiUtilities cvth = new ThaiUtilities();
    int index = 0;
    int chk = 0;
    public String code="";
    public String name="";
    String frmname="listvender";
    public ListVender(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        db.dbconnect();

        lbllist.setText(tbltable.getRowCount()+"");
        tbltable.setShowGrid(true);
        tbltable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tbltable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbltable.setRowSelectionAllowed(true);
        tbltable.setBackground(java.awt.Color.WHITE);
        tbltable.setGridColor(java.awt.Color.gray);

        getLanguage lang = new getLanguage();
        lang.setText(frmname, this, lang.getChklang());
        tbltable.setRowHeight(24);
        tbltable.setFont(new Font("Norasi", Font.PLAIN, 14));
        tbltable.setAutoCreateRowSorter(true);
        initTable();
        showtable("vcode", "%%%");
        txtid.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbltable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        mb_test = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        mb_enter = new javax.swing.JLabel();
        d_h3 = new javax.swing.JLabel();
        d_h2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        db_h1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        db_btnshowall = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        db_lblcount1 = new javax.swing.JLabel();
        lbllist = new javax.swing.JLabel();
        db_lblcount2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbltable.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        tbltable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "รหัสผู้จัดจำหน่าย", "ชื่อผู้จัดจำหน่าย", "เบอร์โทรศัพท์", "เบอร์โทรสาร", "ชื่อผู้ติดต่อ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbltable.setName("tbltable");
        tbltable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltableMouseClicked(evt);
            }
        });
        tbltable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbltableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbltable);
        tbltable.getColumnModel().getColumn(0).setPreferredWidth(100);
        tbltable.getColumnModel().getColumn(1).setPreferredWidth(300);
        tbltable.getColumnModel().getColumn(2).setPreferredWidth(200);
        tbltable.getColumnModel().getColumn(3).setPreferredWidth(200);
        tbltable.getColumnModel().getColumn(4).setPreferredWidth(200);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(194, 254, 140));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mb_test.setFont(new java.awt.Font("Norasi", 1, 16)); // NOI18N
        mb_test.setForeground(new java.awt.Color(255, 37, 37));
        mb_test.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mb_test.setText("การค้นหาข้อมูล สามารถใช้ส่วนหนึ่งของคำในการค้นหาได้เช่น \"เจ้าพระยา\"เพื่อหา\"บริษัท เจ้าพระยาคอมพิวเทค จำกัด\"");
        mb_test.setName("mb_test");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(mb_test, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mb_test, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(213, 202, 253));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBackground(new java.awt.Color(9, 0, 91));

        mb_enter.setFont(new java.awt.Font("Norasi", 1, 16)); // NOI18N
        mb_enter.setForeground(new java.awt.Color(255, 37, 37));
        mb_enter.setText("ใส่ข้อมูลตามช่องที่ต้องการแล้วกด Enter");
        mb_enter.setName("mb_enter");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mb_enter)
                .addGap(92, 92, 92))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(mb_enter)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        d_h3.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_h3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_h3.setText("ชื่อผู้จัดจำหน่าย");
        d_h3.setName("d_h3");

        d_h2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_h2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_h2.setText("รหัสผู้จัดจำหน่าย");
        d_h2.setName("d_h2");

        txtname.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnameFocusGained(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
        });

        txtid.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtidFocusGained(evt);
            }
        });
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidKeyPressed(evt);
            }
        });

        db_h1.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_h1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        db_h1.setText("ค้นหาจากผู้จัดจำหน่าย");
        db_h1.setName("db_h1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(d_h2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(d_h3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtid)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(db_h1)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(db_h1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_h2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d_h3)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 252, 193));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        db_btnshowall.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_btnshowall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Trash-icon.png"))); // NOI18N
        db_btnshowall.setText("F11-แสดงทั้งหมด");
        db_btnshowall.setName("db_btnshowall");
        db_btnshowall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_btnshowallActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        db_lblcount1.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_lblcount1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        db_lblcount1.setText("จำนวนรายการ");
        db_lblcount1.setName("db_lblcount1");

        lbllist.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        lbllist.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbllist.setText("0");

        db_lblcount2.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_lblcount2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        db_lblcount2.setText("รายการ");
        db_lblcount2.setName("db_lblcount2");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(db_lblcount1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbllist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(db_lblcount2)
                .addGap(90, 90, 90))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbllist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(db_lblcount2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(db_lblcount1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(db_btnshowall, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(db_btnshowall)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1032)/2, (screenSize.height-796)/2, 1032, 796);
    }// </editor-fold>//GEN-END:initComponents

    private void tbltableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltableMouseClicked

        index = tbltable.getSelectedRow();
        if (evt.getClickCount() == 2) {
            index = tbltable.getSelectedRow();
            if (index != -1) {

                try {

                    code = tbltable.getValueAt(index, 0).toString();
                    name = tbltable.getValueAt(index, 1).toString();
                    this.dispose();

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tbltableMouseClicked

    private void tbltableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbltableKeyPressed

        index = tbltable.getSelectedRow();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            index = tbltable.getSelectedRow();
            if (index != -1) {
                try {
                    code = tbltable.getValueAt(index, 0).toString();
                    name = tbltable.getValueAt(index, 1).toString();
                    this.dispose();
                } catch (Exception e) {
                }
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            txtname.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tbltableKeyPressed

    private void txtnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusGained
        cleartxt();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameFocusGained

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txtname.getText().trim().equals("")) {
                showtable("vname", txtname.getText());
            } else {
                txtid.requestFocus();
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            dispose();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F11) {
            showtable("vcode", "%%%");
            txtid.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidFocusGained
        cleartxt();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidFocusGained

    private void txtidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txtid.getText().trim().equals("")) {
                showtable("vcode", txtid.getText());
            } else {
//                txtmanager.requestFocus();
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            dispose();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F11) {
            showtable("vcode", "%%%");
            txtid.requestFocus();
        }
    }//GEN-LAST:event_txtidKeyPressed

    private void db_btnshowallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_btnshowallActionPerformed
        showtable("vcode", "%%%");
        
        cleartxt();
        // TODO add your handling code here:
    }//GEN-LAST:event_db_btnshowallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ListVender dialog = new ListVender(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel d_h2;
    private javax.swing.JLabel d_h3;
    private javax.swing.JButton db_btnshowall;
    private javax.swing.JLabel db_h1;
    private javax.swing.JLabel db_lblcount1;
    private javax.swing.JLabel db_lblcount2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbllist;
    private javax.swing.JLabel mb_enter;
    private javax.swing.JLabel mb_test;
    private javax.swing.JTable tbltable;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
private void initTable() {

        model = (DefaultTableModel) tbltable.getModel();
        tbltable.setRowHeight(24);
        tbltable.setFont(new Font("Norasi", Font.PLAIN, 14));
        JTableHeader tHeader = tbltable.getTableHeader();
        tHeader.setFont(new Font("Norasi", Font.BOLD, 14));
        DefaultTableCellRenderer l = new DefaultTableCellRenderer();
        l.setHorizontalAlignment(SwingConstants.LEFT);
        DefaultTableCellRenderer c = new DefaultTableCellRenderer();
        c.setHorizontalAlignment(SwingConstants.CENTER);
        TableColumnModel tcm = tbltable.getColumnModel();
//        tcm.getColumn(0).setCellRenderer(l);
//        tcm.getColumn(1).setCellRenderer(l);
//        tcm.getColumn(2).setCellRenderer(l);
//        tcm.getColumn(3).setCellRenderer(l);
//        tcm.getColumn(4).setCellRenderer(l);
//        tcm.getColumn(5).setCellRenderer(l);
//        tcm.getColumn(6).setCellRenderer(l);
//        tcm.getColumn(7).setCellRenderer(l);
//        tcm.getColumn(8).setCellRenderer(l);
//        tcm.getColumn(9).setCellRenderer(l);
//        tcm.getColumn(10).setCellRenderer(l);
        
    }

    private void clearModel() {
        int size = tbltable.getRowCount();
        for (int i = 0; i < size; i++) {
            model.removeRow(0);
        }
    }


    

    
    
    private void showtable(String where,String code)
    {
        try {
            clearModel();
            stmt = (Statement) dbUtility.con.createStatement();
            int count = 0;
            
            if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
            String sql = "select * from vender where "+where+"  like '%" + cvth.Unicode2ASCII(code) + "%' order by vCode";
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                
                count++;
                    
                                model.addRow(new Object[]{
                                cvth.ASCII2Unicode(rs.getString("vcode")),
                                cvth.ASCII2Unicode(rs.getString("vname")),
                                cvth.ASCII2Unicode(rs.getString("vtel")),
                                cvth.ASCII2Unicode(rs.getString("vfax")),
                                cvth.ASCII2Unicode(rs.getString("vcontack"))
                                
                            });

            }
            rs.close();
            stmt.close();
            }
            else
            {
            String sql = "select * from vender where "+where+"  like '%" + code + "%' order by vCode";
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                
                String remark ="";
                count++;
                 
                   model.addRow(new Object[]{
                                rs.getString("vcode"),
                                rs.getString("vname"),
                                rs.getString("vtel"),
                                rs.getString("vfax"),
                                rs.getString("vcontack")
                           });
            rs.close();
            stmt.close();
            }
            }
            lbllist.setText(count+"");
            tbltable.requestFocus();
            cleartxt();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    private void cleartxt()
    {
        
        txtname.setText("");
        txtid.setText("");
        
        
    }
   
}
