/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package masterfile;

import Main.MainControl;
import borfunction.GetApplicationName;
import borfunction.GetUser;
import dbutility.dbUtility;
import frmlist.ShowBranchOfCompany;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import report.Report;
import utilititiesfunction.Format;
import utilititiesfunction.ThaiUtilities;
import utilititiesfunction.UserLogin;
import utilititiesfunction.getLanguage;

/**
 *
 * @author s386
 */
public class CompanySet extends javax.swing.JFrame {

    /**
     * Creates new form CompanySet
     */
    dbUtility db = new dbUtility();
    Statement stmt;
    String frmName = "companyset";
    boolean chkData = true;
    ThaiUtilities cvth = new ThaiUtilities();
    DefaultTableModel tbBranctype;
    getLanguage lang = new getLanguage();

    public CompanySet() {
        initComponents();
        checkuserconfig();
        db.dbconnect();
        //showdata();

//        txtfCompanyCode.setBackground(new java.awt.Color(255, 246, 143));
//        txtfCompanyCode.setEditable(false);
        this.setExtendedState(CompanySet.MAXIMIZED_BOTH);
        tbBranctype = (DefaultTableModel) tbl.getModel();
        tbl.setShowGrid(true);
        tbl.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tbl.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbl.setRowSelectionAllowed(true);
        tbl.setBackground(java.awt.Color.WHITE);
        tbl.setGridColor(java.awt.Color.gray);
        JTableHeader header = tbl.getTableHeader();
        header.setFont(new java.awt.Font("Norasi", java.awt.Font.BOLD, 14));
        tbl.setFont(new java.awt.Font("Norasi", java.awt.Font.BOLD, 14));
        tbl.setRowHeight(25);
        db.dbconnect();
        showdataintb();
        setFocus(false);
        // clear();

        lang.setText(frmName, this, lang.getChklang());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        d_lblCompanyCode = new javax.swing.JLabel();
        txtfCompanyCode = new javax.swing.JTextField();
        txtfCompanyName = new javax.swing.JTextField();
        d_lblCompanyName = new javax.swing.JLabel();
        d_lblAddress = new javax.swing.JLabel();
        txtfAddress = new javax.swing.JTextField();
        d_lblZone = new javax.swing.JLabel();
        txtfZone = new javax.swing.JTextField();
        txtfProvince = new javax.swing.JTextField();
        d_lblProvince = new javax.swing.JLabel();
        d_lblTel = new javax.swing.JLabel();
        d_lblFax = new javax.swing.JLabel();
        txtfFax = new javax.swing.JTextField();
        txtfEmail = new javax.swing.JTextField();
        d_lblEmail = new javax.swing.JLabel();
        d_lblPost = new javax.swing.JLabel();
        d_lblPrefecture = new javax.swing.JLabel();
        txtfPost = new javax.swing.JTextField();
        txtfPrefecture = new javax.swing.JTextField();
        txtfTel = new javax.swing.JTextField();
        txtfBusid = new javax.swing.JTextField();
        txtfTax = new javax.swing.JTextField();
        d_lblTax = new javax.swing.JLabel();
        d_lblBusid = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        xb_lblDisplay = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDetete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        db_btnPrint = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btnShowBranch = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuFunc = new javax.swing.JMenu();
        menuCancel = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuDelete = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("กำหนดรายละเอียดข้อมูลบริษัท (Company Seting)");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(700, 268));

        d_lblCompanyCode.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_lblCompanyCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_lblCompanyCode.setText("รหัสบริษัท");
        d_lblCompanyCode.setName("d_lblCompanyCode"); // NOI18N

        txtfCompanyCode.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtfCompanyCode.setForeground(new java.awt.Color(255, 0, 0));
        txtfCompanyCode.setName("txtfCompanyCode"); // NOI18N
        txtfCompanyCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfCompanyCodeActionPerformed(evt);
            }
        });
        txtfCompanyCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfCompanyCodeFocusLost(evt);
            }
        });
        txtfCompanyCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfCompanyCodeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfCompanyCodeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfCompanyCodeKeyTyped(evt);
            }
        });

        txtfCompanyName.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtfCompanyName.setName("txtfCompanyName"); // NOI18N
        txtfCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfCompanyNameActionPerformed(evt);
            }
        });
        txtfCompanyName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfCompanyNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfCompanyNameFocusLost(evt);
            }
        });
        txtfCompanyName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfCompanyNameKeyPressed(evt);
            }
        });

        d_lblCompanyName.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_lblCompanyName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_lblCompanyName.setText("ชื่อร้าน/บริษัท");
        d_lblCompanyName.setName("d_lblCompanyName"); // NOI18N

        d_lblAddress.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_lblAddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_lblAddress.setText("ที่อยู่เลขที่");
        d_lblAddress.setName("d_lblAddress"); // NOI18N

        txtfAddress.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtfAddress.setName("txtfAddress"); // NOI18N
        txtfAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfAddressActionPerformed(evt);
            }
        });
        txtfAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfAddressFocusLost(evt);
            }
        });
        txtfAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfAddressKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfAddressKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfAddressKeyTyped(evt);
            }
        });

        d_lblZone.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_lblZone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_lblZone.setText("ตำบล/แขวง");
        d_lblZone.setName("d_lblZone"); // NOI18N

        txtfZone.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtfZone.setName("txtfZone"); // NOI18N
        txtfZone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfZoneActionPerformed(evt);
            }
        });
        txtfZone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfZoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfZoneFocusLost(evt);
            }
        });
        txtfZone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfZoneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfZoneKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfZoneKeyTyped(evt);
            }
        });

        txtfProvince.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtfProvince.setName("txtfProvince"); // NOI18N
        txtfProvince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfProvinceActionPerformed(evt);
            }
        });
        txtfProvince.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfProvinceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfProvinceFocusLost(evt);
            }
        });
        txtfProvince.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfProvinceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfProvinceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfProvinceKeyTyped(evt);
            }
        });

        d_lblProvince.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_lblProvince.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_lblProvince.setText("จังหวัด");
        d_lblProvince.setName("d_lblProvince"); // NOI18N

        d_lblTel.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_lblTel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_lblTel.setText("เบอร์โทรศัพท์");
        d_lblTel.setName("d_lblTel"); // NOI18N

        d_lblFax.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_lblFax.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_lblFax.setText("เบอร์โทรสาร");
        d_lblFax.setName("d_lblFax"); // NOI18N

        txtfFax.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtfFax.setName("txtfFax"); // NOI18N
        txtfFax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfFaxActionPerformed(evt);
            }
        });
        txtfFax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfFaxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfFaxFocusLost(evt);
            }
        });
        txtfFax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfFaxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfFaxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfFaxKeyTyped(evt);
            }
        });

        txtfEmail.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtfEmail.setName("txtfEmail"); // NOI18N
        txtfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfEmailActionPerformed(evt);
            }
        });
        txtfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfEmailFocusLost(evt);
            }
        });
        txtfEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfEmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfEmailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfEmailKeyTyped(evt);
            }
        });

        d_lblEmail.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_lblEmail.setText("e-mail address");
        d_lblEmail.setName("d_lblEmail"); // NOI18N

        d_lblPost.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_lblPost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_lblPost.setText("รหัสไปรษณีย์");
        d_lblPost.setName("d_lblPost"); // NOI18N

        d_lblPrefecture.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_lblPrefecture.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_lblPrefecture.setText("อำเภอ/เขต");
        d_lblPrefecture.setName("d_lblPrefecture"); // NOI18N

        txtfPost.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtfPost.setName("txtfPost"); // NOI18N
        txtfPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfPostActionPerformed(evt);
            }
        });
        txtfPost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfPostFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfPostFocusLost(evt);
            }
        });
        txtfPost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfPostKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfPostKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfPostKeyTyped(evt);
            }
        });

        txtfPrefecture.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtfPrefecture.setName("txtfPrefecture"); // NOI18N
        txtfPrefecture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfPrefectureActionPerformed(evt);
            }
        });
        txtfPrefecture.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfPrefectureFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfPrefectureFocusLost(evt);
            }
        });
        txtfPrefecture.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfPrefectureKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfPrefectureKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfPrefectureKeyTyped(evt);
            }
        });

        txtfTel.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtfTel.setName("txtfTel"); // NOI18N
        txtfTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfTelActionPerformed(evt);
            }
        });
        txtfTel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfTelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfTelFocusLost(evt);
            }
        });
        txtfTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfTelKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfTelKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfTelKeyTyped(evt);
            }
        });

        txtfBusid.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtfBusid.setName("txtfPrefecture"); // NOI18N
        txtfBusid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfBusidActionPerformed(evt);
            }
        });
        txtfBusid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfBusidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfBusidFocusLost(evt);
            }
        });
        txtfBusid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfBusidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfBusidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfBusidKeyTyped(evt);
            }
        });

        txtfTax.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtfTax.setName("txtfPost"); // NOI18N
        txtfTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfTaxActionPerformed(evt);
            }
        });
        txtfTax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfTaxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfTaxFocusLost(evt);
            }
        });
        txtfTax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfTaxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfTaxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfTaxKeyTyped(evt);
            }
        });

        d_lblTax.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_lblTax.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_lblTax.setText("เลขประจำตัวผู้เสียภาษี");
        d_lblTax.setName("d_lblTax"); // NOI18N

        d_lblBusid.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_lblBusid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_lblBusid.setText("เลขทะเบียนการค้า");
        d_lblBusid.setName("d_lblBusid"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(d_lblCompanyCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(d_lblCompanyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(d_lblAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtfCompanyName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfCompanyCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(d_lblFax, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtfFax))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(d_lblTel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtfTel))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(d_lblProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtfProvince))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(d_lblZone, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtfZone, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(d_lblPrefecture, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d_lblPost, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d_lblBusid, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d_lblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(d_lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfPost, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfPrefecture)
                            .addComponent(txtfBusid)
                            .addComponent(txtfTax, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d_lblCompanyCode)
                    .addComponent(txtfCompanyCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_lblCompanyName))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_lblAddress))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfZone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_lblZone)
                    .addComponent(txtfPrefecture, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_lblPrefecture))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_lblProvince)
                    .addComponent(txtfPost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_lblPost))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfTel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d_lblTel))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfFax, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d_lblFax)
                            .addComponent(d_lblTax)
                            .addComponent(txtfTax, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtfBusid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(d_lblBusid)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_lblEmail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        xb_lblDisplay.setFont(new java.awt.Font("Norasi", 1, 20)); // NOI18N
        xb_lblDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xb_lblDisplay.setText("รายละเอียดข้อมูลบริษัท (Company Setup)");
        xb_lblDisplay.setName("xb_lblDisplay"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xb_lblDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xb_lblDisplay)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCancel.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cancel-icon.png"))); // NOI18N
        btnCancel.setText("ยกเลิก");
        btnCancel.setFocusable(false);
        btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancel.setIconTextGap(0);
        btnCancel.setName("db_btnCancel"); // NOI18N
        btnCancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save-icon.png"))); // NOI18N
        btnSave.setText("บันทึกข้อมูล");
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setIconTextGap(0);
        btnSave.setName("db_btnSave"); // NOI18N
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDetete.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btnDetete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete-icons.png"))); // NOI18N
        btnDetete.setText("ลบข้อมูล");
        btnDetete.setFocusable(false);
        btnDetete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDetete.setIconTextGap(0);
        btnDetete.setName("db_btnDetete"); // NOI18N
        btnDetete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDetete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeteteActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LogOut-icon.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setIconTextGap(0);
        btnExit.setName("db_btnExit"); // NOI18N
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        db_btnPrint.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Printer-icon.png"))); // NOI18N
        db_btnPrint.setText("พิมม์");
        db_btnPrint.setFocusable(false);
        db_btnPrint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        db_btnPrint.setIconTextGap(0);
        db_btnPrint.setName("db_btnPrint"); // NOI18N
        db_btnPrint.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        db_btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDetete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 520, Short.MAX_VALUE)
                .addComponent(db_btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(db_btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnDetete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(202, 218, 253));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "รหัสบริษัท", "ชื่อร้าน/บริษัท", "ที่อยู่เลขที่", "ตำบล/แขวง", "อำเภอ/เขต", "จังหวัด", "รหัสไปรษณีย์", "เบอร์โทรศัพท์", "เบอร์โทรสาร", "E-mail address", "เลขทะเบียนการค้า", "เลขประจำตัวผู้เสียภาษี"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.setName("tbl"); // NOI18N
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);
        if (tbl.getColumnModel().getColumnCount() > 0) {
            tbl.getColumnModel().getColumn(0).setMinWidth(100);
            tbl.getColumnModel().getColumn(0).setPreferredWidth(100);
            tbl.getColumnModel().getColumn(0).setMaxWidth(100);
            tbl.getColumnModel().getColumn(1).setMinWidth(200);
            tbl.getColumnModel().getColumn(1).setMaxWidth(350);
            tbl.getColumnModel().getColumn(2).setMinWidth(200);
            tbl.getColumnModel().getColumn(2).setMaxWidth(500);
            tbl.getColumnModel().getColumn(3).setMinWidth(120);
            tbl.getColumnModel().getColumn(3).setMaxWidth(250);
            tbl.getColumnModel().getColumn(4).setMinWidth(120);
            tbl.getColumnModel().getColumn(4).setMaxWidth(250);
            tbl.getColumnModel().getColumn(5).setMinWidth(120);
            tbl.getColumnModel().getColumn(5).setMaxWidth(250);
            tbl.getColumnModel().getColumn(7).setMinWidth(120);
            tbl.getColumnModel().getColumn(7).setMaxWidth(200);
            tbl.getColumnModel().getColumn(8).setMinWidth(120);
            tbl.getColumnModel().getColumn(8).setMaxWidth(200);
            tbl.getColumnModel().getColumn(9).setMinWidth(150);
            tbl.getColumnModel().getColumn(9).setMaxWidth(250);
            tbl.getColumnModel().getColumn(10).setMinWidth(150);
            tbl.getColumnModel().getColumn(10).setMaxWidth(250);
            tbl.getColumnModel().getColumn(11).setMinWidth(150);
            tbl.getColumnModel().getColumn(11).setMaxWidth(250);
        }

        btnShowBranch.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        btnShowBranch.setText("แสดงรายการสาขาในแต่ละบริษัท (Company)");
        btnShowBranch.setName("d_btnShowBranch"); // NOI18N
        btnShowBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowBranchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnShowBranch)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowBranch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuFunc.setText("ฟังก์ชั่น");
        menuFunc.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        menuFunc.setName("menuFunc"); // NOI18N

        menuCancel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menuCancel.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menuCancel.setText("ยกเลิก");
        menuCancel.setName("menuCancel"); // NOI18N
        menuCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCancelActionPerformed(evt);
            }
        });
        menuFunc.add(menuCancel);

        menuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSave.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menuSave.setText("บันทึกข้อมูล");
        menuSave.setName("menuSave"); // NOI18N
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        menuFunc.add(menuSave);

        menuDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuDelete.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menuDelete.setText("ลบข้อมูล");
        menuDelete.setName("menuDelete"); // NOI18N
        menuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeleteActionPerformed(evt);
            }
        });
        menuFunc.add(menuDelete);

        jSeparator1.setName("jSpeparator1"); // NOI18N
        menuFunc.add(jSeparator1);

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuExit.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menuExit.setText("Exit");
        menuExit.setName("menuExit"); // NOI18N
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuFunc.add(menuExit);

        jMenuBar2.add(menuFunc);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1032, 796));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkuserconfig() {
        //MenuName = Mast1
        UserLogin userrec = UserLogin.userlogin;
        if (userrec.getMast1().equals("1")) {
            btnSave.setEnabled(false);
            btnDetete.setEnabled(false);
            menuSave.setEnabled(false);
            menuDelete.setEnabled(false);
        }
        if (userrec.getMast1().equals("2")) {
            btnSave.setEnabled(true);
            btnDetete.setEnabled(false);
            menuSave.setEnabled(true);
            menuDelete.setEnabled(false);
        }
        if (userrec.getMast1().equals("3")) {
            btnSave.setEnabled(true);
            btnDetete.setEnabled(true);
            menuSave.setEnabled(true);
            menuDelete.setEnabled(true);
        }
    }
    private void txtfTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfTelKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfTelKeyTyped

    private void txtfTelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfTelKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfTelKeyReleased

    private void txtfTelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfTelKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtfFax.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfTelKeyPressed

    private void txtfTelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfTelFocusLost
        txtfTel.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfTelFocusLost

    private void txtfTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfTelActionPerformed

    private void txtfPrefectureKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfPrefectureKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPrefectureKeyTyped

    private void txtfPrefectureKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfPrefectureKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPrefectureKeyReleased

    private void txtfPrefectureKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfPrefectureKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtfProvince.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPrefectureKeyPressed

    private void txtfPrefectureFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfPrefectureFocusLost
        txtfPrefecture.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPrefectureFocusLost

    private void txtfPrefectureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfPrefectureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPrefectureActionPerformed

    private void txtfPostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfPostKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPostKeyTyped

    private void txtfPostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfPostKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPostKeyReleased

    private void txtfPostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfPostKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtfTel.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPostKeyPressed

    private void txtfPostFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfPostFocusLost
        txtfPost.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPostFocusLost

    private void txtfPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfPostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPostActionPerformed

    private void txtfEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfEmailKeyTyped

    private void txtfEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfEmailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfEmailKeyReleased

    private void txtfEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfEmailKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtfBusid.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfEmailKeyPressed

    private void txtfEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfEmailFocusLost
        txtfEmail.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfEmailFocusLost

    private void txtfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfEmailActionPerformed

    private void txtfFaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfFaxKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfFaxKeyTyped

    private void txtfFaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfFaxKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfFaxKeyReleased

    private void txtfFaxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfFaxKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtfEmail.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfFaxKeyPressed

    private void txtfFaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfFaxFocusLost
        txtfFax.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfFaxFocusLost

    private void txtfFaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfFaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfFaxActionPerformed

    private void txtfProvinceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfProvinceKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfProvinceKeyTyped

    private void txtfProvinceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfProvinceKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfProvinceKeyReleased

    private void txtfProvinceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfProvinceKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtfPost.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfProvinceKeyPressed

    private void txtfProvinceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfProvinceFocusLost
        txtfProvince.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfProvinceFocusLost

    private void txtfProvinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfProvinceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfProvinceActionPerformed

    private void txtfZoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfZoneKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfZoneKeyTyped

    private void txtfZoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfZoneKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfZoneKeyReleased

    private void txtfZoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfZoneKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtfPrefecture.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfZoneKeyPressed

    private void txtfZoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfZoneFocusLost
        txtfZone.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfZoneFocusLost

    private void txtfZoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfZoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfZoneActionPerformed

    private void txtfAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfAddressKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfAddressKeyTyped

    private void txtfAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfAddressKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfAddressKeyReleased

    private void txtfAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfAddressKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtfZone.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtfAddressKeyPressed

    private void txtfAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfAddressFocusLost
        txtfAddress.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfAddressFocusLost

    private void txtfAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfAddressActionPerformed

    private void txtfCompanyNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfCompanyNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtfAddress.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfCompanyNameKeyPressed

    private void txtfCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfCompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfCompanyNameActionPerformed

    private void txtfCompanyCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfCompanyCodeKeyTyped
        if (txtfCompanyCode.getText().length() >= 3) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfCompanyCodeKeyTyped

    private void txtfCompanyCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfCompanyCodeKeyReleased
        String get = txtfCompanyCode.getText();
        String out = get.toUpperCase();
        txtfCompanyCode.setText(out);

        // TODO add your handling code here:
 }//GEN-LAST:event_txtfCompanyCodeKeyReleased

    private void txtfCompanyCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfCompanyCodeKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txtfCompanyCode.getText().equals("")) {
                setFocus(true);
                txtfCompanyName.requestFocus();

            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtfCompanyCodeKeyPressed

    private void txtfCompanyCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfCompanyCodeFocusLost
        if (!txtfCompanyCode.getText().equals("")) {
            enter();
        }
        // TODO add your handling code here:
  }//GEN-LAST:event_txtfCompanyCodeFocusLost

    private void txtfCompanyCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfCompanyCodeActionPerformed
        // TODO add your handling code here:
   }//GEN-LAST:event_txtfCompanyCodeActionPerformed

    private void txtfBusidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfBusidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfBusidActionPerformed

    private void txtfBusidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfBusidFocusLost
        txtfBusid.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfBusidFocusLost

    private void txtfBusidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfBusidKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtfTax.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfBusidKeyPressed

    private void txtfBusidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfBusidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfBusidKeyReleased

    private void txtfBusidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfBusidKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfBusidKeyTyped

    private void txtfTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfTaxActionPerformed

    private void txtfTaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfTaxFocusLost
        txtfTax.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfTaxFocusLost

    private void txtfTaxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfTaxKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtfCompanyName.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfTaxKeyPressed

    private void txtfTaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfTaxKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfTaxKeyReleased

    private void txtfTaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfTaxKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfTaxKeyTyped

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (!txtfCompanyCode.getText().equals("")) {
            btnsave();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeteteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeteteActionPerformed
        if (!txtfCompanyCode.getText().trim().equals("") && chkdata(txtfCompanyCode.getText()) && txtfCompanyName.isFocusable()) {
            delete();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeteteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void db_btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_btnPrintActionPerformed
        Map parm = new HashMap();
        JRBeanCollectionDataSource ds = null;
        ds = new JRBeanCollectionDataSource(report.dataBeanCompany.getCompany());
        parm.put("companyName", lang.getTextCompanyReport());
        parm.put("Reportheader", lang.getTextReport(frmName, "texthead"));
        //String test = new String(lang.getTextReport(frmName, "code"));

        parm.put("code", lang.getTextReport(frmName, "code"));
        parm.put("name", lang.getTextReport(frmName, "name"));
        parm.put("other1", lang.getTextReport(frmName, "other1"));
        parm.put("other2", lang.getTextReport(frmName, "other2"));
        parm.put("other3", lang.getTextReport(frmName, "other3"));
        parm.put("other4", lang.getTextReport(frmName, "other4"));
        parm.put("other5", lang.getTextReport(frmName, "other5"));
        parm.put("other6", lang.getTextReport(frmName, "other6"));
        parm.put("other7", lang.getTextReport(frmName, "other7"));
        parm.put("other8", lang.getTextReport(frmName, "other8"));
        parm.put("other9", lang.getTextReport(frmName, "other9"));
        parm.put("other10", lang.getTextReport(frmName, "other10"));
        parm.put("totalall", lang.getTextReport(frmName, "totalall"));
        parm.put("branchtxt", lang.getTextReport(frmName, "branchtxt"));
        parm.put("application", new GetApplicationName().getApplicationName());
        parm.put("user", new GetUser().getUser());
        parm.put("currentDate", Format.dateFmtReport.format(new java.util.Date()));

        String rptName = "rptcompany";
        Report rpt = new Report();
        rpt.viewReportbean(rptName, parm, frmName, ds);
        // TODO add your handling code here:
    }//GEN-LAST:event_db_btnPrintActionPerformed

    private void tblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseReleased
        if (evt.getClickCount() == 2) {
            int index = tbl.getSelectedRow();
            String typecode = tbl.getValueAt(index, 0).toString();
            String typedis = tbl.getValueAt(index, 1).toString();
            if (txtfCompanyCode.getText().equals("")) {
                txtfCompanyCode.setText(tbl.getValueAt(index, 0).toString());
                txtfCompanyName.setText(tbl.getValueAt(index, 1).toString());
                txtfAddress.setText(tbl.getValueAt(index, 2).toString());
                txtfZone.setText(tbl.getValueAt(index, 3).toString());
                txtfPrefecture.setText(tbl.getValueAt(index, 4).toString());
                txtfProvince.setText(tbl.getValueAt(index, 5).toString());
                txtfPost.setText(tbl.getValueAt(index, 6).toString());
                txtfTel.setText(tbl.getValueAt(index, 7).toString());
                txtfFax.setText(tbl.getValueAt(index, 8).toString());
                txtfEmail.setText(tbl.getValueAt(index, 9).toString());
                txtfBusid.setText(tbl.getValueAt(index, 10).toString());
                txtfTax.setText(tbl.getValueAt(index, 11).toString());

            } else if (!txtfCompanyCode.getText().equals(typecode)) {
                int confirm = JOptionPane.showConfirmDialog(this, "คุณมีการเพิ่มหรือแก้ไขข้อมูลอยู่ คุณต้องการยกเลิกการเพิ่มหรือแก้ไขข้อมูลนั้นหรือไม่", "Confirm", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    txtfCompanyCode.setText(tbl.getValueAt(index, 0).toString());
                    txtfCompanyName.setText(tbl.getValueAt(index, 1).toString());
                    txtfAddress.setText(tbl.getValueAt(index, 2).toString());
                    txtfZone.setText(tbl.getValueAt(index, 3).toString());
                    txtfPrefecture.setText(tbl.getValueAt(index, 4).toString());
                    txtfProvince.setText(tbl.getValueAt(index, 5).toString());
                    txtfPost.setText(tbl.getValueAt(index, 6).toString());
                    txtfTel.setText(tbl.getValueAt(index, 7).toString());
                    txtfFax.setText(tbl.getValueAt(index, 8).toString());
                    txtfEmail.setText(tbl.getValueAt(index, 9).toString());
                    txtfBusid.setText(tbl.getValueAt(index, 10).toString());
                    txtfTax.setText(tbl.getValueAt(index, 11).toString());

                }
            }

            txtfCompanyName.requestFocus();
            setFocus(true);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblMouseReleased

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveMouseClicked

    private void menuCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCancelActionPerformed
        btnCancelActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCancelActionPerformed

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed
        btnSaveActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSaveActionPerformed

    private void menuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeleteActionPerformed
        btnDeteteActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDeleteActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        btnExitActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuExitActionPerformed

    private void btnShowBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowBranchActionPerformed
        ShowBranchOfCompany f = new ShowBranchOfCompany(this, true);
        f.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowBranchActionPerformed

    private void txtfCompanyNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfCompanyNameFocusGained
        txtfCompanyName.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfCompanyNameFocusGained

    private void txtfCompanyNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfCompanyNameFocusLost
        txtfCompanyName.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfCompanyNameFocusLost

    private void txtfAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfAddressFocusGained
        txtfAddress.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfAddressFocusGained

    private void txtfZoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfZoneFocusGained
        txtfZone.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfZoneFocusGained

    private void txtfProvinceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfProvinceFocusGained
        txtfProvince.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfProvinceFocusGained

    private void txtfTelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfTelFocusGained
        txtfTel.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfTelFocusGained

    private void txtfFaxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfFaxFocusGained
        txtfFax.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfFaxFocusGained

    private void txtfEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfEmailFocusGained
        txtfEmail.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfEmailFocusGained

    private void txtfPrefectureFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfPrefectureFocusGained
        txtfPrefecture.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPrefectureFocusGained

    private void txtfPostFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfPostFocusGained
        txtfPost.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPostFocusGained

    private void txtfBusidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfBusidFocusGained
        txtfBusid.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfBusidFocusGained

    private void txtfTaxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfTaxFocusGained
        txtfTax.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfTaxFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompanySet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompanySet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompanySet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompanySet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CompanySet().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDetete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnShowBranch;
    private javax.swing.JLabel d_lblAddress;
    private javax.swing.JLabel d_lblBusid;
    private javax.swing.JLabel d_lblCompanyCode;
    private javax.swing.JLabel d_lblCompanyName;
    private javax.swing.JLabel d_lblEmail;
    private javax.swing.JLabel d_lblFax;
    private javax.swing.JLabel d_lblPost;
    private javax.swing.JLabel d_lblPrefecture;
    private javax.swing.JLabel d_lblProvince;
    private javax.swing.JLabel d_lblTax;
    private javax.swing.JLabel d_lblTel;
    private javax.swing.JLabel d_lblZone;
    private javax.swing.JButton db_btnPrint;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuCancel;
    private javax.swing.JMenuItem menuDelete;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuFunc;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtfAddress;
    private javax.swing.JTextField txtfBusid;
    private javax.swing.JTextField txtfCompanyCode;
    private javax.swing.JTextField txtfCompanyName;
    private javax.swing.JTextField txtfEmail;
    private javax.swing.JTextField txtfFax;
    private javax.swing.JTextField txtfPost;
    private javax.swing.JTextField txtfPrefecture;
    private javax.swing.JTextField txtfProvince;
    private javax.swing.JTextField txtfTax;
    private javax.swing.JTextField txtfTel;
    private javax.swing.JTextField txtfZone;
    private javax.swing.JLabel xb_lblDisplay;
    // End of variables declaration//GEN-END:variables
    public void btnsave() {

        if (validateSave()) {
            if (chkdata(txtfCompanyCode.getText())) {

                try {
                    if (!db.Char_Set.equalsIgnoreCase("utf-8")) {
                        stmt = (Statement) db.con.createStatement();
                        String sql = "Update company set name = ?,address = ?,subprovince = ?,province = ?,city = ?,post = "
                                + "?,tel = ?,fax = ?,emailaddress=?,businessid=?,tax=? "
                                + " where code=?";
                        PreparedStatement prm = (PreparedStatement) db.con.prepareStatement(sql);
                        prm.setString(1, cvth.Unicode2ASCII(txtfCompanyName.getText()));
                        prm.setString(2, cvth.Unicode2ASCII(txtfAddress.getText()));
                        prm.setString(3, cvth.Unicode2ASCII(txtfZone.getText()));
                        prm.setString(4, cvth.Unicode2ASCII(txtfPrefecture.getText()));
                        prm.setString(5, cvth.Unicode2ASCII(txtfProvince.getText()));
                        prm.setString(6, cvth.Unicode2ASCII(txtfPost.getText()));
                        prm.setString(7, cvth.Unicode2ASCII(txtfTel.getText()));
                        prm.setString(8, cvth.Unicode2ASCII(txtfFax.getText()));
                        prm.setString(9, cvth.Unicode2ASCII(txtfEmail.getText()));
                        prm.setString(10, cvth.Unicode2ASCII(txtfBusid.getText()));
                        prm.setString(11, cvth.Unicode2ASCII(txtfTax.getText()));
                        prm.setString(12, cvth.Unicode2ASCII(txtfCompanyCode.getText()));
                        prm.executeUpdate();

                    } else {
                        stmt = (Statement) db.con.createStatement();
                        String sql = "Update company set name = ?,address = ?,subprovince = ?,province = ?,city = ?,post = "
                                + "?,tel = ?,fax = ?,emailaddress=?,businessid=?,tax=? "
                                + " where code=?";
                        PreparedStatement prm = (PreparedStatement) db.con.prepareStatement(sql);
                        prm.setString(1, txtfCompanyName.getText());
                        prm.setString(2, txtfAddress.getText());
                        prm.setString(3, txtfZone.getText());
                        prm.setString(4, txtfPrefecture.getText());
                        prm.setString(5, txtfProvince.getText());
                        prm.setString(6, txtfPost.getText());
                        prm.setString(7, txtfTel.getText());
                        prm.setString(8, txtfFax.getText());
                        prm.setString(9, txtfEmail.getText());
                        prm.setString(10, txtfBusid.getText());
                        prm.setString(11, txtfTax.getText());
                        prm.setString(12, txtfCompanyCode.getText());
                        prm.executeUpdate();

                    }
                    stmt.close();
                    clear();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "Update Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                try {
                    if (!db.Char_Set.equalsIgnoreCase("utf-8")) {
                        stmt = (Statement) db.con.createStatement();
                        String sql = "Insert into company (name,address,subprovince,province,city,post"
                                + ",tel,fax,emailaddress,businessid,tax  "
                                + ",code) values(?,?,?,?,?,?,?,?,?,?,?,?)";
                        PreparedStatement prm = (PreparedStatement) db.con.prepareStatement(sql);
                        prm.setString(1, cvth.Unicode2ASCII(txtfCompanyName.getText()));
                        prm.setString(2, cvth.Unicode2ASCII(txtfAddress.getText()));
                        prm.setString(3, cvth.Unicode2ASCII(txtfZone.getText()));
                        prm.setString(4, cvth.Unicode2ASCII(txtfPrefecture.getText()));
                        prm.setString(5, cvth.Unicode2ASCII(txtfProvince.getText()));
                        prm.setString(6, cvth.Unicode2ASCII(txtfPost.getText()));
                        prm.setString(7, cvth.Unicode2ASCII(txtfTel.getText()));
                        prm.setString(8, cvth.Unicode2ASCII(txtfFax.getText()));
                        prm.setString(9, cvth.Unicode2ASCII(txtfEmail.getText()));
                        prm.setString(10, cvth.Unicode2ASCII(txtfBusid.getText()));
                        prm.setString(11, cvth.Unicode2ASCII(txtfTax.getText()));
                        prm.setString(12, cvth.Unicode2ASCII(txtfCompanyCode.getText()));
                        prm.executeUpdate();
                    } else {
                        stmt = (Statement) db.con.createStatement();
                        String sql = "Insert into company (name,address,subprovince,province,city,post"
                                + ",tel,fax,emailaddress,businessid,tax "
                                + ",code) values(?,?,?,?,?,?,?,?,?,?,?,?)";
                        PreparedStatement prm = (PreparedStatement) db.con.prepareStatement(sql);
                        prm.setString(1, txtfCompanyName.getText());
                        prm.setString(2, txtfAddress.getText());
                        prm.setString(3, txtfZone.getText());
                        prm.setString(4, txtfPrefecture.getText());
                        prm.setString(5, txtfProvince.getText());
                        prm.setString(6, txtfPost.getText());
                        prm.setString(7, txtfTel.getText());
                        prm.setString(8, txtfFax.getText());
                        prm.setString(9, txtfEmail.getText());
                        prm.setString(10, txtfBusid.getText());
                        prm.setString(11, txtfTax.getText());
                        prm.setString(12, txtfCompanyCode.getText());
                        prm.executeUpdate();
                    }
                    stmt.close();
                    clear();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "Insert Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            showdataintb();
        }

    }

    public void showdata() {
        stmt = null;
        ResultSet rs = null;

        try {
            stmt = (Statement) dbUtility.con.createStatement();
            String sql = "select * from company";
            rs = stmt.executeQuery(sql);
            rs.first();
            if (rs.getRow() > 0) {

                chkData = true;
                if (!db.Char_Set.equalsIgnoreCase("utf-8")) {
                    txtfCompanyCode.setText(cvth.ASCII2Unicode(rs.getString("code")));
                    txtfCompanyName.setText(cvth.ASCII2Unicode(rs.getString("name")));
                    txtfAddress.setText(cvth.ASCII2Unicode(rs.getString("address")));
                    txtfPost.setText(cvth.ASCII2Unicode(rs.getString("post")));
                    txtfPrefecture.setText(cvth.ASCII2Unicode(rs.getString("province")));
                    txtfProvince.setText(cvth.ASCII2Unicode(rs.getString("city")));
                    txtfZone.setText(cvth.ASCII2Unicode(rs.getString("subprovince")));
                    txtfTel.setText(cvth.ASCII2Unicode(rs.getString("tel")));
                    txtfFax.setText(cvth.ASCII2Unicode(rs.getString("fax")));
                    txtfEmail.setText(cvth.ASCII2Unicode(rs.getString("emailaddress")));
                } else {
                    txtfCompanyCode.setText(rs.getString("code"));
                    txtfCompanyName.setText(rs.getString("name"));
                    txtfAddress.setText(rs.getString("address"));
                    txtfPost.setText(rs.getString("post"));
                    txtfPrefecture.setText(rs.getString("province"));
                    txtfProvince.setText(rs.getString("city"));
                    txtfZone.setText(rs.getString("subprovince"));
                    txtfTel.setText(rs.getString("tel"));
                    txtfFax.setText(rs.getString("fax"));
                    txtfEmail.setText(rs.getString("emailaddress"));
                }
                txtfCompanyCode.requestFocus();
            } else {
                chkData = false;
                txtfCompanyCode.setText("");
                txtfCompanyName.setText("");
                txtfAddress.setText("");
                txtfPost.setText("");
                txtfPrefecture.setText("");
                txtfProvince.setText("");
                txtfZone.setText("");
                txtfTel.setText("");
                txtfFax.setText("");
                txtfEmail.setText("");
                txtfCompanyCode.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    public void clear() {
        txtfCompanyCode.setText("");
        txtfCompanyName.setText("");
        txtfAddress.setText("");
        txtfPost.setText("");
        txtfPrefecture.setText("");
        txtfProvince.setText("");
        txtfZone.setText("");
        txtfTel.setText("");
        txtfFax.setText("");
        txtfEmail.setText("");
        txtfBusid.setText("");
        txtfTax.setText("");
        setFocus(false);

        txtfCompanyCode.requestFocus();

    }

    private boolean validateSave() {
        boolean chk = true;
        if (txtfCompanyCode.getText().length() > 3) {
            JOptionPane.showMessageDialog(this, "กำหนดรหัสบริษัทไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 3 ตัวอักษร)");
            chk = false;
            txtfCompanyCode.requestFocus();
        } else if (!txtfCompanyName.isFocusable()) {
            chk = false;
        } else if (txtfCompanyName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "กำหนดชื่อบริษัทไม่ถูกต้อง... (กรุณากรอกชื่อบริษัท)");
            chk = false;
            txtfCompanyName.requestFocus();
        } else if (txtfCompanyName.getText().length() > 60) {
            JOptionPane.showMessageDialog(this, "กำหนดชื่อบริษัทไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 60 ตัวอักษร)");
            chk = false;
            txtfCompanyName.requestFocus();
        } else if (txtfAddress.getText().length() > 50) {
            JOptionPane.showMessageDialog(this, "กำหนดที่อยู่ไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 50 ตัวอักษร)");
            chk = false;
            txtfAddress.requestFocus();
        } else if (txtfZone.getText().length() > 30) {
            JOptionPane.showMessageDialog(this, "กำหนด แขวง/ตำบล ไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 30 ตัวอักษร)");
            chk = false;
            txtfZone.requestFocus();
        } else if (txtfPrefecture.getText().length() > 30) {
            JOptionPane.showMessageDialog(this, "กำหนด เขต/อำเภอ ไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 30 ตัวอักษร)");
            chk = false;
            txtfPrefecture.requestFocus();
        } else if (txtfProvince.getText().length() > 30) {
            JOptionPane.showMessageDialog(this, "กำหนด จังหวัด ไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 30 ตัวอักษร)");
            chk = false;
            txtfProvince.requestFocus();
        } else if (txtfPost.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "กำหนด รหัสไปรษณีย์ ไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 5 ตัวอักษร)");
            chk = false;
            txtfPost.requestFocus();
        } else if (txtfTel.getText().length() > 30) {
            JOptionPane.showMessageDialog(this, "กำหนด เบอร์โทรศัพท์ ไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 30 ตัวอักษร)");
            chk = false;
            txtfTel.requestFocus();
        } else if (txtfFax.getText().length() > 30) {
            JOptionPane.showMessageDialog(this, "กำหนด เบอร์โทรสาร ไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 30 ตัวอักษร)");
            chk = false;
            txtfFax.requestFocus();
        } else if (txtfEmail.getText().length() > 50) {
            JOptionPane.showMessageDialog(this, "กำหนด E-mail Address ไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 50 ตัวอักษร)");
            chk = false;
            txtfEmail.requestFocus();
        } else if (txtfBusid.getText().length() > 20) {
            JOptionPane.showMessageDialog(this, "กำหนด เลขทะเบียนการค้า ไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 20 ตัวอักษร)");
            chk = false;
            txtfEmail.requestFocus();
        } else if (txtfTax.getText().length() > 20) {
            JOptionPane.showMessageDialog(this, "กำหนด เลขประจำตัวผู้เสียภาษี ไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 20 ตัวอักษร)");
            chk = false;
            txtfTax.requestFocus();
        }

        return chk;
    }

    public void showdataintb() {
        stmt = null;
        ResultSet rs = null;

        tbBranctype = (DefaultTableModel) tbl.getModel();
        int cnt = tbBranctype.getRowCount();
        if (cnt > 0) {
            for (int i = 0; i < cnt; i++) {
                tbBranctype.removeRow(0);
            }
        }
        try {
            stmt = (Statement) dbUtility.con.createStatement();
            String sql = "select * from company order by code";
            rs = stmt.executeQuery(sql);
            while (rs.next()) {
                if (!db.Char_Set.equalsIgnoreCase("utf-8")) {
                    tbBranctype.addRow(new Object[]{cvth.ASCII2Unicode(rs.getString("code")),
                        cvth.ASCII2Unicode(rs.getString("name")),
                        cvth.ASCII2Unicode(rs.getString("address")),
                        cvth.ASCII2Unicode(rs.getString("subprovince")),
                        cvth.ASCII2Unicode(rs.getString("province")),
                        cvth.ASCII2Unicode(rs.getString("city")),
                        cvth.ASCII2Unicode(rs.getString("post")),
                        cvth.ASCII2Unicode(rs.getString("tel")),
                        cvth.ASCII2Unicode(rs.getString("fax")),
                        cvth.ASCII2Unicode(rs.getString("emailaddress")),
                        cvth.ASCII2Unicode(rs.getString("businessid")),
                        cvth.ASCII2Unicode(rs.getString("tax")),
                        cvth.ASCII2Unicode(rs.getString("use_sap_article"))
                    });
                } else {
                    tbBranctype.addRow(new Object[]{rs.getString("code"),
                        rs.getString("name"),
                        rs.getString("address"),
                        rs.getString("subprovince"),
                        rs.getString("province"),
                        rs.getString("city"),
                        rs.getString("post"),
                        rs.getString("tel"),
                        rs.getString("fax"),
                        rs.getString("emailaddress"),
                        rs.getString("businessid"),
                        rs.getString("tax"),
                        rs.getString("use_sap_article")
                    });
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    public boolean chkdata(String pk) {
        boolean chk = false;
        ResultSet rs = null;
        try {
            if (!db.Char_Set.equalsIgnoreCase("utf-8")) {
                stmt = (Statement) db.con.createStatement();
                String sql = "select * from company where code ='" + cvth.Unicode2ASCII(pk) + "'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    chk = true;
                }
            } else {
                stmt = (Statement) db.con.createStatement();
                String sql = "select * from company where code ='" + pk + "'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    chk = true;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);

        }
        return chk;
    }

    public void delete() {
        ResultSet rs = null;
        try {
            int chkbran = chkbranfile(txtfCompanyCode.getText());
            if (chkbran == 0) {
                int confirm = JOptionPane.showConfirmDialog(this, "คุณต้องการลบข้อมูลรายการนี้หรือไม่...?", "Confirm", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    if (!db.Char_Set.equalsIgnoreCase("utf-8")) {
                        stmt = (Statement) db.con.createStatement();
                        String sql = "Delete from company where code=?";
                        PreparedStatement prm = (PreparedStatement) db.con.prepareStatement(sql);
                        prm.setString(1, cvth.Unicode2ASCII(txtfCompanyCode.getText()));
                        prm.executeUpdate();
                    } else {
                        stmt = (Statement) db.con.createStatement();
                        String sql = "Delete from company where code=?";
                        PreparedStatement prm = (PreparedStatement) db.con.prepareStatement(sql);
                        prm.setString(1, txtfCompanyCode.getText());
                        prm.executeUpdate();
                        stmt.close();
                    }
                    clear();
                    showdataintb();
                }
            } else {
                if (chkbran != -1) {
                    JOptionPane.showMessageDialog(this, "ไม่สามารถลบข้อมูลได้ เนื่องจากมีข้อมูลอยู่ในสาขาจำนวน " + chkbranfile(txtfCompanyCode.getText()) + " รายการ");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    public int chkbranfile(String code) {

        ResultSet rs = null;
        int count = 0;
        try {
            if (!db.Char_Set.equalsIgnoreCase("utf-8")) {
                stmt = (Statement) db.con.createStatement();
                String sql = "select * from branfile where companycode ='" + cvth.Unicode2ASCII(code) + "'";
                rs = stmt.executeQuery(sql);
                while (rs.next()) {
                    count++;
                }
            } else {
                stmt = (Statement) db.con.createStatement();
                String sql = "select * from branfile where companycode ='" + code + "'";
                rs = stmt.executeQuery(sql);
                while (rs.next()) {
                    count++;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            count = -1;
        }
        return count;
    }

    public void enter() {
        ResultSet rs = null;
        try {
            if (!db.Char_Set.equalsIgnoreCase("utf-8")) {
                stmt = (Statement) db.con.createStatement();
                String sql = "select * from company where code ='" + cvth.Unicode2ASCII(txtfCompanyCode.getText()) + "'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {

                    txtfCompanyCode.setText(cvth.ASCII2Unicode(rs.getString("code")));
                    txtfCompanyName.setText(cvth.ASCII2Unicode(rs.getString("name")));
                    txtfAddress.setText(cvth.ASCII2Unicode(rs.getString("address")));
                    txtfZone.setText(cvth.ASCII2Unicode(rs.getString("subprovince")));
                    txtfPrefecture.setText(cvth.ASCII2Unicode(rs.getString("province")));
                    txtfProvince.setText(cvth.ASCII2Unicode(rs.getString("city")));
                    txtfPost.setText(cvth.ASCII2Unicode(rs.getString("post")));
                    txtfTel.setText(cvth.ASCII2Unicode(rs.getString("tel")));
                    txtfFax.setText(cvth.ASCII2Unicode(rs.getString("fax")));
                    txtfEmail.setText(cvth.ASCII2Unicode(rs.getString("emailaddress")));
                    txtfBusid.setText(cvth.ASCII2Unicode(rs.getString("businessid")));
                    txtfTax.setText(cvth.ASCII2Unicode(rs.getString("tax")));

                    txtfCompanyName.requestFocus();
                    setFocus(true);

                } else {
                    txtfCompanyName.requestFocus();
                    setFocus(true);
                }
            } else {
                stmt = (Statement) db.con.createStatement();
                String sql = "select * from company where code ='" + txtfCompanyCode.getText() + "'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {

                    txtfCompanyCode.setText(rs.getString("code"));
                    txtfCompanyName.setText(rs.getString("name"));
                    txtfAddress.setText(rs.getString("address"));
                    txtfZone.setText(rs.getString("subprovince"));
                    txtfPrefecture.setText(rs.getString("province"));
                    txtfProvince.setText(rs.getString("city"));
                    txtfPost.setText(rs.getString("post"));
                    txtfTel.setText(rs.getString("tel"));
                    txtfFax.setText(rs.getString("fax"));
                    txtfEmail.setText(rs.getString("emailaddress"));
                    txtfBusid.setText(rs.getString("businessid"));
                    txtfTax.setText(rs.getString("tax"));
                    txtfCompanyName.requestFocus();
                    setFocus(true);

                } else {
                    txtfCompanyName.requestFocus();
                    setFocus(true);
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void setFocus(boolean chk) {
        //txtfCompanyCode.setFocusable(chk);
        txtfCompanyName.setFocusable(chk);
        txtfAddress.setFocusable(chk);
        txtfPost.setFocusable(chk);
        txtfPrefecture.setFocusable(chk);
        txtfProvince.setFocusable(chk);
        txtfZone.setFocusable(chk);
        txtfTel.setFocusable(chk);
        txtfFax.setFocusable(chk);
        txtfEmail.setFocusable(chk);
        txtfBusid.setFocusable(chk);
        txtfTax.setFocusable(chk);
        if (chk == false) {
            txtfCompanyCode.setFocusable(true);
            txtfCompanyCode.setBackground(Color.WHITE);
        } else {
            txtfCompanyCode.setBackground(new java.awt.Color(255, 246, 143));
            txtfCompanyCode.setFocusable(false);
        }
    }
}
