/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package masterfile;

import borfunction.GetApplicationName;
import borfunction.GetUser;
import dbutility.dbUtility;
import frmlist.ShowBranchOfArea;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import jxl.write.WriteException;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.save.JRSingleSheetXlsSaveContributor;
import report.Report;
import utilititiesfunction.*;

/**
 *
 * @author s386
 */
public class CrAccNo extends javax.swing.JFrame {

    /**
     * Creates new form CrAccNo
     */
    DefaultTableModel tbBranctype ;
    dbUtility db = new dbUtility();
    Statement stmt ;
    String frmName = "craccno";
    ThaiUtilities cvth = new ThaiUtilities();
    getLanguage lang = new getLanguage();
    public CrAccNo() {
        initComponents();
        checkuserconfig();
        tbBranctype = (DefaultTableModel) tblBank.getModel();
        tblBank.setShowGrid(true);
        tblBank.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblBank.setRowSelectionAllowed(true);
        tblBank.setBackground(java.awt.Color.WHITE);
        tblBank.setGridColor(java.awt.Color.gray);
        JTableHeader header = tblBank.getTableHeader();
        header.setFont(new java.awt.Font("Norasi", java.awt.Font.BOLD, 14));
        //tblBtype.setFont(new java.awt.Font("Norasi", java.awt.Font.BOLD, 14));
        tblBank.setRowHeight(25);
        db.dbconnect();
        showdataintb();
        clear();
        
        lang.setText(frmName, this, lang.getChklang());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        d_lblBankCode = new javax.swing.JLabel();
        d_lblBankName = new javax.swing.JLabel();
        txtfBankCode = new javax.swing.JTextField();
        txtfBankName = new javax.swing.JTextField();
        d_lblSubAcc = new javax.swing.JLabel();
        txtfSubAcc = new javax.swing.JTextField();
        d_lblAccNo = new javax.swing.JLabel();
        txtfAccNo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBank = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDetete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        db_btnPrint = new javax.swing.JButton();
        db_btnExel = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuFunc = new javax.swing.JMenu();
        menuCancel = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuDelete = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("กำหนด Bank_Code และรหัสบัญชี");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        d_lblBankCode.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_lblBankCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_lblBankCode.setText("Bank_Code");
        d_lblBankCode.setName("d_lblBankCode");

        d_lblBankName.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_lblBankName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_lblBankName.setText("ชื่อธนาคาร");
        d_lblBankName.setName("d_lblBankName");

        txtfBankCode.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtfBankCode.setName("txtfBankCode");
        txtfBankCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfBankCodeActionPerfrmed(evt);
            }
        });
        txtfBankCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfBankCodeFocusLost(evt);
            }
        });
        txtfBankCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfBankCodeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfBankCodeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfBankCodeKeyTyped(evt);
            }
        });

        txtfBankName.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtfBankName.setName("txtfBankName");
        txtfBankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfBankNameActionPerformed(evt);
            }
        });
        txtfBankName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfBankNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfBankNameFocusLost(evt);
            }
        });
        txtfBankName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfBankNameKeyPressed(evt);
            }
        });

        d_lblSubAcc.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_lblSubAcc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_lblSubAcc.setText("Sub Acc");
        d_lblSubAcc.setName("d_lblSubAcc");

        txtfSubAcc.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtfSubAcc.setName("txtfSubAcc");
        txtfSubAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfSubAccActionPerformed(evt);
            }
        });
        txtfSubAcc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfSubAccFocusLost(evt);
            }
        });
        txtfSubAcc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfSubAccKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfSubAccKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfSubAccKeyTyped(evt);
            }
        });

        d_lblAccNo.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        d_lblAccNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d_lblAccNo.setText("เลขที่บัญชี");
        d_lblAccNo.setName("d_lblAccNo");

        txtfAccNo.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txtfAccNo.setName("txtfAccNo");
        txtfAccNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfAccNoActionPerformed(evt);
            }
        });
        txtfAccNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfAccNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfAccNoFocusLost(evt);
            }
        });
        txtfAccNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfAccNoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfAccNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfAccNoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(d_lblBankCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(d_lblBankName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(d_lblAccNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtfBankCode, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(d_lblSubAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtfSubAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtfBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d_lblBankCode)
                    .addComponent(txtfBankCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_lblSubAcc)
                    .addComponent(txtfSubAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_lblBankName))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_lblAccNo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblBank.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        tblBank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bank_Code", "Sub Acc", "ชื่อธนาคาร", "เลขที่บัญชีธนาคาร"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBank.setName("tblBank");
        tblBank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblBankMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblBank);
        tblBank.getColumnModel().getColumn(0).setPreferredWidth(150);
        tblBank.getColumnModel().getColumn(1).setPreferredWidth(150);
        tblBank.getColumnModel().getColumn(2).setPreferredWidth(900);
        tblBank.getColumnModel().getColumn(3).setPreferredWidth(300);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCancel.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cancel-icon.png"))); // NOI18N
        btnCancel.setText("ยกเลิก");
        btnCancel.setFocusable(false);
        btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancel.setIconTextGap(0);
        btnCancel.setName("db_btnCancel");
        btnCancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save-icon.png"))); // NOI18N
        btnSave.setText("บันทึกข้อมูล");
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setIconTextGap(0);
        btnSave.setName("db_btnSave");
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDetete.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btnDetete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete-icons.png"))); // NOI18N
        btnDetete.setText("ลบข้อมูล");
        btnDetete.setFocusable(false);
        btnDetete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDetete.setIconTextGap(0);
        btnDetete.setName("db_btnDetete");
        btnDetete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDetete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeteteActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LogOut-icon.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setIconTextGap(0);
        btnExit.setName("db_btnExit");
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        db_btnPrint.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Printer-icon.png"))); // NOI18N
        db_btnPrint.setText("พิมม์");
        db_btnPrint.setFocusable(false);
        db_btnPrint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        db_btnPrint.setIconTextGap(0);
        db_btnPrint.setName("db_btnPrint");
        db_btnPrint.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        db_btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_btnPrintActionPerformed(evt);
            }
        });

        db_btnExel.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        db_btnExel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Excel-icon.png"))); // NOI18N
        db_btnExel.setText("Exel File");
        db_btnExel.setFocusable(false);
        db_btnExel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        db_btnExel.setIconTextGap(0);
        db_btnExel.setName("db_btnExel");
        db_btnExel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        db_btnExel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db_btnExelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDetete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 327, Short.MAX_VALUE)
                .addComponent(db_btnExel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(db_btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnDetete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(db_btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(db_btnExel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        menuFunc.setText("ฟังก์ชั่น");
        menuFunc.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        menuFunc.setName("menuFunc"); // NOI18N

        menuCancel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menuCancel.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menuCancel.setText("ยกเลิก");
        menuCancel.setName("menuCancel"); // NOI18N
        menuCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCancelActionPerformed(evt);
            }
        });
        menuFunc.add(menuCancel);

        menuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSave.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menuSave.setText("บันทึกข้อมูล");
        menuSave.setName("menuSave"); // NOI18N
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        menuFunc.add(menuSave);

        menuDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuDelete.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menuDelete.setText("ลบข้อมูล");
        menuDelete.setName("menuDelete"); // NOI18N
        menuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeleteActionPerformed(evt);
            }
        });
        menuFunc.add(menuDelete);

        jSeparator1.setName("jSpeparator1"); // NOI18N
        menuFunc.add(jSeparator1);

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuExit.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menuExit.setText("Exit");
        menuExit.setName("menuExit"); // NOI18N
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuFunc.add(menuExit);

        jMenuBar2.add(menuFunc);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-939)/2, (screenSize.height-578)/2, 939, 578);
    }// </editor-fold>//GEN-END:initComponents
private void checkuserconfig() {
        //MenuName = Mast1
        UserLogin userrec = UserLogin.userlogin;
        if (userrec.getMast11().equals("1")) {
            btnSave.setEnabled(false);
            btnDetete.setEnabled(false);
            menuSave.setEnabled(false);
            menuDelete.setEnabled(false);
        }
        if (userrec.getMast11().equals("2")) {
            btnSave.setEnabled(true);
            btnDetete.setEnabled(false);
            menuSave.setEnabled(true);
            menuDelete.setEnabled(false);
        }
        if (userrec.getMast11().equals("3")) {
            btnSave.setEnabled(true);
            btnDetete.setEnabled(true);
            menuSave.setEnabled(true);
            menuDelete.setEnabled(true);
        }
    }
    private void txtfBankCodeActionPerfrmed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfBankCodeActionPerfrmed

        // TODO add your handling code here:
   }//GEN-LAST:event_txtfBankCodeActionPerfrmed

    private void txtfBankCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfBankCodeFocusLost
        if(!txtfBankCode.getText().equals(""))
        {
            
            txtfSubAcc.requestFocus();
        }

        // TODO add your handling code here:
  }//GEN-LAST:event_txtfBankCodeFocusLost

    private void txtfBankCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfBankCodeKeyPressed

     if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(!txtfBankCode.getText().equals(""))
        {
                txtfSubAcc.requestFocus();
        }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtfBankCodeKeyPressed

    private void txtfBankCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfBankCodeKeyReleased



        // TODO add your handling code here:
 }//GEN-LAST:event_txtfBankCodeKeyReleased

    private void txtfBankCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfBankCodeKeyTyped
        if (txtfBankCode.getText().length() >= 8) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfBankCodeKeyTyped

    private void txtfBankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfBankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfBankNameActionPerformed

    private void txtfBankNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfBankNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtfAccNo.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfBankNameKeyPressed

    private void tblBankMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBankMouseReleased
        if (evt.getClickCount() == 2) {
            int index = tblBank.getSelectedRow();
            String code = tblBank.getValueAt(index, 0).toString();
            String sub = tblBank.getValueAt(index, 1).toString();
            String name = tblBank.getValueAt(index, 2).toString();
            String acc = tblBank.getValueAt(index, 3).toString();
            if (txtfBankCode.getText().trim().equals("")&&txtfSubAcc.getText().trim().equals("")) {
                txtfBankCode.setText(code);
                txtfBankName.setText(name);
                txtfSubAcc.setText(sub);
                txtfAccNo.setText(acc);
            } else if (!txtfSubAcc.getText().equals("")&&!txtfBankCode.getText().equals("")&&!txtfSubAcc.getText().equals(sub)||!txtfBankCode.getText().equals(code)) {
                int confirm = JOptionPane.showConfirmDialog(this, "คุณมีการเพิ่มหรือแก้ไขข้อมูลอยู่ คุณต้องการยกเลิกการเพิ่มหรือแก้ไขข้อมูลนั้นหรือไม่", "Confirm", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                       txtfBankCode.setText(code);
                       txtfBankName.setText(name);
                       txtfSubAcc.setText(sub);
                       txtfAccNo.setText(acc);
                }
            }
            setFocus(true);
            txtfBankName.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBankMouseReleased

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (!txtfBankCode.getText().equals("")) {
            btnsave();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeteteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeteteActionPerformed
        if (!txtfBankCode.getText().trim().equals("") &&!txtfSubAcc.getText().trim().equals("") && chkdata(txtfBankCode.getText(),txtfSubAcc.getText())&&txtfBankName.isFocusable()) {
            delete();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeteteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void db_btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_btnPrintActionPerformed
        Map parm = new HashMap();
        JRBeanCollectionDataSource ds = null;
        ds = new JRBeanCollectionDataSource(report.databean4Field.getCrAccNo());
        parm.put("companyName", lang.getTextCompanyReport());
        parm.put("Reportheader", lang.getTextReport(frmName, "texthead"));

        parm.put("code", lang.getTextReport(frmName, "code"));
        parm.put("name", lang.getTextReport(frmName, "name"));
        parm.put("other1", lang.getTextReport(frmName, "other1"));
        parm.put("other2", lang.getTextReport(frmName, "other2"));
        
        parm.put("totalall", lang.getTextReport(frmName, "totalall"));
        parm.put("branchtxt", lang.getTextReport(frmName, "branchtxt"));
        parm.put("application",new GetApplicationName().getApplicationName());
        parm.put("user", new GetUser().getUser());
        parm.put("currentDate", Format.dateFmtReport.format(new java.util.Date()));
        
        String rptName = "rptcraccno";
        Report rpt = new Report();
        rpt.viewReportbean(rptName, parm,frmName, ds); 
        // TODO add your handling code here:
    }//GEN-LAST:event_db_btnPrintActionPerformed

    private void db_btnExelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db_btnExelActionPerformed
        Export2Excel test = new Export2Excel();
        JFileChooser chooser = new JFileChooser();
        DefaultTableModel dtb = (DefaultTableModel) tblBank.getModel();
        JTableHeader jtb = (JTableHeader) tblBank.getTableHeader();
   
        chooser.setSelectedFile(test.getDefaulepath());
        chooser.setFileFilter(new JRSingleSheetXlsSaveContributor(Locale.ENGLISH, null));
       
        int confirm = chooser.showSaveDialog(this);
            if(confirm == JFileChooser.APPROVE_OPTION)
            {

        File curFile = chooser.getSelectedFile();
        
                if(curFile.exists())
                {
                    int confirm2 = JOptionPane.showConfirmDialog(this, "ข้อมูลนี้มีอยู่แล้ว คุณต้องการบันทึกรายการนี้หรือไม่...?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (confirm2 == JOptionPane.NO_OPTION) {
                        test.setDefaultpath(curFile);
                        db_btnExelActionPerformed(null);
                        
                        return;

                    }
                    
                }
        
        try {
            test.setOutputFile(curFile.toString());
            test.write2single(dtb, jtb);
            test.setDefaultpath(curFile);
        } catch (IOException ex) {
            Logger.getLogger(ShowBranchOfArea.class.getName()).log(Level.SEVERE, null, ex);
        } catch (WriteException ex) {
            Logger.getLogger(ShowBranchOfArea.class.getName()).log(Level.SEVERE, null, ex);
        }
            }
            
           
            
        // TODO add your handling code here:
    }//GEN-LAST:event_db_btnExelActionPerformed

    private void txtfSubAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfSubAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfSubAccActionPerformed

    private void txtfSubAccFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfSubAccFocusLost
        if(txtfBankCode.getText().equals(""))
        {
            txtfBankCode.requestFocus();
        }
        else if(!txtfSubAcc.getText().equals(""))
        {
            enter();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfSubAccFocusLost

    private void txtfSubAccKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfSubAccKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(txtfBankCode.getText().equals(""))
            {
                txtfBankCode.requestFocus();
            }
            else if(!txtfSubAcc.getText().equals(""))
            {
                setFocus(true);
                txtfBankName.requestFocus();
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtfSubAccKeyPressed

    private void txtfSubAccKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfSubAccKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfSubAccKeyReleased

    private void txtfSubAccKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfSubAccKeyTyped
        if (txtfSubAcc.getText().length() >= 5) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfSubAccKeyTyped

    private void txtfAccNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfAccNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfAccNoActionPerformed

    private void txtfAccNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfAccNoFocusLost
        txtfAccNo.select(0,0);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfAccNoFocusLost

    private void txtfAccNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfAccNoKeyPressed
 if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
          txtfBankName.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtfAccNoKeyPressed

    private void txtfAccNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfAccNoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfAccNoKeyReleased

    private void txtfAccNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfAccNoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfAccNoKeyTyped

    private void menuCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCancelActionPerformed
        btnCancelActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCancelActionPerformed

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed
        btnSaveActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSaveActionPerformed

    private void menuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeleteActionPerformed
        btnDeteteActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDeleteActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        btnExitActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuExitActionPerformed

    private void txtfBankNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfBankNameFocusGained
        txtfBankName.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfBankNameFocusGained

    private void txtfAccNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfAccNoFocusGained
        txtfAccNo.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfAccNoFocusGained

    private void txtfBankNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfBankNameFocusLost
        txtfBankName.select(0,0);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfBankNameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrAccNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrAccNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrAccNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrAccNo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CrAccNo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDetete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel d_lblAccNo;
    private javax.swing.JLabel d_lblBankCode;
    private javax.swing.JLabel d_lblBankName;
    private javax.swing.JLabel d_lblSubAcc;
    private javax.swing.JButton db_btnExel;
    private javax.swing.JButton db_btnPrint;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuCancel;
    private javax.swing.JMenuItem menuDelete;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuFunc;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JTable tblBank;
    private javax.swing.JTextField txtfAccNo;
    private javax.swing.JTextField txtfBankCode;
    private javax.swing.JTextField txtfBankName;
    private javax.swing.JTextField txtfSubAcc;
    // End of variables declaration//GEN-END:variables
public boolean ChkValidEnter(String Name , int length)
{
    boolean chk = true;
    if(Name.equals("Sub Acc"))
    {
    if(txtfSubAcc.getText().equals(""))
    {
        JOptionPane.showMessageDialog(this, "กรุณากำหนด "+Name+" ก่อน");
        chk = false;
        txtfSubAcc.requestFocus();
    }
    else if(txtfSubAcc.getText().length()>length)
    {
         JOptionPane.showMessageDialog(this, "กำหนด "+Name+" ไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน "+length+" ตัวอักษร)");
        chk = false;
        txtfSubAcc.requestFocus();
    }
    else if(txtfSubAcc.getText().trim().equals(""))
    {
         JOptionPane.showMessageDialog(this, "กรุณากำหนด "+Name+" ให้ถูกต้อง");
        chk = false;
        txtfSubAcc.requestFocus();
        txtfSubAcc.setText("");
    }
//    txtfSubAcc.setBackground(java.awt.Color.white);
//    txtfSubAcc.setEditable(true);
    }
    else{
    if(txtfBankCode.getText().equals(""))
    {
        JOptionPane.showMessageDialog(this, "กรุณากำหนด "+Name+" ก่อน");
        chk = false;
        txtfBankCode.requestFocus();
    }
    else if(txtfBankCode.getText().length()>length)
    {
         JOptionPane.showMessageDialog(this, "กำหนด "+Name+" ไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน "+length+" ตัวอักษร)");
        chk = false;
        txtfBankCode.requestFocus();
    }
    else if(txtfBankCode.getText().trim().equals(""))
    {
         JOptionPane.showMessageDialog(this, "กรุณากำหนด "+Name+" ให้ถูกต้อง");
        chk = false;
        txtfBankCode.requestFocus();
        txtfBankCode.setText("");
    }
//    txtfBankCode.setBackground(java.awt.Color.white);
//    txtfBankCode.setEditable(true);
    }
    return chk;
}
public void showdataintb()
{
    stmt = null;
    ResultSet rs = null;
    
   
    tbBranctype = (DefaultTableModel) tblBank.getModel();
     int cnt = tbBranctype.getRowCount();
        if (cnt > 0) {
            for (int i = 0; i < cnt; i++) {
                tbBranctype.removeRow(0);
            }
        }
    try {
        stmt = (Statement) dbUtility.con.createStatement();
        String sql = "select * from craccno order by bank_code";
        rs = stmt.executeQuery(sql);
        while(rs.next())
        {
            if(!db.Char_Set.equalsIgnoreCase("utf-8"))
            {
            tbBranctype.addRow(new Object[]{cvth.ASCII2Unicode(rs.getString("bank_code")),
                                            cvth.ASCII2Unicode(rs.getString("bank_sub")),
                                            cvth.ASCII2Unicode(rs.getString("bank_name")),
                                            cvth.ASCII2Unicode(rs.getString("bank_acc"))
                                            });
            }
            else
            {
            tbBranctype.addRow(new Object[]{rs.getString("bank_code"),
                                            rs.getString("bank_sub"),
                                            rs.getString("bank_name"),
                                            rs.getString("bank_acc")
                                           });
            }
        }
    } catch (Exception e) {
    }
}
public void clear()
{
    txtfBankCode.setText("");
    txtfBankName.setText("");
    txtfSubAcc.setText("");
    txtfAccNo.setText("");
    setFocus(false);
    txtfBankCode.requestFocus();
    
}
public boolean validateSave()
{
    boolean chk = true;
        if (!txtfBankName.isFocusable()) {
        chk = false;
        }
        else if(ChkValidEnter("Sub Acc", 5)&&ChkValidEnter("Bank Code", 8))
        {
        if(txtfBankName.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(this, "กรุณากำหนดชื่อธนาคารให้ถูกต้อง");
            chk = false;
            txtfBankName.requestFocus();
            txtfBankName.setEditable(true);
        }
        else if(txtfBankName.getText().length()>50)
        {
            JOptionPane.showMessageDialog(this, "กำหนดชื่อธนาคารไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 50 ตัวอักษร)");
            chk = false;
            txtfBankName.requestFocus();
        }
        else if(txtfAccNo.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(this, "กรุณากำหนดเลขที่บัญชีให้ถูกต้อง");
            chk = false;
            txtfAccNo.requestFocus();
            txtfAccNo.setEditable(true);
        }
        else if(txtfAccNo.getText().length()>15)
        {
            JOptionPane.showMessageDialog(this, "กำหนดเลขที่บัญชีไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 15 ตัวอักษร)");
            chk = false;
            txtfAccNo.requestFocus();
        }
        }
        else
        {
        chk = false;
        }
  
    
    return chk;
}
public boolean chkdata(String pk,String pk2)
{
    boolean chk= false;
    ResultSet rs = null;
    try {
        if(!db.Char_Set.equalsIgnoreCase("utf-8"))
        {
        stmt = (Statement) db.con.createStatement();
        String sql = "select * from craccno where bank_code ='"+cvth.Unicode2ASCII(pk)+"' and bank_sub ='"+cvth.Unicode2ASCII(pk2)+"'";
        rs = stmt.executeQuery(sql);
        if(rs.next())
        {
            chk = true;
        }
        }
        else
        {
        stmt = (Statement) db.con.createStatement();
        String sql = "select * from craccno where bank_code ='"+pk+"' and bank_sub ='"+pk2+"'";
        rs = stmt.executeQuery(sql);
        if(rs.next())
        {
            chk = true;
        }
        }
    } catch (Exception e) {
        
    }
    return chk;
}
public void btnsave()
{
    if(validateSave())
    {
        if(chkdata(txtfBankCode.getText(),txtfSubAcc.getText()))
        {
            
            try {
            if(!db.Char_Set.equalsIgnoreCase("utf-8"))
            {
               stmt = (Statement) db.con.createStatement();
               String sql = "Update craccno set bank_name=?,bank_acc = ? where bank_code = ? and bank_sub = ?";
               PreparedStatement prm = (PreparedStatement) db.con.prepareStatement(sql);
               prm.setString(1, cvth.Unicode2ASCII(txtfBankName.getText()));
               prm.setString(2, cvth.Unicode2ASCII(txtfAccNo.getText()));
               prm.setString(3, cvth.Unicode2ASCII(txtfBankCode.getText()));
               prm.setString(4, cvth.Unicode2ASCII(txtfSubAcc.getText()));
               prm.executeUpdate();
            }
            else
            {
               stmt = (Statement) db.con.createStatement();
               String sql = "Update craccno set bank_name=?,bank_acc = ? where bank_code = ? and bank_sub = ?";
               PreparedStatement prm = (PreparedStatement) db.con.prepareStatement(sql);
               prm.setString(1, txtfBankName.getText());
               prm.setString(2, txtfAccNo.getText());
               prm.setString(2, txtfBankCode.getText());
               prm.setString(2, txtfSubAcc.getText());
               prm.executeUpdate();
                   
            }
               stmt.close();
               clear();
               
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Update Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            try {
                  if(!db.Char_Set.equalsIgnoreCase("utf-8"))
            {
               stmt = (Statement) db.con.createStatement();
               String sql = "Insert into craccno (bank_code,bank_name,bank_sub,bank_acc) values(?,?,?,?)";
               PreparedStatement prm = (PreparedStatement) db.con.prepareStatement(sql);
               prm.setString(2, cvth.Unicode2ASCII(txtfBankName.getText()));
               prm.setString(1, cvth.Unicode2ASCII(txtfBankCode.getText().trim()));
               prm.setString(3, cvth.Unicode2ASCII(txtfSubAcc.getText().trim()));
               prm.setString(4, cvth.Unicode2ASCII(txtfAccNo.getText()));
               prm.executeUpdate();
            }
            else
            {
               stmt = (Statement) db.con.createStatement();
               String sql = "Insert into craccno (bank_code,bank_name,bank_sub,bank_acc) values(?,?,?,?)";
               PreparedStatement prm = (PreparedStatement) db.con.prepareStatement(sql);
               prm.setString(2, txtfBankName.getText());
               prm.setString(1, txtfBankCode.getText().trim());
               prm.setString(3, txtfSubAcc.getText().trim());
               prm.setString(4, txtfAccNo.getText());
               prm.executeUpdate();
            }
               stmt.close();
               clear();
               
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Insert Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        showdataintb();
    }
}
public void enter()
{
    ResultSet rs = null;
    try {
        if(!db.Char_Set.equalsIgnoreCase("utf-8"))
            {
        stmt = (Statement) db.con.createStatement();
        String sql = "select * from craccno where bank_code ='"+cvth.Unicode2ASCII(txtfBankCode.getText())+"' and bank_sub='"+cvth.Unicode2ASCII(txtfSubAcc.getText())+"'";
        rs = stmt.executeQuery(sql);
        if(rs.next())
        {
            txtfBankName.setText(cvth.ASCII2Unicode(rs.getString("bank_name")));
            txtfAccNo.setText(cvth.ASCII2Unicode(rs.getString("bank_acc")));
            setFocus(true);
            txtfBankName.requestFocus();
        }
        else {
            setFocus(true);
            txtfBankName.requestFocus();
        }
            }
        else
        {
              stmt = (Statement) db.con.createStatement();
         String sql = "select * from craccno where bank_code ='"+txtfBankCode.getText()+"' and bank_sub='"+txtfSubAcc.getText()+"'";
        rs = stmt.executeQuery(sql);
        if(rs.next())
        {
            txtfBankName.setText(rs.getString("bank_name"));
            txtfAccNo.setText(rs.getString("bank_acc"));
            setFocus(true);
            txtfBankName.requestFocus();
        }
        else {
            setFocus(true);
            txtfBankName.requestFocus();
        }
        }
    } catch (Exception e) {
        
    }
}
public void delete()
{
    ResultSet rs = null;
    try {
        int confirm = JOptionPane.showConfirmDialog(this, "คุณต้องการลบข้อมูลรายการนี้หรือไม่...?", "Confirm", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                     if(!db.Char_Set.equalsIgnoreCase("utf-8"))
                    {
                    stmt = (Statement) db.con.createStatement();
                    String sql = "Delete from craccno where bank_code=? and bank_sub =?";
                    PreparedStatement prm = (PreparedStatement) db.con.prepareStatement(sql);
                    prm.setString(1, cvth.Unicode2ASCII(txtfBankCode.getText()));
                    prm.setString(2, cvth.Unicode2ASCII(txtfSubAcc.getText()));
                    prm.executeUpdate();
                    }
                    else
                    {
        stmt = (Statement) db.con.createStatement();
               String sql = "Delete from craccno where bank_code=? and bank_sub =?";
               PreparedStatement prm = (PreparedStatement) db.con.prepareStatement(sql);
               prm.setString(1, txtfBankCode.getText());
               prm.setString(1, txtfSubAcc.getText());
               prm.executeUpdate();
               stmt.close();
                    }
               clear();
               showdataintb();
                }
                
       
    } catch (Exception e) {
        
    }
}
    private void setFocus(boolean chk)
    {
  
    txtfAccNo.setFocusable(chk);
    txtfBankName.setFocusable(chk);
        if(chk==false)
        {
        txtfSubAcc.setFocusable(true);
        txtfSubAcc.setBackground(Color.WHITE);
        txtfBankCode.setFocusable(true);
        txtfBankCode.setBackground(Color.WHITE);
        
        }
        else
        {
        txtfSubAcc.setFocusable(false);
        txtfSubAcc.setBackground(new java.awt.Color(255, 246, 143));
        txtfBankCode.setFocusable(false);
        txtfBankCode.setBackground(new java.awt.Color(255, 246, 143));
        }
    }
}
