/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package masterfile;

import borfunction.GetApplicationName;
import borfunction.GetUser;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import dbutility.dbUtility;
import frmlist.BrowserBankFile;
import frmlist.listCrAccNo;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import report.Report;
import utilititiesfunction.*;

/**
 *
 * @author shady
 */
public class CreditCardSetup extends javax.swing.JFrame {

    dbUtility db = new dbUtility();
    private Statement stmt;
    DefaultTableModel tbCreditCardSetup;
    String frmName = "creditcardsetup";
    private Color colorEnable = new Color(255, 246, 143);
    private Color colorDisable2 = new Color(216, 215, 214);
    ThaiUtilities cvth = new ThaiUtilities();
    getLanguage lang = new getLanguage();
    /**
     * Creates new form branchsetting
     */
    public CreditCardSetup() {
        initComponents();
        checkuserconfig();
        db.dbconnect();
        try {
            stmt = (Statement) dbUtility.con.createStatement();
        } catch (Exception e) {
        }
        tbCreditCardSetup = (DefaultTableModel) tblcreditcard.getModel();
        tblcreditcard.setShowGrid(true);
        tblcreditcard.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblcreditcard.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblcreditcard.setRowSelectionAllowed(true);
        tblcreditcard.setBackground(java.awt.Color.WHITE);
        tblcreditcard.setGridColor(java.awt.Color.gray);
        JTableHeader header = tblcreditcard.getTableHeader();
        header.setFont(new java.awt.Font("Norasi", java.awt.Font.BOLD, 14));
//        tblcreditcard.setFont(new java.awt.Font("Norasi", java.awt.Font.BOLD, 14));
        tblcreditcard.setRowHeight(25);
        tblcreditcard.setAutoCreateRowSorter(true);
        showdataintb();
        clear();

        
        lang.setText(frmName, this, lang.getChklang());

        //Setting btt
        //ชื่อปุ่ม.setfont.getfontsize
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcreditcard = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        t_creditacc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t_subacc = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        rd_yes = new javax.swing.JRadioButton();
        rd_no = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t_chargecredit = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        t_discountcredit = new javax.swing.JFormattedTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        t_bankcode2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t_bankname2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        t_account = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnbank2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        t_subacc2 = new javax.swing.JTextField();
        t_service = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t_creditcode = new javax.swing.JTextField();
        t_creditname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t_bankcode = new javax.swing.JTextField();
        t_bankname = new javax.swing.JTextField();
        btnbank1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuFunc = new javax.swing.JMenu();
        menuCancel = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuDelete = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNew.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Add-icon.png"))); // NOI18N
        btnNew.setText("เพิ่มรายการ");
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setName("DBbtnadd"); // NOI18N
        btnNew.setRequestFocusEnabled(false);
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cancel-icon.png"))); // NOI18N
        btnCancel.setText("ยกเลิก");
        btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancel.setName("DBbtncancle"); // NOI18N
        btnCancel.setRequestFocusEnabled(false);
        btnCancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save-icon.png"))); // NOI18N
        btnSave.setText("บันทึกข้อมูล");
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setName("DBbtnsave"); // NOI18N
        btnSave.setRequestFocusEnabled(false);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete-icons.png"))); // NOI18N
        btnDelete.setText("ลบข้อมูล");
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setName("DBbtndel"); // NOI18N
        btnDelete.setRequestFocusEnabled(false);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Printer-icon.png"))); // NOI18N
        jButton6.setText("พิมพ์");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setName("DBbtnprint"); // NOI18N
        jButton6.setRequestFocusEnabled(false);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LogOut-icon.png"))); // NOI18N
        jButton7.setText("ออก");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setName("DBbtnexit"); // NOI18N
        jButton7.setRequestFocusEnabled(false);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        tblcreditcard.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        tblcreditcard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ธนาคาร", "รหัสบัตร", "ชื่อบัตร / รายการ", "หักส่วนลด", "Charge", "ใส่หมายเลขบัตร"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblcreditcard.setFocusable(false);
        tblcreditcard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblcreditcardMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblcreditcard);
        tblcreditcard.getColumnModel().getColumn(0).setPreferredWidth(60);
        tblcreditcard.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblcreditcard.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblcreditcard.getColumnModel().getColumn(3).setPreferredWidth(70);
        tblcreditcard.getColumnModel().getColumn(4).setPreferredWidth(60);
        tblcreditcard.getColumnModel().getColumn(5).setPreferredWidth(70);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Norasi", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("กำหนดรายการบัตรเครดิต (Credit Card Setup)");
        jLabel12.setName("LBcreditcardsetup"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Credit_Acc");
        jLabel4.setName("D_creditacc"); // NOI18N

        t_creditacc.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_creditacc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_creditaccFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_creditaccFocusLost(evt);
            }
        });
        t_creditacc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_creditaccKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Sub_Acc");
        jLabel5.setName("D_subacc"); // NOI18N

        t_subacc.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_subacc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_subaccFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_subaccFocusLost(evt);
            }
        });
        t_subacc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_subaccKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_creditacc, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t_subacc, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t_creditacc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(t_subacc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(rd_yes);
        rd_yes.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        rd_yes.setText("ใช่");
        rd_yes.setName("D_yes"); // NOI18N

        buttonGroup1.add(rd_no);
        rd_no.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        rd_no.setSelected(true);
        rd_no.setText("ไม่");
        rd_no.setName("D_no"); // NOI18N

        jLabel14.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel14.setText("กำหนดให้รับบัตรเครดิตด้วยหรือไม่");
        jLabel14.setName("D_setrecredit"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(rd_yes)
                .addGap(33, 33, 33)
                .addComponent(rd_no)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_yes)
                    .addComponent(jLabel14)
                    .addComponent(rd_no))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel6.setText("จำนวน % Charge เมื่อรับชำระด้วยบัตรเครดิต");
        jLabel6.setName("D_numpercharge"); // NOI18N

        t_chargecredit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        t_chargecredit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t_chargecredit.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_chargecredit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_chargecreditFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_chargecreditFocusLost(evt);
            }
        });
        t_chargecredit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_chargecreditKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel7.setText("จำนวน % หักส่วนลดเมื่อรับชำระด้วยบัตรเครดิต");
        jLabel7.setName("D_numperdiscount"); // NOI18N

        t_discountcredit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        t_discountcredit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t_discountcredit.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_discountcredit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_discountcreditFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_discountcreditFocusLost(evt);
            }
        });
        t_discountcredit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_discountcreditKeyPressed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Bank_Code");
        jLabel8.setName("D_bankcode"); // NOI18N

        t_bankcode2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_bankcode2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_bankcode2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_bankcode2FocusLost(evt);
            }
        });
        t_bankcode2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_bankcode2KeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("ชื่อธนาคาร");
        jLabel9.setName("D_bankname"); // NOI18N

        t_bankname2.setBackground(new java.awt.Color(249, 252, 186));
        t_bankname2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_bankname2.setFocusable(false);
        t_bankname2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_bankname2KeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("เลขบัญชี");
        jLabel10.setName("D_acccode"); // NOI18N

        t_account.setBackground(new java.awt.Color(249, 252, 186));
        t_account.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_account.setFocusable(false);
        t_account.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_accountKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("ค่าธรรมเนียม");
        jLabel11.setName("D_charge"); // NOI18N

        btnbank2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Windows-Magnifier-icon.png"))); // NOI18N
        btnbank2.setFocusable(false);
        btnbank2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbank2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Sub_Acc");
        jLabel13.setName("D_subacc2"); // NOI18N

        t_subacc2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_subacc2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_subacc2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_subacc2FocusLost(evt);
            }
        });
        t_subacc2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_subacc2KeyPressed(evt);
            }
        });

        t_service.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        t_service.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        t_service.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_service.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_serviceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_serviceFocusLost(evt);
            }
        });
        t_service.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_serviceKeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("%");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_bankcode2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbank2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(t_subacc2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_bankname2))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_account, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_service, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel15)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(t_subacc2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnbank2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(t_bankcode2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(t_bankname2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(t_account, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(t_service, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addContainerGap())))
        );

        jPanel7.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel1.setText("รหัสบัตรเครดิต");
        jLabel1.setName("D_creditcode"); // NOI18N

        t_creditcode.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_creditcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_creditcodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_creditcodeFocusLost(evt);
            }
        });
        t_creditcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_creditcodeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_creditcodeKeyTyped(evt);
            }
        });

        t_creditname.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_creditname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_creditnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_creditnameFocusLost(evt);
            }
        });
        t_creditname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_creditnameKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel2.setText("ชื่อบัตรเครดิต");
        jLabel2.setName("D_creditname"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel3.setText("รหัสธนาคารเจ้าของบัตร");
        jLabel3.setName("D_mybankcode"); // NOI18N

        t_bankcode.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_bankcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_bankcodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_bankcodeFocusLost(evt);
            }
        });
        t_bankcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_bankcodeKeyPressed(evt);
            }
        });

        t_bankname.setBackground(new java.awt.Color(249, 252, 186));
        t_bankname.setEditable(false);
        t_bankname.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_bankname.setFocusable(false);
        t_bankname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_banknameKeyPressed(evt);
            }
        });

        btnbank1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Windows-Magnifier-icon.png"))); // NOI18N
        btnbank1.setFocusable(false);
        btnbank1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbank1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t_creditname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(t_bankcode, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_bankname)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbank1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(t_creditcode, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(t_creditcode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t_creditname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(t_bankname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_bankcode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnbank1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel16.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("%");

        jLabel17.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("%");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(t_discountcredit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(t_chargecredit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)))
                        .addGap(9, 9, 9))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(t_chargecredit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(t_discountcredit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuFunc.setText("ฟังก์ชั่น");
        menuFunc.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        menuFunc.setName("menuFunc"); // NOI18N

        menuCancel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menuCancel.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menuCancel.setText("ยกเลิก");
        menuCancel.setName("menuCancel"); // NOI18N
        menuCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCancelActionPerformed(evt);
            }
        });
        menuFunc.add(menuCancel);

        menuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSave.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menuSave.setText("บันทึกข้อมูล");
        menuSave.setName("menuSave"); // NOI18N
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        menuFunc.add(menuSave);

        menuDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuDelete.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menuDelete.setText("ลบข้อมูล");
        menuDelete.setName("menuDelete"); // NOI18N
        menuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeleteActionPerformed(evt);
            }
        });
        menuFunc.add(menuDelete);

        jSeparator1.setName("jSpeparator1"); // NOI18N
        menuFunc.add(jSeparator1);

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuExit.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menuExit.setText("Exit");
        menuExit.setName("menuExit"); // NOI18N
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuFunc.add(menuExit);

        jMenuBar2.add(menuFunc);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1024)/2, (screenSize.height-768)/2, 1024, 768);
    }// </editor-fold>//GEN-END:initComponents
private void checkuserconfig() {
        //MenuName = Mast1
        UserLogin userrec = UserLogin.userlogin;
        if (userrec.getMast17().equals("1")) {
            btnNew.setEnabled(false);
            btnSave.setEnabled(false);
            btnDelete.setEnabled(false);
            //menuNew.setEnabled(false);
            menuSave.setEnabled(false);
            menuDelete.setEnabled(false);
        }
        if (userrec.getMast17().equals("2")) {
            btnNew.setEnabled(true);
            btnSave.setEnabled(true);
            btnDelete.setEnabled(false);
            //menuNew.setEnabled(true);
            menuSave.setEnabled(true);
            menuDelete.setEnabled(false);
        }
        if (userrec.getMast17().equals("3")) {
            btnNew.setEnabled(true);
            btnSave.setEnabled(true);
            btnDelete.setEnabled(true);
            //menuNew.setEnabled(true);
            menuSave.setEnabled(true);
            menuDelete.setEnabled(true);
        }
    }
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        clear();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tblcreditcardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcreditcardMouseReleased

        if (evt.getClickCount() == 2) {
            int index = tblcreditcard.getSelectedRow();
            String creditcode = tblcreditcard.getValueAt(index, 1).toString();
            if (t_creditcode.getText().equals("")) {
                if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                    GetData(cvth.Unicode2ASCII(creditcode));
                } else {
                    GetData(creditcode);
                }
            } else if (!t_creditcode.getText().equals(creditcode)) {
                int confirm = JOptionPane.showConfirmDialog(this, "คุณมีการเพิ่มหรือแก้ไขข้อมูลอยู่ คุณต้องการยกเลิกการเพิ่มหรือแก้ไขข้อมูลนั้นหรือไม่", "Confirm", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
//                    GetData(creditcode);
                    if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                        GetData(cvth.Unicode2ASCII(creditcode));
                    } else {
                        GetData(creditcode);
                    }
                }
            }
            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tblcreditcardMouseReleased

    private void t_creditcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_creditcodeKeyPressed


        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!t_creditcode.getText().equals("")) {
                
                    setActive();
                t_creditname.requestFocus();
            }
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_creditcodeKeyPressed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed

        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewActionPerformed

    private void t_creditnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_creditnameKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_bankcode.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_creditnameKeyPressed

    private void t_bankcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_bankcodeKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_creditacc.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            btnbank();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_bankcodeKeyPressed

    private void t_creditaccKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_creditaccKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_subacc.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_creditaccKeyPressed

    private void t_banknameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_banknameKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_creditacc.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_banknameKeyPressed

    private void t_subaccKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_subaccKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_chargecredit.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_subaccKeyPressed

    private void t_chargecreditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_chargecreditKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_discountcredit.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_chargecreditKeyPressed

    private void t_discountcreditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_discountcreditKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_bankcode2.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_discountcreditKeyPressed

    private void t_bankcode2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_bankcode2KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_subacc2.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            btnbank2();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_bankcode2KeyPressed

    private void t_subacc2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_subacc2KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_service.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_subacc2KeyPressed

    private void t_bankname2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_bankname2KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_account.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_bankname2KeyPressed

    private void t_accountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_accountKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_service.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_accountKeyPressed

    private void t_serviceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_serviceKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_creditname.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_serviceKeyPressed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        if (!t_creditcode.getText().trim().equals("")&&chkdata(t_creditcode.getText())&&t_creditname.isFocusable()) {
            delete();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (!t_creditcode.getText().trim().equals("")) {
            btnsave();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void t_creditcodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_creditcodeKeyTyped

        if (t_creditcode.getText().length() >= 8) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_creditcodeKeyTyped

    private void t_bankcodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_bankcodeFocusLost
        
        GetDataBank(t_bankcode.getText());
        t_bankcode.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_bankcodeFocusLost

    private void t_bankcode2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_bankcode2FocusLost
        t_bankcode2.select(0, 0);
        //        if(!t_bankcode2.getText().equals("")&&!t_subacc2.getText().equals(""))
//        {
//            GetDataBank2(t_bankcode2.getText(), t_subacc2.getText());
//        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_bankcode2FocusLost

    private void btnbank1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbank1ActionPerformed
        
        btnbank();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbank1ActionPerformed

    private void btnbank2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbank2ActionPerformed

        btnbank2();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbank2ActionPerformed

    private void t_subacc2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_subacc2FocusLost
        if(t_bankcode2.getText().equals("")&&t_subacc2.getText().equals(""))
        {}
        else
        {
        if(!t_bankcode2.getText().equals(""))
        {
        GetDataBank2(t_bankcode2.getText(),t_subacc2.getText());
        }
        else
        {
            
                t_bankcode2.requestFocus();
            
        }
        }
        t_subacc2.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_subacc2FocusLost

    private void menuCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCancelActionPerformed
        //jButton2ActionPe(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCancelActionPerformed

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed
        //jButton3ActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSaveActionPerformed

    private void menuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeleteActionPerformed
        //jButton4ActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDeleteActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        jButton7ActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuExitActionPerformed

    private void t_creditcodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_creditcodeFocusGained
        
        // TODO add your handling code here:
    }//GEN-LAST:event_t_creditcodeFocusGained

    private void t_creditcodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_creditcodeFocusLost
        if (!t_creditcode.getText().equals("")) {
                
                    GetData(t_creditcode.getText());
                
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_creditcodeFocusLost

    private void t_creditnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_creditnameFocusGained
        t_creditname.setText(t_creditname.getText());
        t_creditname.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_creditnameFocusGained

    private void t_bankcodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_bankcodeFocusGained
        t_bankcode.setText(t_bankcode.getText());
        t_bankcode.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_bankcodeFocusGained

    private void t_creditaccFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_creditaccFocusGained
        t_creditacc.setText(t_creditacc.getText());
        t_creditacc.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_creditaccFocusGained

    private void t_subaccFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_subaccFocusGained
        t_subacc.setText(t_subacc.getText());
        t_subacc.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_subaccFocusGained

    private void t_chargecreditFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_chargecreditFocusGained
        t_chargecredit.setText(t_chargecredit.getText());
        t_chargecredit.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_chargecreditFocusGained

    private void t_bankcode2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_bankcode2FocusGained
        t_bankcode2.setText(t_bankcode2.getText());
        t_bankcode2.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_bankcode2FocusGained

    private void t_subacc2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_subacc2FocusGained
        t_subacc2.setText(t_subacc2.getText());
        t_subacc2.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_subacc2FocusGained

    private void t_serviceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_serviceFocusGained
        t_service.setText(t_service.getText());
        t_service.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_serviceFocusGained

    private void t_creditnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_creditnameFocusLost
        t_creditname.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_creditnameFocusLost

    private void t_creditaccFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_creditaccFocusLost
        t_creditacc.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_creditaccFocusLost

    private void t_subaccFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_subaccFocusLost
        t_subacc.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_subaccFocusLost

    private void t_chargecreditFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_chargecreditFocusLost
        t_chargecredit.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_chargecreditFocusLost

    private void t_discountcreditFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_discountcreditFocusLost
        t_discountcredit.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_discountcreditFocusLost

    private void t_serviceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_serviceFocusLost
        t_service.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_serviceFocusLost

    private void t_discountcreditFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_discountcreditFocusGained
        t_discountcredit.setText(t_discountcredit.getText());
        t_discountcredit.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_discountcreditFocusGained

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        Map parm = new HashMap();
        JRBeanCollectionDataSource ds = null;
        ds = new JRBeanCollectionDataSource(report.dataBeanCreditfile.getCreditFile());
        parm.put("companyName", lang.getTextCompanyReport());
        parm.put("Reportheader", lang.getTextReport(frmName, "texthead"));
        //String test = new String(lang.getTextReport(frmName, "code"));
        
        parm.put("code", lang.getTextReport(frmName, "code"));
        parm.put("name", lang.getTextReport(frmName, "name"));
        parm.put("other1", lang.getTextReport(frmName, "other1"));
        parm.put("other2", lang.getTextReport(frmName, "other2"));
        parm.put("other3", lang.getTextReport(frmName, "other3"));
        parm.put("other4", lang.getTextReport(frmName, "other4"));
        parm.put("other5", lang.getTextReport(frmName, "other5"));
        parm.put("other6", lang.getTextReport(frmName, "other6"));
        parm.put("other7", lang.getTextReport(frmName, "other7"));
        parm.put("other8", lang.getTextReport(frmName, "other8"));
        parm.put("other9", lang.getTextReport(frmName, "other9"));
        parm.put("totalall", lang.getTextReport(frmName, "totalall"));
        parm.put("branchtxt", lang.getTextReport(frmName, "branchtxt"));
        parm.put("application",new GetApplicationName().getApplicationName());
        parm.put("user", new GetUser().getUser());
        parm.put("currentDate", Format.dateFmtReport.format(new java.util.Date()));
        
        String rptName = "rptcreditfile";
        Report rpt = new Report();
        rpt.viewReportbean(rptName, parm,frmName, ds); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        t_creditcode.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditCardSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditCardSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditCardSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditCardSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CreditCardSetup().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnbank1;
    private javax.swing.JButton btnbank2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuCancel;
    private javax.swing.JMenuItem menuDelete;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuFunc;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JRadioButton rd_no;
    private javax.swing.JRadioButton rd_yes;
    private javax.swing.JTextField t_account;
    private javax.swing.JTextField t_bankcode;
    private javax.swing.JTextField t_bankcode2;
    private javax.swing.JTextField t_bankname;
    private javax.swing.JTextField t_bankname2;
    private javax.swing.JFormattedTextField t_chargecredit;
    private javax.swing.JTextField t_creditacc;
    private javax.swing.JTextField t_creditcode;
    private javax.swing.JTextField t_creditname;
    private javax.swing.JFormattedTextField t_discountcredit;
    private javax.swing.JFormattedTextField t_service;
    private javax.swing.JTextField t_subacc;
    private javax.swing.JTextField t_subacc2;
    private javax.swing.JTable tblcreditcard;
    // End of variables declaration//GEN-END:variables

    public void clear() {
        t_creditcode.setText("");
        t_creditcode.setBackground(java.awt.Color.white);
        t_creditcode.requestFocus();
        t_creditcode.setEditable(true);
        t_creditname.setText("");
        t_bankcode.setText("");
        t_bankname.setText("");
        t_creditacc.setText("");
        t_subacc.setText("");
        t_chargecredit.setText("0.00");
        t_discountcredit.setText("0.00");
        t_bankcode2.setText("");
        t_subacc2.setText("");
        t_bankname2.setText("");
        t_account.setText("");
        t_service.setText("0.00");
        rd_yes.isSelected();
        setUnActive();
        t_creditcode.requestFocus();

    }

    private void setActive() {
        setActive(true, colorEnable);
    }

    private void setUnActive() {
        setActive(false, colorDisable2);
    }

    private void setActive(boolean active, Color color) {

        t_creditname.setFocusable(active);
        t_bankcode.setFocusable(active);
        t_creditacc.setFocusable(active);
        t_subacc.setFocusable(active);
        t_chargecredit.setFocusable(active);
        t_discountcredit.setFocusable(active);
        t_bankcode2.setFocusable(active);
        t_subacc2.setFocusable(active);
        //t_bankname2.setFocusable(active);
        //t_account.setFocusable(active);
        t_service.setFocusable(active);
        rd_yes.setFocusable(active);
        rd_no.setFocusable(active);
        btnbank1.setEnabled(active);
        btnbank2.setEnabled(active);
        rd_yes.setEnabled(active);
        rd_no.setEnabled(active);
        
        if(active==false)
        {
        t_creditcode.setFocusable(true);
//        btnbank1.setEnabled(true);
//        btnbank2.setEnabled(true);
        t_creditcode.setBackground(Color.WHITE);
        
        }
        else
        {
        t_creditcode.setFocusable(false);
//        btnbank1.setEnabled(false);
//        btnbank2.setEnabled(false);
        t_creditcode.setBackground(new java.awt.Color(249,252,186));
        
        }
    }

    public void GetData(String Code) {
        String credit = "";
        if (CheckValidEnter()) {
            try {
                String sql = "select * from creditfile where CrCode='" + Code + "'";

                stmt = (Statement) dbUtility.con.createStatement();
                ResultSet rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                        t_creditcode.setText(cvth.ASCII2Unicode(rs.getString("CrCode")));
                        t_creditname.setText(cvth.ASCII2Unicode(rs.getString("CrName")));
                        t_bankcode.setText(cvth.ASCII2Unicode(rs.getString("CrBank")));
                        GetDataBank(t_bankcode.getText());
                        t_creditacc.setText(cvth.ASCII2Unicode(rs.getString("CrAcc")));
                        t_subacc.setText(cvth.ASCII2Unicode(rs.getString("CrSub")));
                        t_chargecredit.setText(rs.getDouble("CrCharge")+"");
                        t_discountcredit.setText(rs.getDouble("CrRedule")+"");
                        t_bankcode2.setText(cvth.ASCII2Unicode(rs.getString("Bank_Code")));
                        
                        t_subacc2.setText(cvth.ASCII2Unicode(rs.getString("Bank_Sub")));
                        GetDataBank2(t_bankcode2.getText(),t_subacc2.getText());
                        t_service.setText((rs.getDouble("Bank_Chg"))+"");
                        credit = rs.getString("CrGetCardNo");
                        if (credit.equals("Y")) {
                            rd_yes.setSelected(true);
                        } else {
                            rd_no.setSelected(true);
                        }
                        
                    } else {
                        t_creditcode.setText(rs.getString("CrCode"));
                        t_creditname.setText(rs.getString("CrName"));
                        t_bankcode.setText(rs.getString("CrBank"));
                        GetDataBank(t_bankcode.getText());
                        t_creditacc.setText(rs.getString("CrAcc"));
                        t_subacc.setText(rs.getString("CrSub"));
                        t_chargecredit.setText(rs.getDouble("CrCharge")+"");
                        t_discountcredit.setText(rs.getDouble("CrRedule")+"");
                        t_bankcode2.setText(rs.getString("Bank_Code"));
                        
                        t_subacc2.setText(rs.getString("Bank_Sub"));
                        GetDataBank2(t_bankcode2.getText(),t_subacc2.getText());
                        t_service.setText((rs.getDouble("Bank_Chg"))+"");
                        credit = rs.getString("CrGetCardNo");
                        if (credit.equals("Y")) {
                            rd_yes.setSelected(true);
                        } else {
                            rd_no.setSelected(true);
                        }
                        
                    }
                } else {
                    t_creditname.requestFocus();
                }
                rs.close();
                stmt.close();
                setActive();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }

    public void GetDataBank(String Code) {
        if (CheckValidBank() & !t_bankcode.getText().trim().equals("")) {
            try {
                String sql = "select * from bankfile where BCode='" + Code + "'";

                stmt = (Statement) dbUtility.con.createStatement();
                ResultSet rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                        t_bankcode.setText(cvth.ASCII2Unicode(rs.getString("BCode")));
                        t_bankname.setText(cvth.ASCII2Unicode(rs.getString("BName")));
                    } else {
                        t_bankcode.setText(rs.getString("BCode"));
                        t_bankname.setText(rs.getString("BName"));
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "คุณกำหนดรหัสธนาคารไม่ถูกต้อง...");
                    t_bankcode.setText("");
                    t_bankname.setText("");
                    t_bankcode.requestFocus();
                }
                rs.close();
                stmt.close();
                setActive();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }

    public void GetDataBank2(String Code,String sub) {
        if (CheckValidBank2() & !t_bankcode2.getText().trim().equals("")) {
            try {
                String sql = "select * from craccno where Bank_Code='" + Code + "' and bank_sub = '"+sub+"'";

                stmt = (Statement) dbUtility.con.createStatement();
                ResultSet rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                        t_bankcode2.setText(cvth.ASCII2Unicode(rs.getString("Bank_Code")));
                        t_subacc2.setText(cvth.ASCII2Unicode(rs.getString("Bank_sub")));
                        t_bankname2.setText(cvth.ASCII2Unicode(rs.getString("Bank_Name")));
                        t_account.setText(cvth.ASCII2Unicode(rs.getString("Bank_Acc")));
                    } else {
                        t_bankcode2.setText(rs.getString("Bank_Code"));
                        t_subacc2.setText(rs.getString("Bank_sub"));
                        t_bankname2.setText(rs.getString("Bank_Name"));
                        t_account.setText(rs.getString("Bank_Acc"));
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "คุณกำหนดรหัสธนาคารไม่ถูกต้อง...");
                    t_bankcode2.setText("");
                    t_subacc2.setText("");
                    t_bankname2.setText("");
                    t_account.setText("");
                    t_bankcode2.requestFocus();
                }
                rs.close();
                stmt.close();
                setActive();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }

    public boolean CheckValidEnter() {
        boolean RetVal2 = true;

        if (t_creditcode.getText().length() > 8) {
            JOptionPane.showMessageDialog(this, "กำหนดรหัสบัตรเครดิตไม่ถูกต้อง...(ตัองมีขนาดไม่เกิน 8 ตัวอักษร)");
            RetVal2 = false;
            t_creditcode.requestFocus();
        }
        return RetVal2;
    }

    public boolean CheckValidBank() {
        boolean RetVal2 = true;

        if (t_bankcode.getText().length() > 3) {
            JOptionPane.showMessageDialog(this, "กำหนดรหัสธนาคารเจ้าของบัตรไม่ถูกต้อง...(ตัองมีขนาดไม่เกิน 3 ตัวอักษร)");
            RetVal2 = false;
            t_bankcode.requestFocus();
        }
        return RetVal2;
    }

    public boolean CheckValidBank2() {
        boolean RetVal2 = true;
//        if(chkdatabank2(t_bankcode2.getText(), t_subacc2.getText()))
//        {
//            JOptionPane.showMessageDialog(this, "กำหนดรหัสธนาคารไม่ถูกต้อง...(กรุณากรอกเลขบัญชีให้ถูกต้อง)");
//            RetVal2 = false;
//            t_bankcode2.requestFocus();
//        }
        if (t_bankcode2.getText().length() > 8) {
            JOptionPane.showMessageDialog(this, "กำหนดรหัสธนาคารไม่ถูกต้อง...(ตัองมีขนาดไม่เกิน 8 ตัวอักษร)");
            RetVal2 = false;
            t_bankcode2.requestFocus();
        }
        return RetVal2;
    }

    public void showdataintb() {
        stmt = null;
        ResultSet rs = null;

        tbCreditCardSetup = (DefaultTableModel) tblcreditcard.getModel();
        int cnt = tbCreditCardSetup.getRowCount();
        if (cnt > 0) {
            for (int i = 0; i < cnt; i++) {
                tbCreditCardSetup.removeRow(0);
            }
        }
        try {
            stmt = (Statement) dbUtility.con.createStatement();
            String sql = "select * from creditfile order by CrCode";
            rs = stmt.executeQuery(sql);
            while (rs.next()) {
                {
                    if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                        tbCreditCardSetup.addRow(new Object[]{cvth.ASCII2Unicode(rs.getString("CrBank")),
                                    cvth.ASCII2Unicode(rs.getString("CrCode")),
                                    cvth.ASCII2Unicode(rs.getString("CrName")),
                                    cvth.ASCII2Unicode(rs.getString("CrRedule")),
                                    cvth.ASCII2Unicode(rs.getString("CrCharge")),
                                    cvth.ASCII2Unicode(rs.getString("CrGetCardNo"))});
                    } else {
                        tbCreditCardSetup.addRow(new Object[]{rs.getString("CrBank"),
                                    rs.getString("CrCode"),
                                    rs.getString("CrName"),
                                    rs.getString("CrRedule"),
                                    rs.getString("CrCharge"),
                                    rs.getString("CrGetCardNo")});
                    }
                }
            }
        } catch (Exception e) {
        }
    }

    public void btnsave() {
        if (CheckValidSave()) {
            if (chkdata(t_creditcode.getText())) {

                try {
                    if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                        stmt = (Statement) dbUtility.con.createStatement();
                        String sql = "Update creditfile set CrName=?,CrBank=?,CrAcc=?,CrSub=?"
                                + ",CrGetCardNo=?,CrCharge=?,CrRedule=?,Bank_Code=?,Bank_Sub=?"
                                + ",Bank_Chg=? where CrCode = ?";
                        PreparedStatement prm = (PreparedStatement) dbUtility.con.prepareStatement(sql);
                        prm.setString(1, cvth.Unicode2ASCII(t_creditname.getText()));
                        prm.setString(2, cvth.Unicode2ASCII(t_bankcode.getText()));
                        prm.setString(3, cvth.Unicode2ASCII(t_creditacc.getText()));
                        prm.setString(4, cvth.Unicode2ASCII(t_subacc.getText()));
                        if (rd_yes.isSelected()) {
                            prm.setString(5, cvth.Unicode2ASCII("Y"));
                        } else if (rd_no.isSelected()) {
                            prm.setString(5, cvth.Unicode2ASCII("N"));
                        }
                        prm.setDouble(6, Double.parseDouble(PUtility.ConvertReal(t_chargecredit.getText())));
                        prm.setDouble(7, Double.parseDouble(PUtility.ConvertReal(t_discountcredit.getText())));
                        prm.setString(8, cvth.Unicode2ASCII(t_bankcode2.getText()));
                        prm.setString(9, cvth.Unicode2ASCII(t_subacc2.getText()));
                        prm.setDouble(10, Double.parseDouble(PUtility.ConvertReal(t_service.getText())));
                        prm.setString(11, cvth.Unicode2ASCII(t_creditcode.getText().trim()));
                        prm.executeUpdate();
                    } else {
                        stmt = (Statement) dbUtility.con.createStatement();
                        String sql = "Update creditfile set CrName=?,CrBank=?,CrAcc=?,CrSub=?"
                                + ",CrGetCardNo=?,CrCharge=?,CrRedule=?,Bank_Code=?,Bank_Sub=?"
                                + ",Bank_Chg=? where CrCode = ?";
                        PreparedStatement prm = (PreparedStatement) dbUtility.con.prepareStatement(sql);
                        prm.setString(1, t_creditname.getText());
                        prm.setString(2, t_bankcode.getText());
                        prm.setString(3, t_creditacc.getText());
                        prm.setString(4, t_subacc.getText());
                        if (rd_yes.isSelected()) {
                            prm.setString(5, "Y");
                        } else if (rd_no.isSelected()) {
                            prm.setString(5, "N");
                        }
                        prm.setDouble(6, Double.parseDouble(PUtility.ConvertReal(t_chargecredit.getText())));
                        prm.setDouble(7, Double.parseDouble(PUtility.ConvertReal(t_discountcredit.getText())));
                        prm.setString(8, t_bankcode2.getText());
                        prm.setString(9, t_subacc2.getText());
                        prm.setDouble(10, Double.parseDouble(PUtility.ConvertReal(t_service.getText())));
                        prm.setString(11, t_creditcode.getText().trim());
                        prm.executeUpdate();
                    }
                    stmt.close();
                    clear();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "Update CreditCard Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                try {
                    if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                        stmt = (Statement) dbUtility.con.createStatement();
                        String sql = "Insert into creditfile (CrCode,CrName,CrBank,CrAcc,CrSub"
                                + ",CrGetCardNo,CrCharge,CrRedule,Bank_Code,Bank_Sub,Bank_Chg) "
                                + " values(?,?,?,?,?,?,?,?,?,? ,?)";
                        PreparedStatement prm = (PreparedStatement) dbUtility.con.prepareStatement(sql);
                        prm.setString(1, cvth.Unicode2ASCII(t_creditcode.getText().trim()));
                        prm.setString(2, cvth.Unicode2ASCII(t_creditname.getText()));
                        prm.setString(3, cvth.Unicode2ASCII(t_bankcode.getText()));
                        prm.setString(4, cvth.Unicode2ASCII(t_creditacc.getText()));
                        prm.setString(5, cvth.Unicode2ASCII(t_subacc.getText()));
                        if (rd_yes.isSelected()) {
                            prm.setString(6, cvth.Unicode2ASCII("Y"));
                        } else if (rd_no.isSelected()) {
                            prm.setString(6, cvth.Unicode2ASCII("N"));
                        }
                        prm.setDouble(7, Double.parseDouble(PUtility.ConvertReal(t_chargecredit.getText())));
                        prm.setDouble(8, Double.parseDouble(PUtility.ConvertReal(t_discountcredit.getText())));
                        
                        prm.setString(9, cvth.Unicode2ASCII(t_bankcode2.getText()));
                        prm.setString(10, cvth.Unicode2ASCII(t_subacc2.getText()));
                        prm.setDouble(11, Double.parseDouble(PUtility.ConvertReal(t_service.getText())));
                        prm.executeUpdate();
                    } else {
                        stmt = (Statement) dbUtility.con.createStatement();
                        String sql = "Insert into creditfile (CrCode,CrName,CrBank,CrAcc,CrSub"
                                + ",CrGetCardNo,CrCharge,CrRedule,Bank_Code,Bank_Sub,Bank_Chg) "
                                + " values(?,?,?,?,?,?,?,?,?,? ,?)";
                        PreparedStatement prm = (PreparedStatement) dbUtility.con.prepareStatement(sql);
                        prm.setString(1, t_creditcode.getText().trim());
                        prm.setString(2, t_creditname.getText());
                        prm.setString(3, t_bankcode.getText());
                        prm.setString(4, t_creditacc.getText());
                        prm.setString(5, t_subacc.getText());
                        if (rd_yes.isSelected()) {
                            prm.setString(6, "Y");
                        } else if (rd_no.isSelected()) {
                            prm.setString(6, "N");
                        }
                        prm.setDouble(7, Double.parseDouble(PUtility.ConvertReal(t_chargecredit.getText())));
                        prm.setDouble(8, Double.parseDouble(PUtility.ConvertReal(t_discountcredit.getText())));
                        
                        prm.setString(9, t_bankcode2.getText());
                        prm.setString(10, t_subacc2.getText());
                        prm.setDouble(11, Double.parseDouble(PUtility.ConvertReal(t_service.getText())));
                        prm.executeUpdate();
                    }
                    stmt.close();
                    clear();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "Insert CreditCard Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            showdataintb();
        }
    }

    public boolean chkdata(String pk) {
        boolean chk = false;
        ResultSet rs = null;
        try {
            if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                stmt = (Statement) dbUtility.con.createStatement();
                String sql = "select * from creditfile where CrCode ='" + cvth.Unicode2ASCII(pk) + "'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    chk = true;
                }
            } else {
                stmt = (Statement) dbUtility.con.createStatement();
                String sql = "select * from creditfile where CrCode ='" + pk + "'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    chk = true;
                }
            }
        } catch (Exception e) {
        }
        return chk;
    }

    public boolean chkdatabank(String pk) {
        boolean chk = false;
        ResultSet rs = null;
        try {
            if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                stmt = (Statement) dbUtility.con.createStatement();
                String sql = "select * from bankfile where BCode ='" + cvth.Unicode2ASCII(pk) + "'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    chk = true;
                }
            } else {
                stmt = (Statement) dbUtility.con.createStatement();
                String sql = "select * from bankfile where BCode ='" + pk + "'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    chk = true;
                }
            }
        } catch (Exception e) {
        }
        return chk;
    }

    public boolean chkdatabank2(String pk, String sub) {
        boolean chk = false;
        ResultSet rs = null;
        try {
            if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                stmt = (Statement) dbUtility.con.createStatement();
                String sql = "select * from craccno where Bank_Code ='" + cvth.Unicode2ASCII(pk) + "' and bank_sub='"+cvth.Unicode2ASCII(sub)+"'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    chk = true;
                }
            } else {
                stmt = (Statement) dbUtility.con.createStatement();
                String sql = "select * from craccno where Bank_Code ='" + pk + "' and bank_sub='"+sub+"'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    chk = true;
                }
            }
        } catch (Exception e) {
        }
        return chk;
    }

    public boolean CheckValidSave() {
        boolean chk = true;
        if(!t_creditname.isFocusable())
        {
            chk = false;
        }
        
        else if (t_creditcode.getText().length() > 8) {
            JOptionPane.showMessageDialog(this, "กำหนดรหัสบัตรเครดิตไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 8 ตัวอักษร)");
            chk = false;
            t_creditcode.requestFocus();
        } else if (t_creditname.getText().length() > 30) {
            JOptionPane.showMessageDialog(this, "กำหนดชื่อบัตรเครดิตไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 30 ตัวอักษร)");
            chk = false;
            t_creditname.requestFocus();
        } else if (t_bankcode.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "กรุณากำหนดรหัสธนาคาร");
            chk = false;
            t_bankcode.requestFocus();
            t_bankcode.setEditable(true);
        } else if (t_bankcode.getText().length() > 3) {
            JOptionPane.showMessageDialog(this, "กำหนดรหัสธนาคารไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 3 ตัวอักษร)");
            chk = false;
            t_bankcode.requestFocus();
        } 
        else if(!chkdatabank2(t_bankcode2.getText(), t_subacc2.getText()))
        {
            JOptionPane.showMessageDialog(this, "กำหนดรหัสธนาคารไม่ถูกต้อง...(กรุณากรอกเลขบัญชีให้ถูกต้อง)");
            chk = false;
            t_bankcode2.requestFocus();
        }
        else if (t_bankcode.getText().length() > 3) {
            JOptionPane.showMessageDialog(this, "กำหนดรหัสธนาคารเจ้าของบัตรไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 3 ตัวอักษร)");
            chk = false;
            t_bankcode.requestFocus();
        } else if (t_creditacc.getText().length() > 8) {
            JOptionPane.showMessageDialog(this, "กำหนด Credit Acc ไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 8 ตัวอักษร)");
            chk = false;
            t_creditacc.requestFocus();
        } else if (t_subacc.getText().length() > 8) {
            JOptionPane.showMessageDialog(this, "กำหนด Sub Acc ไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 5 ตัวอักษร)");
            chk = false;
            t_subacc.requestFocus();
        } else if (t_bankcode2.getText().length() > 8) {
            JOptionPane.showMessageDialog(this, "กำหนดรหัสธนาคารไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 8 ตัวอักษร)");
            chk = false;
            t_bankcode2.requestFocus();
        } else if (t_subacc2.getText().length() > 5) {
            JOptionPane.showMessageDialog(this, "กำหนด Sub Acc ไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 5 ตัวอักษร)");
            chk = false;
            t_subacc2.requestFocus();
        }
        return chk;
    }

    public void delete() {
        try {
            int confirm = JOptionPane.showConfirmDialog(this, "คุณต้องการลบข้อมูลรายการนี้หรือไม่...?", "Confirm", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                    stmt = (Statement) dbUtility.con.createStatement();
                    String sql = "Delete from creditfile where CrCode = ?";
                    PreparedStatement prm = (PreparedStatement) dbUtility.con.prepareStatement(sql);
                    prm.setString(1, cvth.Unicode2ASCII(t_creditcode.getText()));
                    prm.executeUpdate();
                    stmt.close();
                } else {
                    stmt = (Statement) dbUtility.con.createStatement();
                    String sql = "Delete from creditfile where CrCode = ?";
                    PreparedStatement prm = (PreparedStatement) dbUtility.con.prepareStatement(sql);
                    prm.setString(1, t_creditcode.getText());
                    prm.executeUpdate();
                    stmt.close();
                }
                clear();
                showdataintb();
            }

        } catch (Exception e) {
        }
    }
    
    public void btnbank() {
        Point point = btnbank1.getLocation();
        point.setLocation(point.getX() + 1, point.getY() + 1);
        BrowserBankFile dialog = new BrowserBankFile(new NimbusFrame(), true, point);
        dialog.setVisible(true);

        try {
            if (!dialog.code.equals("")) {
                t_bankcode.setText(dialog.code);
                GetDataBank(dialog.code);
                t_creditacc.requestFocus();
            } else {
                t_bankcode.requestFocus();
            }
        } catch (Exception e) {
            t_bankcode.requestFocus();
        }
    }
    
    public void btnbank2() {
        Point point = btnbank2.getLocation();
        point.setLocation(point.getX() + 1, point.getY() + 1);
        listCrAccNo dialog = new listCrAccNo(new NimbusFrame(), true);
        dialog.setVisible(true);

        try { 
            if (!dialog.code.equals("")) {
                t_bankcode2.setText(dialog.code);
                t_subacc2.setText(dialog.name);
                GetDataBank2(t_bankcode2.getText(),t_subacc2.getText());
                t_service.requestFocus();
            } else {
                t_bankcode2.requestFocus();
            }
        } catch (Exception e) {
            t_bankcode2.requestFocus();
        }
    }
}
