/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UpdateMaterial.java
 *
 * Created on Sep 4, 2012, 10:59:31 AM
 */
package masterfile;

import borfunction.calculateLCostPLU;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import dbutility.dbUtility;
import frmlist.ListIngredent;
import frmlist.listCampaign;
import frmlist.listIngGroup;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilititiesfunction.*;

/**
 *
 * @author natee
 */
public class UpdateMaterial extends javax.swing.JDialog {

    dbUtility db = new dbUtility();
    private Statement stmt;
    
    DefaultTableModel tbCreditCardSetup;
    String formname = "updatematerial";
    private Color colorEnable = new Color(255, 246, 143);
    private Color colorDisable2 = new Color(216, 215, 214);
    ThaiUtilities cvth = new ThaiUtilities();

    /** Creates new form UpdateMaterial */
    public UpdateMaterial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        checkuserconfig() ;
        db.dbconnect();
        try {
            stmt = (Statement) dbUtility.con.createStatement();
        } catch (Exception e) {
        }


        getLanguage Language = new getLanguage();
        Language.setText(formname, this, Language.getChklang());
        clear();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t_code = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t_bgroup = new javax.swing.JTextField();
        btncode = new javax.swing.JButton();
        btngroup = new javax.swing.JButton();
        t_bgroupname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t_unit = new javax.swing.JTextField();
        t_cost = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        t_lost = new javax.swing.JFormattedTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        t_subunit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t_pack1 = new javax.swing.JTextField();
        t_pack = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuDelete = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cancel-icon.png"))); // NOI18N
        jButton2.setText("ยกเลิก");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setIconTextGap(0);
        jButton2.setName("DBbtncancle"); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save-icon.png"))); // NOI18N
        btnSave.setText("บันทึกข้อมูล");
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setIconTextGap(0);
        btnSave.setName("DBbtnsave"); // NOI18N
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete-icons.png"))); // NOI18N
        btnDelete.setText("ลบข้อมูล");
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setIconTextGap(0);
        btnDelete.setName("DBbtndel"); // NOI18N
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LogOut-icon.png"))); // NOI18N
        jButton7.setText("ออก");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setIconTextGap(0);
        jButton7.setName("DBbtnexit"); // NOI18N
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("รหัสวัตถุดิบ (Code)");
        jLabel1.setName("D_code"); // NOI18N

        t_code.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_codeFocusLost(evt);
            }
        });
        t_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_codeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_codeKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("รายละเอียด");
        jLabel2.setName("D_detail"); // NOI18N

        t_name.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_nameFocusLost(evt);
            }
        });
        t_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_nameKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("กลุ่มวัตถุดิบ");
        jLabel3.setName("D_ingre"); // NOI18N

        t_bgroup.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_bgroup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_bgroupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_bgroupFocusLost(evt);
            }
        });
        t_bgroup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_bgroupKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_bgroupKeyTyped(evt);
            }
        });

        btncode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Windows-Magnifier-icon.png"))); // NOI18N
        btncode.setFocusable(false);
        btncode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncodeActionPerformed(evt);
            }
        });

        btngroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Windows-Magnifier-icon.png"))); // NOI18N
        btngroup.setFocusable(false);
        btngroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngroupActionPerformed(evt);
            }
        });

        t_bgroupname.setBackground(new java.awt.Color(249, 252, 186));
        t_bgroupname.setEditable(false);
        t_bgroupname.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_bgroupname.setFocusable(false);

        jLabel4.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("อัตราสูญเสียจากการใช้");
        jLabel4.setName("D_lost"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("ราคาต้นทุน/หน่วยหลัก");
        jLabel5.setName("D_cost"); // NOI18N

        t_unit.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_unit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_unitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_unitFocusLost(evt);
            }
        });
        t_unit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_unitKeyPressed(evt);
            }
        });

        t_cost.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        t_cost.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        t_cost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_costFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_costFocusLost(evt);
            }
        });
        t_cost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_costKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_costKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("หน่วยนับหลัก");
        jLabel6.setName("D_unit"); // NOI18N

        t_lost.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00%"))));
        t_lost.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        t_lost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_lostFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_lostFocusLost(evt);
            }
        });
        t_lost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_lostKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_lostKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(t_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_lost, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(t_code, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btncode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(t_bgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btngroup, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(t_bgroupname, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(t_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_name)))
                .addGap(91, 91, 91))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(t_code, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btncode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(t_bgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btngroup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_bgroupname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(t_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(t_lost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("กำหนดอัตราส่วนหน่วยย่อย(หน่วยผสม)");
        jLabel7.setName("D_subtitle"); // NOI18N
        jLabel7.setBounds(10, 10, 280, 24);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("หน่วยนับย่อย");
        jLabel8.setName("D_subunit"); // NOI18N

        t_subunit.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_subunit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_subunitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_subunitFocusLost(evt);
            }
        });
        t_subunit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_subunitKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("อัตราส่วนหน่วยนับหลัก");
        jLabel9.setName("D_count"); // NOI18N

        t_pack1.setBackground(new java.awt.Color(249, 252, 186));
        t_pack1.setEditable(false);
        t_pack1.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        t_pack1.setText("1 X");

        t_pack.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        t_pack.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        t_pack.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_packFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_packFocusLost(evt);
            }
        });
        t_pack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_packKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_packKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t_subunit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_pack1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_pack, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(t_subunit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(t_pack1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_pack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4.setBounds(20, 30, 570, 60);
        jLayeredPane1.add(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jMenu1.setText("ฟังก์ชั่น");
        jMenu1.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        jMenu1.setName("menufuc"); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jMenuItem2.setText("ยกเลิก");
        jMenuItem2.setName("mcancle"); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        menuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSave.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menuSave.setText("บันทึกข้อมูล");
        menuSave.setName("msave"); // NOI18N
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        jMenu1.add(menuSave);

        menuDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuDelete.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menuDelete.setText("ลบข้อมูล");
        menuDelete.setName("mdel"); // NOI18N
        menuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeleteActionPerformed(evt);
            }
        });
        jMenu1.add(menuDelete);
        jMenu1.add(jSeparator1);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jMenuItem5.setText("ออก");
        jMenuItem5.setName("mexit"); // NOI18N
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-684)/2, (screenSize.height-504)/2, 684, 504);
    }// </editor-fold>//GEN-END:initComponents
private void checkuserconfig() {
        //MenuName = Mast1
        UserLogin userrec = UserLogin.userlogin;
        if (userrec.getPlu10().equals("1")) {
            btnSave.setEnabled(false);
            btnDelete.setEnabled(false);
            menuSave.setEnabled(false);
            menuDelete.setEnabled(false);
        }
        if (userrec.getPlu10().equals("2")) {
            btnSave.setEnabled(true);
            btnDelete.setEnabled(false);
            menuSave.setEnabled(true);
            menuDelete.setEnabled(false);
        }
        if (userrec.getPlu10().equals("3")) {
            btnSave.setEnabled(true);
            btnDelete.setEnabled(true);
            menuSave.setEnabled(true);
            menuDelete.setEnabled(true);
        }
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (!t_code.getText().trim().equals("")&&t_name.isFocusable()) {
            btnsave();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        if (!t_code.getText().trim().equals("")&&chkdata(t_code.getText())&&t_name.isFocusable()) {
            delete();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jButton2ActionPerformed(evt);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed

        //jButton3ActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSaveActionPerformed

    private void menuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeleteActionPerformed

        //jButton4ActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDeleteActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
    jButton7ActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void t_codeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_codeKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(!t_code.getText().equals(""))
            {
                setActive();
                t_name.requestFocus();
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            btnIngredient();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_codeKeyPressed

    private void t_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_nameKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_bgroup.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nameKeyPressed

    private void t_bgroupKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_bgroupKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String Code = "";
            Code = t_bgroup.getText().trim();
            if(!Code.equals(""))
            {
            t_unit.requestFocus();
            GetGroup(Code);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "ข้อมูลไม่ถูกต้อง กรุณากรอกข้อมูลก่อน");
                t_bgroupname.setText("");
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            btnInggroup();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_bgroupKeyPressed

    private void t_unitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_unitKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_cost.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_unitKeyPressed

    private void t_costKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_costKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_lost.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_costKeyPressed

    private void t_lostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_lostKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_subunit.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_lostKeyPressed

    private void t_subunitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_subunitKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_pack.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_subunitKeyPressed

    private void t_packKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_packKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_name.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_packKeyPressed

    private void btngroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngroupActionPerformed
        btnInggroup();
        // TODO add your handling code here:
    }//GEN-LAST:event_btngroupActionPerformed

    private void btncodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncodeActionPerformed
        btnIngredient();
        // TODO add your handling code here:
    }//GEN-LAST:event_btncodeActionPerformed

    private void t_bgroupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_bgroupFocusLost
        t_bgroup.select(0,0);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_t_bgroupFocusLost

    private void t_bgroupKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_bgroupKeyTyped
        if(t_bgroup.getText().length()>=4)
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_bgroupKeyTyped

    private void t_codeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_codeKeyTyped
        if(t_code.getText().length()>=13)
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_codeKeyTyped

    private void t_lostFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_lostFocusLost
        t_lost.select(0,0);
        if(!PUtility.CheckFmtPersent(t_lost.getText()))
        {
        JOptionPane.showMessageDialog(this, "กรุณาใส่รูปแบบเปอร์เซ็นให้ถูกต้อง ตัวอย่าง 10.00%");
        t_lost.requestFocus();
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_t_lostFocusLost

    private void t_lostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_lostKeyTyped
        if(t_lost.getText().length()>=7)
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_lostKeyTyped

    private void t_packKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_packKeyTyped
        if(t_pack.getText().length()>=9)
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_packKeyTyped

    private void t_costKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_costKeyTyped
        if(t_cost.getText().length()>=12)
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_costKeyTyped

    private void t_codeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_codeFocusLost
            String Code = "";
            Code = t_code.getText().trim();
            if(!Code.equals(""))
            {
            GetData(Code);
            t_name.requestFocus();
            }
            
        // TODO add your handling code here:
    }//GEN-LAST:event_t_codeFocusLost

    private void t_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_nameFocusGained
        t_name.selectAll();
        // TODO add your handling code here:

    }//GEN-LAST:event_t_nameFocusGained

    private void t_bgroupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_bgroupFocusGained
        t_bgroup.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_bgroupFocusGained

    private void t_unitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_unitFocusGained
        t_unit.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_unitFocusGained

    private void t_costFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_costFocusGained
        t_cost.setText(t_cost.getText());
        t_cost.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_costFocusGained

    private void t_lostFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_lostFocusGained
        t_lost.setText(t_lost.getText());
        t_lost.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_lostFocusGained

    private void t_subunitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_subunitFocusGained
        t_subunit.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_subunitFocusGained

    private void t_packFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_packFocusGained
        t_pack.setText(t_pack.getText());
        t_pack.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_packFocusGained

    private void t_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_nameFocusLost
        t_name.select(0,0);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nameFocusLost

    private void t_unitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_unitFocusLost
        t_unit.select(0,0);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_unitFocusLost

    private void t_costFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_costFocusLost
        t_cost.select(0,0);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_costFocusLost

    private void t_subunitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_subunitFocusLost
        t_subunit.select(0,0);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_subunitFocusLost

    private void t_packFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_packFocusLost
        t_pack.select(0,0);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_packFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                UpdateMaterial dialog = new UpdateMaterial(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btncode;
    private javax.swing.JButton btngroup;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuDelete;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JTextField t_bgroup;
    private javax.swing.JTextField t_bgroupname;
    private javax.swing.JTextField t_code;
    private javax.swing.JFormattedTextField t_cost;
    private javax.swing.JFormattedTextField t_lost;
    private javax.swing.JTextField t_name;
    private javax.swing.JFormattedTextField t_pack;
    private javax.swing.JTextField t_pack1;
    private javax.swing.JTextField t_subunit;
    private javax.swing.JTextField t_unit;
    // End of variables declaration//GEN-END:variables

    public void clear() {
        t_code.setText("");
        t_code.setBackground(java.awt.Color.white);
        
        t_name.setText("");
        t_bgroup.setText("");
        t_bgroupname.setText("");
        t_unit.setText("");
        t_cost.setText("0.00");
        t_lost.setText("0.00%");
        t_subunit.setText("");
        t_pack1.setText("1 X");
        t_pack.setText("1");
        setUnActive();
        t_code.setEditable(true);
        jLabel1.requestFocus();
        t_code.requestFocus();

    }

    private void setActive() {
        setActive(true, colorEnable);
    }

    private void setUnActive() {
        setActive(false, colorDisable2);
    }

    private void setActive(boolean active, Color color) {


        t_name.setFocusable(active);
        t_bgroup.setFocusable(active);
        t_bgroupname.setFocusable(active);
        t_unit.setFocusable(active);
        t_cost.setFocusable(active);
        t_lost.setFocusable(active);
        t_subunit.setFocusable(active);
        t_pack1.setFocusable(active);
        t_pack.setFocusable(active);
        btngroup.setEnabled(active);
        
        if(active==false)
        {
        t_code.setFocusable(true);
        t_code.setBackground(Color.WHITE);
        
        }
        else
        {
        t_code.setFocusable(false);
        t_code.setBackground(new java.awt.Color(255, 246, 143));
        
        }

    }

    public void btnsave() {
        if (CheckValidSave()) {
            if (chkdata(t_code.getText())) {
                
                    try {
                        if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                            stmt = (Statement) dbUtility.con.createStatement();
                            String sql = "Update ingredent set InName=?,InGroup=?,InUnit=?,InCost=?"
                                    + ",InLost=?,InSubUnit=?,InPack=? where InCode = ?";
                            PreparedStatement prm = (PreparedStatement) dbUtility.con.prepareStatement(sql);
                            prm.setString(8, cvth.Unicode2ASCII(t_code.getText()));
                            prm.setString(1, cvth.Unicode2ASCII(t_name.getText()));
                            prm.setString(2, cvth.Unicode2ASCII(t_bgroup.getText()));
                            prm.setString(3, cvth.Unicode2ASCII(t_unit.getText()));
                            double TempAmt1 = Double.parseDouble(PUtility.ConvertReal(t_cost.getText()));
                            prm.setDouble(4, TempAmt1);
                            double TempAmt2 = Double.parseDouble(PUtility.ConvertReal(PUtility.ConvertPersent(t_lost.getText())));
                            prm.setDouble(5, TempAmt2);
                            prm.setString(6, cvth.Unicode2ASCII(t_subunit.getText()));
                            double TempAmt3 = Double.parseDouble(PUtility.ConvertReal(t_pack.getText()));
                            prm.setDouble(7, TempAmt3);
                            prm.executeUpdate();
                        } else {
                            stmt = (Statement) dbUtility.con.createStatement();
                            String sql = "Update ingredent set InName=?,InGroup=?,InUnit=?,InCost=?"
                                    + ",InLost=?,InSubUnit=?,InPack=? where InCode = ?";
                            PreparedStatement prm = (PreparedStatement) dbUtility.con.prepareStatement(sql);
                            prm.setString(8, t_code.getText());
                            prm.setString(1, t_name.getText());
                            prm.setString(2, t_bgroup.getText());
                            prm.setString(3, t_unit.getText());
                            double TempAmt1 = Double.parseDouble(PUtility.ConvertReal(t_cost.getText()));
                            prm.setDouble(4, TempAmt1);
                            double TempAmt2 = Double.parseDouble(PUtility.ConvertReal(t_lost.getText()));
                            prm.setDouble(5, TempAmt2);
                            prm.setString(6, t_subunit.getText());
                            double TempAmt3 = Double.parseDouble(PUtility.ConvertReal(t_pack.getText()));
                            prm.setDouble(7, TempAmt3);
                            prm.executeUpdate();
                        }
                        stmt.close();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, e.getMessage(), "Update Material Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    try {
                        if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                            stmt = (Statement) dbUtility.con.createStatement();
                            String sql = "Insert into ingredent (InCode,InName,InGroup,InUnit,InCost"
                                    + ",InLost,InSubUnit,InPack) values(?,?,?,?,?,?,?,?)";
                            PreparedStatement prm = (PreparedStatement) dbUtility.con.prepareStatement(sql);
                            prm.setString(1, cvth.Unicode2ASCII(t_code.getText().trim()));
                            prm.setString(2, cvth.Unicode2ASCII(t_name.getText()));
                            prm.setString(3, cvth.Unicode2ASCII(t_bgroup.getText()));
                            prm.setString(4, cvth.Unicode2ASCII(t_unit.getText()));
                            double TempAmt1 = Double.parseDouble(PUtility.ConvertReal(cvth.Unicode2ASCII(t_cost.getText())));
                            prm.setDouble(5, TempAmt1);
                            double TempAmt2 = Double.parseDouble(PUtility.ConvertReal(PUtility.ConvertPersent(t_lost.getText())));
                            prm.setDouble(6, TempAmt2);
                            prm.setString(7, cvth.Unicode2ASCII(t_subunit.getText()));
                            double TempAmt3 = Double.parseDouble(PUtility.ConvertReal(cvth.Unicode2ASCII(t_pack.getText())));
                            prm.setDouble(8, TempAmt3);
                            prm.executeUpdate();
                        } else {
                            stmt = (Statement) dbUtility.con.createStatement();
                            String sql = "Insert into ingredent (InCode,InName,InGroup,InUnit,InCost"
                                    + ",InLost,InSubUnit,InPack) values(?,?,?,?,?,?,?,?)";
                            PreparedStatement prm = (PreparedStatement) dbUtility.con.prepareStatement(sql);
                            prm.setString(1, t_code.getText().trim());
                            prm.setString(2, t_name.getText());
                            prm.setString(3, t_bgroup.getText());
                            prm.setString(4, t_unit.getText());
                            double TempAmt1 = Double.parseDouble(PUtility.ConvertReal(t_cost.getText()));
                            prm.setDouble(5, TempAmt1);
                            double TempAmt2 = Double.parseDouble(PUtility.ConvertReal(PUtility.ConvertPersent(t_lost.getText())));
                            prm.setDouble(6, TempAmt2);
                            prm.setString(7, t_subunit.getText());
                            double TempAmt3 = Double.parseDouble(PUtility.ConvertReal(t_pack.getText()));
                            prm.setDouble(8, TempAmt3);
                            prm.executeUpdate();
                        }
                        stmt.close();
                        
                        
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, e.getMessage(), "Insert Material Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            UpdateCostInProduct(t_code.getText());
            clear();
        }
    }

    public boolean chkdata(String pk) {
        boolean chk = false;
        ResultSet rs = null;
        try {
            if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                stmt = (Statement) dbUtility.con.createStatement();
                String sql = "select * from ingredent where InCode ='" + cvth.Unicode2ASCII(pk) + "'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    chk = true;
                }
            } else {
                stmt = (Statement) dbUtility.con.createStatement();
                String sql = "select * from ingredent where InCode ='" + pk + "'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    chk = true;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return chk;
    }

    public boolean chkdatagroup(String pk) {
        boolean chk = false;
        ResultSet rs = null;
        try {
            if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                stmt = (Statement) dbUtility.con.createStatement();
                String sql = "select * from inggroup where ingGroupCode ='" + cvth.Unicode2ASCII(pk) + "'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    chk = true;
                }
            } else {
                stmt = (Statement) dbUtility.con.createStatement();
                String sql = "select * from inggroup where ingGroupCode ='" + pk + "'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    chk = true;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return chk;
    }

    public boolean CheckValidSave() {
        boolean chk = true;


        if (t_code.getText().length() > 13) {
            JOptionPane.showMessageDialog(this, "กำหนดรหัสวัตถุดิบไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 13 ตัวอักษร)");
            chk = false;
            t_code.requestFocus();
        } else if (t_bgroup.getText().length() > 4) {
            JOptionPane.showMessageDialog(this, "กำหนดกลุ่มวัตถุดิบไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 4 ตัวอักษร)");
            chk = false;
            t_bgroup.requestFocus();
        } else if (t_bgroup.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "กรุณากำหนดกลุ่มวัตถุดิบ");
            chk = false;
            t_bgroup.requestFocus();
            t_bgroup.setEditable(true);
        }
            else if (!chkdatagroup(t_bgroup.getText())) {
            JOptionPane.showMessageDialog(this, "กำหนดกลุ่มวัตถุดิบไม่ถูกต้อง กรุณากำหนดกลุ่มวัตถุดิบ");
            chk = false;
            t_bgroup.requestFocus();
            t_bgroup.setEditable(true);
        
        } else if (t_unit.getText().length() > 15) {
            JOptionPane.showMessageDialog(this, "กำหนดหน่วยนับไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 15 ตัวอักษร)");
            chk = false;
            t_unit.requestFocus();
        } else if (t_lost.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "กำหนดอัตราสูญเสียจากการใช้ไม่ถูกต้อง... ");
            chk = false;
            t_lost.requestFocus();
            return chk;
        }
         else if (t_subunit.getText().length() > 15) {
            JOptionPane.showMessageDialog(this, "กำหนดหน่วยนับย่อยไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 15 ตัวอักษร)");
            chk = false;
            t_subunit.requestFocus();
        }else if (t_pack.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "กำหนดอัตราส่วนหน่วยนับหลักไม่ถูกต้อง... ");
            chk = false;
            t_pack.requestFocus();
        } 
        else if (t_pack.getText().length() > 9) {
            JOptionPane.showMessageDialog(this, "ระบบไม่สามารถจัดเก็บได้ ต้องมีจำนวนไม่เกิน 9,999,999");
            chk = false;
            t_pack.requestFocus();
        }
        else if (t_cost.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "กำหนดราคาต้นทุน/หน่วยหลักไม่ถูกต้อง...");
            chk = false;
            t_cost.requestFocus();
        }
        else if (t_cost.getText().length()>12) {
            JOptionPane.showMessageDialog(this, "ระบบไม่สามารถจัดเก็บได้ ต้องมีจำนวนไม่เกิน 9,999,999.99");
            chk = false;
            t_cost.requestFocus();
        }
        Double lost = Double.parseDouble(PUtility.ConvertReal(PUtility.ConvertPersent(t_lost.getText())));
        if (lost<0||lost>100.00) {
            JOptionPane.showMessageDialog(this, "ระบบไม่สามารถจัดเก็บได้ จำนวนเปอร์เซ็นต้องไม่น้อยกว่า 0.00 และมากเกิน 100.00 เปอร์เซ็น");
            chk = false;
            t_lost.requestFocus();
        }
        return chk;
    }

    public void delete() {
        try {
        int chk = chkMenuSetup(t_code.getText());
        if(chk==-1)
        {
            return;
        }
        if(chk==0)
        {
            int confirm = JOptionPane.showConfirmDialog(this, "คุณต้องการลบข้อมูลรายการนี้หรือไม่...?", "Confirm", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                
                if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                    stmt = (Statement) dbUtility.con.createStatement();
                    String sql = "Delete from ingredent where inCode = ?";
                    PreparedStatement prm = (PreparedStatement) dbUtility.con.prepareStatement(sql);
                    prm.setString(1, cvth.Unicode2ASCII(t_code.getText()));
                    prm.executeUpdate();
                } else {
                    stmt = (Statement) dbUtility.con.createStatement();
                    String sql = "Delete from ingredent where inCode = ?";
                    PreparedStatement prm = (PreparedStatement) dbUtility.con.prepareStatement(sql);
                    prm.setString(1, t_code.getText());
                    prm.executeUpdate();
                    stmt.close();
                }
                clear();
            }
        }
        else{
        JOptionPane.showMessageDialog(this, "ไม่สามารถลบข้อมูลได้ เนื่องจากมีข้อมูลอยู่ในรายการอาหารจำนวน "+chk+" รายการ");
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }

    public void GetData(String Code) {

        if (CheckValidEnter()) {
            try {
                if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                String sql = "select * from ingredent where InCode='" + cvth.Unicode2ASCII(Code) + "'";
                stmt = (Statement) dbUtility.con.createStatement();
                ResultSet rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    
                        t_code.setText(cvth.ASCII2Unicode(rs.getString("InCode")));
                        t_name.setText(cvth.ASCII2Unicode(rs.getString("InName")));
                        t_bgroup.setText(cvth.ASCII2Unicode(rs.getString("InGroup")));
                        GetGroup(t_bgroup.getText());
                        t_unit.setText(cvth.ASCII2Unicode(rs.getString("InUnit")));
                        t_cost.setText(cvth.ASCII2Unicode(Format.doubleFmt.format(rs.getFloat("InCost"))));
                        t_lost.setText(cvth.ASCII2Unicode(Format.percentFmt.format(rs.getFloat("InLost")/100)));
                        t_subunit.setText(cvth.ASCII2Unicode(rs.getString("InSubUnit")));
                        t_pack.setText(cvth.ASCII2Unicode(Format.integerFmt.format(rs.getFloat("InPack"))));
                        

                } else {
                    t_name.requestFocus();
                }
                rs.close();
                stmt.close();
                setActive();
                }
                else
                {
                String sql = "select * from ingredent where InCode='" + Code + "'";
                stmt = (Statement) dbUtility.con.createStatement();
                ResultSet rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    

                        t_code.setText(rs.getString("InCode"));
                        t_name.setText(rs.getString("InName"));
                        t_bgroup.setText(rs.getString("InGroup"));
                        GetGroup(t_bgroup.getText());
                        t_unit.setText(rs.getString("InUnit"));
                        t_cost.setText(Format.doubleFmt.format(rs.getFloat("InCost")));
                        t_lost.setText(Format.percentFmt.format(rs.getFloat("InLost")));
                        t_subunit.setText(rs.getString("InSubUnit"));
                        t_pack.setText(Format.integerFmt.format(rs.getFloat("InPack")));
                        
                    
                } else {
                    t_name.requestFocus();
                }
                rs.close();
                stmt.close();
                setActive();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }

    public boolean CheckValidEnter() {
        boolean RetVal2 = true;

        if (t_code.getText().length() > 13) {
            JOptionPane.showMessageDialog(this, "กำหนดรหัสวัตถุดิบไม่ถูกต้อง...(ตัองมีขนาดไม่เกิน 13 ตัวอักษร)");
            RetVal2 = false;
            t_code.requestFocus();
        }

        return RetVal2;
    }

    public void GetGroup(String Code) {
        if (CheckValidEnterGroup()) {
            try {
                 if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                String sql = "select * from inggroup where ingGroupCode='" + cvth.Unicode2ASCII(Code) + "'";
                stmt = (Statement) dbUtility.con.createStatement();
                ResultSet rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    
                        t_bgroup.setText(cvth.ASCII2Unicode(rs.getString("ingGroupCode")));
                        t_bgroupname.setText(cvth.ASCII2Unicode(rs.getString("ingGroupName")));
                    
                    t_unit.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(this, "กรุณาระบุรหัสกลุ่มวัตถุดิบให้ถูกต้อง");
                    t_bgroup.requestFocus();
                    t_bgroup.setText("");
                    t_bgroupname.setText("");
                }
                
                rs.close();
                stmt.close();
                }
                 else
                 {
                     
                        String sql = "select * from inggroup where ingGroupCode='" + cvth.Unicode2ASCII(Code) + "'";
                stmt = (Statement) dbUtility.con.createStatement();
                ResultSet rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    
                       t_bgroup.setText(rs.getString("ingGroupCode"));
                        t_bgroupname.setText(rs.getString("ingGroupName"));
                    t_unit.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(this, "กรุณาระบุรหัสกลุ่มวัตถุดิบให้ถูกต้อง");
                    t_bgroup.requestFocus();
                    t_bgroup.setText("");
                    t_bgroupname.setText("");
                }
                
                rs.close();
                stmt.close();
                 }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }

    public boolean CheckValidEnterGroup() {
        boolean RetVal2 = true;
        if (t_bgroup.getText().length() > 4) {
            JOptionPane.showMessageDialog(this, "กำหนดรหัสกลุ่มวัตถุดิบไม่ถูกต้อง...(ตัองมีขนาดไม่เกิน 4 ตัวอักษร)");
            RetVal2 = false;
            t_bgroup.requestFocus();
        }
        return RetVal2;
    }

    private void btnInggroup() {
        listIngGroup f = new listIngGroup(new NimbusFrame(), true);
        f.setVisible(true);
        if (!f.code.equals("")) {
            
                t_bgroup.setText(f.code);
                t_bgroup.requestFocus();
                GetGroup(t_bgroup.getText());
        }
    }

    private void btnIngredient() {
          ListIngredent f = new ListIngredent(new NimbusFrame(), true);
        f.setVisible(true);
        if (!f.code.equals("")) {
            
                t_code.setText(f.code);
                t_code.requestFocus();
                GetData(t_code.getText());
        }
    }
    private void UpdateCostInProduct(String Ingcode)
    {
        
        ResultSet rsmenuing =null;
        try {
            if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                stmt = (Statement) dbUtility.con.createStatement();
               
                String sqlmenuing = "select * from menusetup where incode = '"+cvth.Unicode2ASCII(Ingcode)+"'";
                rsmenuing = stmt.executeQuery(sqlmenuing);
                while (rsmenuing.next()) {
                  calculateLCostPLU.updatecostPLU(rsmenuing.getString("menucode"),calculateLCostPLU.calculatecost(rsmenuing.getString("menucode")));
                }
            } else {
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    public int chkMenuSetup(String code) {
        
        ResultSet rs = null;
        int count = 0;
        try {
            if (!db.Char_Set.equalsIgnoreCase("utf-8")) {
                stmt = (Statement) db.con.createStatement();
                String sql = "select * from menusetup where incode ='" + cvth.Unicode2ASCII(code) + "'";
                rs = stmt.executeQuery(sql);
                while (rs.next()) {
                    count++;
                }
            } else {
                stmt = (Statement) db.con.createStatement();
                String sql = "select * from menusetup where incode ='" + code + "'";
                rs = stmt.executeQuery(sql);
                while (rs.next()) {
                    count++;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            count = -1;
        }
        return count;
    }
}
