/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package masterfile;

import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import dbutility.dbUtility;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import utilititiesfunction.*;

/**
 *
 * @author shady
 */
public class VoidConfigSetup extends javax.swing.JFrame {

    dbUtility db = new dbUtility();
    private Statement stmt;
    DefaultTableModel tbCreditCardSetup;
    String frmName = "creditcardsetup";
    private Color colorEnable = new Color(255, 246, 143);
    private Color colorDisable2 = new Color(216, 215, 214);
    ThaiUtilities cvth = new ThaiUtilities();
    getLanguage lang = new getLanguage();

    /**
     * Creates new form branchsetting
     */
    public VoidConfigSetup() {
        initComponents();
        checkuserconfig();
        db.dbconnect();
        try {
            stmt = (Statement) dbUtility.con.createStatement();
        } catch (Exception e) {
        }
        tbCreditCardSetup = (DefaultTableModel) tbluser.getModel();
        tbluser.setShowGrid(true);
        tbluser.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tbluser.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbluser.setRowSelectionAllowed(true);
        tbluser.setBackground(java.awt.Color.WHITE);
        tbluser.setGridColor(java.awt.Color.gray);
        JTableHeader header = tbluser.getTableHeader();
        header.setFont(new java.awt.Font("Norasi", java.awt.Font.BOLD, 14));
        tbluser.setRowHeight(25);
        tbluser.setAutoCreateRowSorter(true);
        showdataintb();
        clear();
        //lang.setText(frmName, this, lang.getChklang());
    }

    public VoidConfigSetup(masterfile.NimbusFrame nimbusFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbluser = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t_code = new javax.swing.JTextField();
        t_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        t_qty1 = new javax.swing.JFormattedTextField();
        t_amt1 = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        t_qty2 = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        t_amt2 = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        t_otp = new javax.swing.JComboBox<>();
        t_sms = new javax.swing.JComboBox<>();
        t_email = new javax.swing.JComboBox<>();
        t_otp2 = new javax.swing.JComboBox<>();
        t_sms2 = new javax.swing.JComboBox<>();
        t_email2 = new javax.swing.JComboBox<>();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuFunc = new javax.swing.JMenu();
        menuCancel = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuDelete = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNew.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Add-icon.png"))); // NOI18N
        btnNew.setText("เพิ่มรายการ");
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setName("DBbtnadd"); // NOI18N
        btnNew.setRequestFocusEnabled(false);
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cancel-icon.png"))); // NOI18N
        btnCancel.setText("ยกเลิก");
        btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancel.setName("DBbtncancle"); // NOI18N
        btnCancel.setRequestFocusEnabled(false);
        btnCancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save-icon.png"))); // NOI18N
        btnSave.setText("บันทึกข้อมูล");
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setName("DBbtnsave"); // NOI18N
        btnSave.setRequestFocusEnabled(false);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete-icons.png"))); // NOI18N
        btnDelete.setText("ลบข้อมูล");
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setName("DBbtndel"); // NOI18N
        btnDelete.setRequestFocusEnabled(false);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Printer-icon.png"))); // NOI18N
        jButton6.setText("พิมพ์");
        jButton6.setEnabled(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setName("DBbtnprint"); // NOI18N
        jButton6.setRequestFocusEnabled(false);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LogOut-icon.png"))); // NOI18N
        jButton7.setText("ออก");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setName("DBbtnexit"); // NOI18N
        jButton7.setRequestFocusEnabled(false);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        tbluser.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        tbluser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "รหัสกลุ่ม", "ชื่อกลุ่ม", "Void ใน(ครั้ง)", "void ใน(บาท)", "void นอก(ครั้ง)", "void นอก(บาท)", "Send OTP", "Send SMS", "Send e-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbluser.setFocusable(false);
        tbluser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbluserMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbluser);
        if (tbluser.getColumnModel().getColumnCount() > 0) {
            tbluser.getColumnModel().getColumn(0).setPreferredWidth(100);
            tbluser.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbluser.getColumnModel().getColumn(2).setPreferredWidth(80);
            tbluser.getColumnModel().getColumn(3).setPreferredWidth(80);
            tbluser.getColumnModel().getColumn(4).setPreferredWidth(80);
            tbluser.getColumnModel().getColumn(5).setPreferredWidth(80);
            tbluser.getColumnModel().getColumn(6).setPreferredWidth(80);
            tbluser.getColumnModel().getColumn(7).setPreferredWidth(80);
            tbluser.getColumnModel().getColumn(8).setPreferredWidth(80);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel12.setFont(new java.awt.Font("Norasi", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("กำหนดแฟ้มข้อมูลกลุ่มสิทธิ์การ Void");
        jLabel12.setName("LBcreditcardsetup"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("รหัสกลุ่ม");
        jLabel1.setName("D_creditcode"); // NOI18N

        t_code.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        t_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_codeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_codeFocusLost(evt);
            }
        });
        t_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_codeKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_codeKeyPressed(evt);
            }
        });

        t_name.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_nameFocusLost(evt);
            }
        });
        t_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_nameKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ชื่อกลุ่ม");
        jLabel2.setName("D_creditname"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("สิทธิ์การ Void นอก");
        jLabel3.setName("D_mybankcode"); // NOI18N

        jLabel18.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("สิทธิ์การ Void ใน");
        jLabel18.setName("D_mybankcode"); // NOI18N

        jLabel19.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Use OTP Permission");
        jLabel19.setName("D_mybankcode"); // NOI18N

        t_qty1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        t_qty1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_qty1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_qty1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_qty1KeyPressed(evt);
            }
        });

        t_amt1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        t_amt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_amt1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_amt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_amt1KeyPressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("จำนวนครั้ง");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel20.setName("D_mybankcode"); // NOI18N

        jLabel21.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("จำนวนเงิน(บาท)");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel21.setName("D_mybankcode"); // NOI18N

        jLabel22.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("จำนวนครั้ง");
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel22.setName("D_mybankcode"); // NOI18N

        t_qty2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        t_qty2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_qty2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_qty2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_qty2KeyPressed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("จำนวนเงิน(บาท)");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel23.setName("D_mybankcode"); // NOI18N

        t_amt2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        t_amt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_amt2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_amt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_amt2KeyPressed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Send SMS");
        jLabel24.setName("D_mybankcode"); // NOI18N

        jLabel25.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Send e-mail");
        jLabel25.setName("D_mybankcode"); // NOI18N

        t_otp.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_otp.setMaximumRowCount(2);
        t_otp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));

        t_sms.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_sms.setMaximumRowCount(2);
        t_sms.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));

        t_email.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_email.setMaximumRowCount(2);
        t_email.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));

        t_otp2.setEditable(true);
        t_otp2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_otp2.setMaximumRowCount(2);
        t_otp2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));
        t_otp2.setRequestFocusEnabled(true);

        t_sms2.setEditable(true);
        t_sms2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_sms2.setMaximumRowCount(2);
        t_sms2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));

        t_email2.setEditable(true);
        t_email2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        t_email2.setMaximumRowCount(2);
        t_email2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));

        jLabel61.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        jLabel61.setText("Void ใน");

        jLabel62.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        jLabel62.setText("Void นอก");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t_email, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t_qty2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t_qty1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(t_otp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t_sms, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel23))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_amt1)
                                    .addComponent(t_amt2)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_email2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel62)
                                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(t_otp2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(t_sms2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_name)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(t_code, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(t_code, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(t_qty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel22)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_qty2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_amt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_amt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(jLabel62))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(t_otp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(t_sms, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(t_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(t_otp2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_sms2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_email2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuFunc.setText("ฟังก์ชั่น");
        menuFunc.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        menuFunc.setName("menuFunc"); // NOI18N

        menuCancel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menuCancel.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menuCancel.setText("ยกเลิก");
        menuCancel.setName("menuCancel"); // NOI18N
        menuCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCancelActionPerformed(evt);
            }
        });
        menuFunc.add(menuCancel);

        menuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSave.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menuSave.setText("บันทึกข้อมูล");
        menuSave.setName("menuSave"); // NOI18N
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        menuFunc.add(menuSave);

        menuDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuDelete.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menuDelete.setText("ลบข้อมูล");
        menuDelete.setName("menuDelete"); // NOI18N
        menuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeleteActionPerformed(evt);
            }
        });
        menuFunc.add(menuDelete);

        jSeparator1.setName("jSpeparator1"); // NOI18N
        menuFunc.add(jSeparator1);

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuExit.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menuExit.setText("Exit");
        menuExit.setName("menuExit"); // NOI18N
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuFunc.add(menuExit);

        jMenuBar2.add(menuFunc);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1024, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void checkuserconfig() {
        //MenuName = Mast1
        UserLogin userrec = UserLogin.userlogin;
        if (userrec.getMast17().equals("1")) {
            btnNew.setEnabled(false);
            btnSave.setEnabled(false);
            btnDelete.setEnabled(false);
            //menuNew.setEnabled(false);
            menuSave.setEnabled(false);
            menuDelete.setEnabled(false);
        }
        if (userrec.getMast17().equals("2")) {
            btnNew.setEnabled(true);
            btnSave.setEnabled(true);
            btnDelete.setEnabled(false);
            //menuNew.setEnabled(true);
            menuSave.setEnabled(true);
            menuDelete.setEnabled(false);
        }
        if (userrec.getMast17().equals("3")) {
            btnNew.setEnabled(true);
            btnSave.setEnabled(true);
            btnDelete.setEnabled(true);
            //menuNew.setEnabled(true);
            menuSave.setEnabled(true);
            menuDelete.setEnabled(true);
        }
    }
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        clear();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tbluserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbluserMouseReleased

        if (evt.getClickCount() == 2) {
            int index = tbluser.getSelectedRow();
            String creditcode = tbluser.getValueAt(index, 0).toString();
            if (t_code.getText().equals("")) {
                if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                    GetData(cvth.Unicode2ASCII(creditcode));
                } else {
                    GetData(creditcode);
                }
            } else if (!t_code.getText().equals(creditcode)) {
                int confirm = JOptionPane.showConfirmDialog(this, "คุณมีการเพิ่มหรือแก้ไขข้อมูลอยู่ คุณต้องการยกเลิกการเพิ่มหรือแก้ไขข้อมูลนั้นหรือไม่", "Confirm", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                        GetData(cvth.Unicode2ASCII(creditcode));
                    } else {
                        GetData(creditcode);
                    }
                }
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tbluserMouseReleased

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed

        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        if (!t_code.getText().trim().equals("") && chkdata(t_code.getText()) && t_name.isFocusable()) {
            delete();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (!t_code.getText().trim().equals("")) {
            btnsave();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void menuCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCancelActionPerformed
        //jButton2ActionPe(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCancelActionPerformed

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed
        //jButton3ActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSaveActionPerformed

    private void menuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeleteActionPerformed
        //jButton4ActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDeleteActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        jButton7ActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuExitActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
//        Map parm = new HashMap();
//        JRBeanCollectionDataSource ds = null;
//        ds = new JRBeanCollectionDataSource(report.dataBeanCreditfile.getCreditFile());
//        parm.put("companyName", lang.getTextCompanyReport());
//        parm.put("Reportheader", lang.getTextReport(frmName, "texthead"));
//        parm.put("code", lang.getTextReport(frmName, "code"));
//        parm.put("name", lang.getTextReport(frmName, "name"));
//        parm.put("other1", lang.getTextReport(frmName, "other1"));
//        parm.put("other2", lang.getTextReport(frmName, "other2"));
//        parm.put("other3", lang.getTextReport(frmName, "other3"));
//        parm.put("other4", lang.getTextReport(frmName, "other4"));
//        parm.put("other5", lang.getTextReport(frmName, "other5"));
//        parm.put("other6", lang.getTextReport(frmName, "other6"));
//        parm.put("other7", lang.getTextReport(frmName, "other7"));
//        parm.put("other8", lang.getTextReport(frmName, "other8"));
//        parm.put("other9", lang.getTextReport(frmName, "other9"));
//        parm.put("totalall", lang.getTextReport(frmName, "totalall"));
//        parm.put("branchtxt", lang.getTextReport(frmName, "branchtxt"));
//        parm.put("application", new GetApplicationName().getApplicationName());
//        parm.put("user", new GetUser().getUser());
//        parm.put("currentDate", Format.dateFmtReport.format(new java.util.Date()));
//        String rptName = "rptcreditfile";
//        Report rpt = new Report();
//        rpt.viewReportbean(rptName, parm, frmName, ds);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        t_code.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void t_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_nameKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_qty1.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nameKeyPressed

    private void t_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_nameFocusLost
        t_name.select(0, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nameFocusLost

    private void t_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_nameFocusGained
        t_name.setText(t_name.getText());
        t_name.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nameFocusGained

    private void t_codeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_codeKeyTyped

        if (t_code.getText().length() >= 8) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_codeKeyTyped

    private void t_codeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_codeKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!t_code.getText().equals("")) {

                setActive();
                t_name.requestFocus();
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_codeKeyPressed

    private void t_codeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_codeFocusLost
        if (!t_code.getText().equals("")) {

            GetData(t_code.getText());

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t_codeFocusLost

    private void t_codeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_codeFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_t_codeFocusGained

    private void t_qty1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_qty1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_amt1.requestFocus();
        }
    }//GEN-LAST:event_t_qty1KeyPressed

    private void t_amt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_amt1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_qty2.requestFocus();
        }
    }//GEN-LAST:event_t_amt1KeyPressed

    private void t_qty2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_qty2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_amt2.requestFocus();
        }
    }//GEN-LAST:event_t_qty2KeyPressed

    private void t_amt2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_amt2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_name.requestFocus();
        }
    }//GEN-LAST:event_t_amt2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoidConfigSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoidConfigSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoidConfigSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoidConfigSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VoidConfigSetup().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuCancel;
    private javax.swing.JMenuItem menuDelete;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuFunc;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JFormattedTextField t_amt1;
    private javax.swing.JFormattedTextField t_amt2;
    private javax.swing.JTextField t_code;
    private javax.swing.JComboBox<String> t_email;
    private javax.swing.JComboBox<String> t_email2;
    private javax.swing.JTextField t_name;
    private javax.swing.JComboBox<String> t_otp;
    private javax.swing.JComboBox<String> t_otp2;
    private javax.swing.JFormattedTextField t_qty1;
    private javax.swing.JFormattedTextField t_qty2;
    private javax.swing.JComboBox<String> t_sms;
    private javax.swing.JComboBox<String> t_sms2;
    private javax.swing.JTable tbluser;
    // End of variables declaration//GEN-END:variables

    public void clear() {
        t_code.setText("");
        t_code.setBackground(java.awt.Color.white);
        t_code.requestFocus();
        t_code.setEditable(true);
        t_name.setText("");
        t_qty1.setValue(0);
        t_qty2.setValue(0);
        t_amt1.setValue(0);
        t_amt2.setValue(0);
        t_otp.setSelectedIndex(0);
        t_sms.setSelectedIndex(0);
        t_email.setSelectedIndex(0);
        t_otp2.setSelectedIndex(0);
        t_sms2.setSelectedIndex(0);
        t_email2.setSelectedIndex(0);
        setUnActive();
        t_code.requestFocus();

    }

    private void setActive() {
        setActive(true, colorEnable);
    }

    private void setUnActive() {
        setActive(false, colorDisable2);
    }

    private void setActive(boolean active, Color color) {
        t_name.setFocusable(active);
        t_qty1.setFocusable(active);
        t_qty2.setFocusable(active);
        t_amt1.setFocusable(active);
        t_amt2.setFocusable(active);
        t_otp.setFocusable(active);
        t_sms.setFocusable(active);
        t_email.setFocusable(active);
        if (active == false) {
            t_code.setFocusable(true);
            t_code.setBackground(Color.WHITE);
        } else {
            t_code.setFocusable(false);
            t_code.setBackground(new java.awt.Color(249, 252, 186));

        }
    }

    public void GetData(String Code) {
        String credit = "";
        if (CheckValidEnter()) {
            try {
                String sql = "select * from voidconfig where v_code='" + Code + "'";

                stmt = (Statement) dbUtility.con.createStatement();
                ResultSet rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                        t_code.setText(cvth.ASCII2Unicode(rs.getString("v_code")));
                        t_name.setText(cvth.ASCII2Unicode(rs.getString("v_name")));
                        t_qty1.setValue(rs.getDouble("v_voidcnt"));
                        t_amt1.setValue(rs.getDouble("v_voidamt"));
                        t_qty2.setValue(rs.getDouble("v_refundcnt"));
                        t_amt2.setValue(rs.getDouble("v_refundamt"));
                        if (rs.getString("v_otp").equals("Y")) {
                            t_otp.setSelectedIndex(0);
                        } else {
                            t_otp.setSelectedIndex(1);
                        }
                        if (rs.getString("v_sms").equals("Y")) {
                            t_sms.setSelectedIndex(0);
                        } else {
                            t_sms.setSelectedIndex(1);
                        }
                        if (rs.getString("v_email").equals("Y")) {
                            t_email.setSelectedIndex(0);
                        } else {
                            t_email.setSelectedIndex(1);
                        }
                        //==============================
                         if (rs.getString("v_otp2").equals("Y")) {
                            t_otp2.setSelectedIndex(0);
                        } else {
                            t_otp2.setSelectedIndex(1);
                        }
                        if (rs.getString("v_sms2").equals("Y")) {
                            t_sms2.setSelectedIndex(0);
                        } else {
                            t_sms2.setSelectedIndex(1);
                        }
                        if (rs.getString("v_email2").equals("Y")) {
                            t_email2.setSelectedIndex(0);
                        } else {
                            t_email2.setSelectedIndex(1);
                        }
                    } else {
                        t_code.setText(rs.getString("v_code"));
                        t_name.setText(rs.getString("v_name"));
                        t_qty1.setValue(rs.getDouble("v_voidcnt"));
                        t_amt1.setValue(rs.getDouble("v_voidamt"));
                        t_qty2.setValue(rs.getDouble("v_refundcnt"));
                        t_amt2.setValue(rs.getDouble("v_refundamt"));
                        if (rs.getString("v_otp").equals("Y")) {
                            t_otp.setSelectedIndex(0);
                        } else {
                            t_otp.setSelectedIndex(1);
                        }
                        if (rs.getString("v_sms").equals("Y")) {
                            t_sms.setSelectedIndex(0);
                        } else {
                            t_sms.setSelectedIndex(1);
                        }
                        if (rs.getString("v_email").equals("Y")) {
                            t_email.setSelectedIndex(0);
                        } else {
                            t_email.setSelectedIndex(1);
                        }
                        //==============================
                         if (rs.getString("v_otp2").equals("Y")) {
                            t_otp2.setSelectedIndex(0);
                        } else {
                            t_otp2.setSelectedIndex(1);
                        }
                        if (rs.getString("v_sms2").equals("Y")) {
                            t_sms2.setSelectedIndex(0);
                        } else {
                            t_sms2.setSelectedIndex(1);
                        }
                        if (rs.getString("v_email2").equals("Y")) {
                            t_email2.setSelectedIndex(0);
                        } else {
                            t_email2.setSelectedIndex(1);
                        }
                    }
                } else {
                    t_name.requestFocus();
                }
                rs.close();
                stmt.close();
                setActive();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }

    public boolean CheckValidEnter() {
        boolean RetVal2 = true;
        if (t_code.getText().length() > 10) {
            JOptionPane.showMessageDialog(this, "กำหนดรหัสบัตรเครดิตไม่ถูกต้อง...(ตัองมีขนาดไม่เกิน 10 ตัวอักษร)");
            RetVal2 = false;
            t_code.requestFocus();
        }
        return RetVal2;
    }

    public void showdataintb() {
        stmt = null;
        ResultSet rs = null;
        tbCreditCardSetup = (DefaultTableModel) tbluser.getModel();
        int cnt = tbCreditCardSetup.getRowCount();
        if (cnt > 0) {
            for (int i = 0; i < cnt; i++) {
                tbCreditCardSetup.removeRow(0);
            }
        }
        try {
            stmt = (Statement) dbUtility.con.createStatement();
            String sql = "select * from voidconfig order by v_Code";
            rs = stmt.executeQuery(sql);
            while (rs.next()) {
                {
                    if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                        tbCreditCardSetup.addRow(new Object[]{cvth.ASCII2Unicode(rs.getString("v_code")),
                            cvth.ASCII2Unicode(rs.getString("v_name")),
                            cvth.ASCII2Unicode(rs.getString("v_voidcnt")),
                            cvth.ASCII2Unicode(rs.getString("v_voidamt")),
                            cvth.ASCII2Unicode(rs.getString("v_refundcnt")),
                            cvth.ASCII2Unicode(rs.getString("v_refundamt")),
                            cvth.ASCII2Unicode(rs.getString("v_otp")),
                            cvth.ASCII2Unicode(rs.getString("v_sms")),
                            cvth.ASCII2Unicode(rs.getString("v_email"))
                        });
                    } else {
                        tbCreditCardSetup.addRow(new Object[]{rs.getString("v_code"),
                            rs.getString("v_name"),
                            rs.getString("v_voidcnt"),
                            rs.getString("v_voidamt"),
                            rs.getString("v_refundcnt"),
                            rs.getString("v_refundamt"),
                            rs.getString("v_otp"),
                            rs.getString("v_sms"),
                            rs.getString("v_email")
                        });
                    }
                }
            }
        } catch (Exception e) {
        }
    }

    public void btnsave() {
        if (CheckValidSave()) {
            if (chkdata(t_code.getText())) {
                try {
                    if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                        stmt = (Statement) dbUtility.con.createStatement();
                        String sql = "Update voidconfig set v_name=?,v_voidcnt=?,v_voidamt=?,v_refundcnt=?,v_refundamt=?,v_otp=?,v_sms=?,v_email=?,v_otp2=?,v_sms2=?,v_email2=?  "
                                + "where v_code = ?";
                        PreparedStatement prm = (PreparedStatement) dbUtility.con.prepareStatement(sql);
                        prm.setString(1, cvth.Unicode2ASCII(t_name.getText()));
                        prm.setDouble(2, Double.parseDouble(t_qty1.getValue().toString()));
                        prm.setDouble(3, Double.parseDouble(t_amt1.getValue().toString()));
                        prm.setDouble(4, Double.parseDouble(t_qty2.getValue().toString()));
                        prm.setDouble(5, Double.parseDouble(t_amt2.getValue().toString()));
                        if (t_otp.getSelectedIndex() == 0) {
                            prm.setString(6, "Y");
                        } else {
                            prm.setString(6, "N");
                        }
                        if (t_sms.getSelectedIndex() == 0) {
                            prm.setString(7, "Y");
                        } else {
                            prm.setString(7, "N");
                        }
                        if (t_email.getSelectedIndex() == 0) {
                            prm.setString(8, "Y");
                        } else {
                            prm.setString(8, "N");
                        }
                        //=============================================
                         if (t_otp2.getSelectedIndex() == 0) {
                            prm.setString(9, "Y");
                        } else {
                            prm.setString(9, "N");
                        }
                        if (t_sms2.getSelectedIndex() == 0) {
                            prm.setString(10, "Y");
                        } else {
                            prm.setString(10, "N");
                        }
                        if (t_email2.getSelectedIndex() == 0) {
                            prm.setString(11, "Y");
                        } else {
                            prm.setString(11, "N");
                        }
                        prm.setString(12, cvth.Unicode2ASCII(t_code.getText()));
                        prm.executeUpdate();
                    } else {
                        stmt = (Statement) dbUtility.con.createStatement();
                        String sql = "Update voidconfig set v_name=?,v_voidcnt=?,v_voidamt=?,v_refundcnt=?,v_refundamt=?,v_otp=?,v_sms=?,v_email=?,v_otp2=?,v_sms2=?,v_email2=?   "
                                + "where v_code = ?";
                        PreparedStatement prm = (PreparedStatement) dbUtility.con.prepareStatement(sql);
                        prm.setString(1, t_name.getText());
                        prm.setDouble(2, Double.parseDouble(t_qty1.getValue().toString()));
                        prm.setDouble(3, Double.parseDouble(t_amt1.getValue().toString()));
                        prm.setDouble(4, Double.parseDouble(t_qty2.getValue().toString()));
                        prm.setDouble(5, Double.parseDouble(t_amt2.getValue().toString()));
                        if (t_otp.getSelectedIndex() == 0) {
                            prm.setString(6, "Y");
                        } else {
                            prm.setString(6, "N");
                        }
                        if (t_sms.getSelectedIndex() == 0) {
                            prm.setString(7, "Y");
                        } else {
                            prm.setString(7, "N");
                        }
                        if (t_email.getSelectedIndex() == 0) {
                            prm.setString(8, "Y");
                        } else {
                            prm.setString(8, "N");
                        }
                        //=============================================
                         if (t_otp2.getSelectedIndex() == 0) {
                            prm.setString(9, "Y");
                        } else {
                            prm.setString(9, "N");
                        }
                        if (t_sms2.getSelectedIndex() == 0) {
                            prm.setString(10, "Y");
                        } else {
                            prm.setString(10, "N");
                        }
                        if (t_email2.getSelectedIndex() == 0) {
                            prm.setString(11, "Y");
                        } else {
                            prm.setString(11, "N");
                        }
                        prm.setString(12, t_code.getText());
                        prm.executeUpdate();
                    }
                    stmt.close();
                    clear();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "Update Void Config Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                try {
                    if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                        stmt = (Statement) dbUtility.con.createStatement();
                        String sql = "Insert into voidconfig (v_code,v_name,v_voidcnt,v_voidamt,v_refundcnt,v_refundamt,v_otp,v_sms,v_email,v_otp2,v_sms2,v_email2) "
                                + " values(?,?,?,?,?,?,?,?,?,?,?,?)";
                        PreparedStatement prm = (PreparedStatement) dbUtility.con.prepareStatement(sql);
                        prm.setString(1, cvth.Unicode2ASCII(t_code.getText()));
                        prm.setString(2, cvth.Unicode2ASCII(t_name.getText()));
                        prm.setDouble(3, Double.parseDouble(t_qty1.getValue().toString()));
                        prm.setDouble(4, Double.parseDouble(t_amt1.getValue().toString()));
                        prm.setDouble(5, Double.parseDouble(t_qty2.getValue().toString()));
                        prm.setDouble(6, Double.parseDouble(t_amt2.getValue().toString()));
                        if (t_otp.getSelectedIndex() == 0) {
                            prm.setString(7, "Y");
                        } else {
                            prm.setString(7, "N");
                        }
                        if (t_sms.getSelectedIndex() == 0) {
                            prm.setString(8, "Y");
                        } else {
                            prm.setString(8, "N");
                        }
                        if (t_email.getSelectedIndex() == 0) {
                            prm.setString(9, "Y");
                        } else {
                            prm.setString(9, "N");
                        }
                         //=============================================
                         if (t_otp2.getSelectedIndex() == 0) {
                            prm.setString(10, "Y");
                        } else {
                            prm.setString(10, "N");
                        }
                        if (t_sms2.getSelectedIndex() == 0) {
                            prm.setString(11, "Y");
                        } else {
                            prm.setString(11, "N");
                        }
                        if (t_email2.getSelectedIndex() == 0) {
                            prm.setString(12, "Y");
                        } else {
                            prm.setString(12, "N");
                        }
                        prm.executeUpdate();
                    } else {
                        stmt = (Statement) dbUtility.con.createStatement();
                        String sql = "Insert into voidconfig (v_code,v_name,v_voidcnt,v_voidamt,v_refundcnt,v_refundamt,v_otp,v_sms,v_email,v_otp2,v_sms2,v_email2) "
                                + " values(?,?,?,?,?,?,?,?,?,?,?,?)";
                        PreparedStatement prm = (PreparedStatement) dbUtility.con.prepareStatement(sql);
                        prm.setString(1, t_code.getText());
                        prm.setString(2, t_name.getText());
                        prm.setDouble(3, Double.parseDouble(t_qty1.getValue().toString()));
                        prm.setDouble(4, Double.parseDouble(t_amt1.getValue().toString()));
                        prm.setDouble(5, Double.parseDouble(t_qty2.getValue().toString()));
                        prm.setDouble(6, Double.parseDouble(t_amt2.getValue().toString()));
                        if (t_otp.getSelectedIndex() == 0) {
                            prm.setString(7, "Y");
                        } else {
                            prm.setString(7, "N");
                        }
                        if (t_sms.getSelectedIndex() == 0) {
                            prm.setString(8, "Y");
                        } else {
                            prm.setString(8, "N");
                        }
                        if (t_email.getSelectedIndex() == 0) {
                            prm.setString(9, "Y");
                        } else {
                            prm.setString(9, "N");
                        }
                        //=============================================
                         if (t_otp2.getSelectedIndex() == 0) {
                            prm.setString(10, "Y");
                        } else {
                            prm.setString(10, "N");
                        }
                        if (t_sms2.getSelectedIndex() == 0) {
                            prm.setString(11, "Y");
                        } else {
                            prm.setString(11, "N");
                        }
                        if (t_email2.getSelectedIndex() == 0) {
                            prm.setString(12, "Y");
                        } else {
                            prm.setString(12, "N");
                        }
                        prm.executeUpdate();
                    }
                    stmt.close();
                    clear();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "Insert Void User Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            showdataintb();
        }
    }

    public boolean chkdata(String pk) {
        boolean chk = false;
        ResultSet rs = null;
        try {
            if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                stmt = (Statement) dbUtility.con.createStatement();
                String sql = "select * from voidconfig where v_code ='" + cvth.Unicode2ASCII(pk) + "'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    chk = true;
                }
            } else {
                stmt = (Statement) dbUtility.con.createStatement();
                String sql = "select * from voidconfig where v_code ='" + pk + "'";
                rs = stmt.executeQuery(sql);
                if (rs.next()) {
                    chk = true;
                }
            }
        } catch (Exception e) {
        }
        return chk;
    }

    public boolean CheckValidSave() {
        boolean chk = true;
        if (!t_name.isFocusable()) {
            chk = false;
        } else if (t_code.getText().length() > 10) {
            JOptionPane.showMessageDialog(this, "กำหนดรหัสกลุ่มสิทธิ์การ Void ไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 10 ตัวอักษร)");
            chk = false;
            t_code.requestFocus();
        } else if (t_name.getText().length() > 50) {
            JOptionPane.showMessageDialog(this, "กำหนดชื่อกลุ่มสิทธิ์การ Void ไม่ถูกต้อง... (ต้องมีขนาดไม่เกิน 50 ตัวอักษร)");
            chk = false;
            t_name.requestFocus();
        }
        return chk;
    }

    public void delete() {
        try {
            int confirm = JOptionPane.showConfirmDialog(this, "คุณต้องการลบข้อมูลรายการนี้หรือไม่...?", "Confirm", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                if (!dbUtility.Char_Set.equalsIgnoreCase("utf-8")) {
                    stmt = (Statement) dbUtility.con.createStatement();
                    String sql = "Delete from voidconfig where v_code = ?";
                    PreparedStatement prm = (PreparedStatement) dbUtility.con.prepareStatement(sql);
                    prm.setString(1, cvth.Unicode2ASCII(t_code.getText()));
                    prm.executeUpdate();
                    stmt.close();
                } else {
                    stmt = (Statement) dbUtility.con.createStatement();
                    String sql = "Delete from voidconfig where v_code = ?";
                    PreparedStatement prm = (PreparedStatement) dbUtility.con.prepareStatement(sql);
                    prm.setString(1, t_code.getText());
                    prm.executeUpdate();
                    stmt.close();
                }
                //Delete From Branch_void
                clear();
                showdataintb();
            }
        } catch (Exception e) {
        }
    }
}
